objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Shift Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Make__c</fullName>
        <formula>TEXT(Vehicle_ID__r.Make__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The region in which the seller&apos;s vehicle was acquired</description>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Vehicle_ID__r.Display_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Represents a region for vehicle activity (acquire, sell, etc).</description>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Listing_Region_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Listing Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <picklist>
            <picklistValues>
                <fullName>Acura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alfa Romeo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aston Martin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bentley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bugatti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadillac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chevrolet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chrysler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daewoo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dodge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferrari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fisker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hummer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyundai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infiniti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Isuzu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaguar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jeep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lamborghini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyota</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a seller opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShiftSellerVehicleSyncTest.cls
@isTest public class ShiftSellerVehicleSyncTest {

	@testSetup private static void setup() { ShiftTesting.setup(); }

	private static Vehicle__c createTestVehicle() {
		return new Vehicle__c(
			Name = 'test vehicle',
			Year__c = 2001,
			Make__c = 'Toyota',
			Model__c = 'Corolla',
			Listing_Region_ID__r = new Region__c(Shift_Key__c = 'testing')
		);
	}

	private static Vehicle__c insertTestVehicle() {
		Vehicle__c res = createTestVehicle();
		insert res;
		return res;
	}

	private static Opportunity createSellerOpportunity(Id vehicleId) {
		Account acct = new Account(Name = 'Test Account');
		insert acct;
		List<RecordType> recTypes = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Seller'];
		return new Opportunity(
			Name = 'test seller',
			AccountId = acct.Id,
			RecordTypeId = recTypes.get(0).Id,
			StageName = 'Quote and Schedule',
			CloseDate = Date.today().addDays(60),
			Vehicle_ID__c = vehicleId,
			Region_ID__r = [SELECT Id FROM Region__c WHERE Shift_Key__c = 'testing']
		);
	}

	private static Opportunity insertSellerOpportunity(Id vehicleId) {
		Opportunity res = createSellerOpportunity(vehicleId);
		insert res;
		return res;
	}

	private static void expectVehicleSellerOpportunityID(Vehicle__c v, Opportunity seller) {
		Vehicle__c act = [SELECT Seller_Opportunity_ID__c FROM Vehicle__c WHERE Id = :v.Id];
		Id expctSellerId = null;
		if (seller != null) {
			expctSellerId = seller.Id;
		}
		System.assertEquals(expctSellerId, act.Seller_Opportunity_Id__c);
	}

	@isTest private static void testOneOpportunityOneVehicle() {
		// insert a vehicle v1 and a seller opp s1 and check that v1 points to s1
		Vehicle__c v1 = insertTestVehicle();
		System.assert(v1.Id != null);
		Opportunity s1 = insertSellerOpportunity(v1.Id);
		expectVehicleSellerOpportunityID(v1, s1);
	}

	@isTest private static void testOpportunityWithChangedVehicle() {
		Vehicle__c v1 = insertTestVehicle();
		Opportunity s1 = insertSellerOpportunity(v1.Id);
		// change s1 to point to a new vehicle v2, and check that v1 points
		// to no seller opp and and v2 points to s1
		Vehicle__c v2 = insertTestVehicle();
		s1.Vehicle_ID__c = v2.Id;
		update s1;
		expectVehicleSellerOpportunityID(v2, s1);
		expectVehicleSellerOpportunityID(v1, null);
	}

	@isTest private static void testMultipleOpportunitiesOneVehicle() {
		Vehicle__c v1 = insertTestVehicle();
		Opportunity s1 = insertSellerOpportunity(v1.Id);
		// attempt to insert opp s2 pointing at v1 and expect an error 
		try {
			Opportunity s2 = insertSellerOpportunity(v1.Id);
			System.assert(false, 'was able to insert multiple sellers for a single vehicle');
		} catch (DmlException dme) {
			System.assert(dme.getMessage().contains('attempt to reference vehicle from seller opportunity'), dme.getMessage());
		}
	}

	@isTest private static void testVehicleWithDeletedSeller() {
		Vehicle__c v1 = insertTestVehicle();
		Opportunity s1 = insertSellerOpportunity(v1.Id);
		// delete s1 and assert that v points nowhere
		delete s1;
		expectVehicleSellerOpportunityID(v1, null);
	}

	@isTest private static void testMutipleOpportunitiesOneVehicleInsertBatch() {
		// check that we get failure when two opps in the same insert batch
		// point to the same vehicle 
		Vehicle__c v1 = insertTestVehicle();
		List<Opportunity> opps = new List<Opportunity>();
		opps.add(createSellerOpportunity(v1.Id));
		opps.add(createSellerOpportunity(v1.Id));
		try {
			insert opps;
			System.assert(false, 'was able to insert multiple sellers for same vehicle in a single batch');
		} catch (DmlException dme) {
			System.assert(dme.getMessage().contains('operation contains multiple assignments to vehicle'), dme.getMessage());
		}
	}

	@isTest private static void testMutipleOpportunitiesOneVehicleUpdateBatch() {
		// check that we get failure when two opps in the same update batch
		// point to the same vehicle 
		Vehicle__c v1 = insertTestVehicle();
		Vehicle__c v2 = insertTestVehicle();
		Opportunity s1 = insertSellerOpportunity(v1.Id);
		Opportunity s2 = insertSellerOpportunity(v2.Id);
		List<Opportunity> opps = new List<Opportunity>{s1, s2};
		Vehicle__c v3 = insertTestVehicle();
		s1.Vehicle_ID__c = v3.Id;
		s2.Vehicle_ID__c = v3.Id;
		try {
			update opps;
			System.assert(false, 'was able to update multiple sellers for same vehicle in a single batch');
		} catch (DmlException dme) {
			System.assert(dme.getMessage().contains('operation contains multiple assignments to vehicle'), dme.getMessage());
		}
	}

	@isTest private static void testBatchOperationsNoErrors() {
		// (regression) check that batch deletes do not encounter errors
		Test.startTest();
		List<Opportunity> oppsToDel = new List<Opportunity>();
		List<Vehicle__c> vehiclesToDel = new List<Vehicle__c>();
		for (Integer i = 0; i < 2; i++) {
			Vehicle__c vhToDel = insertTestVehicle();
			vehiclesToDel.add(vhToDel);
			Opportunity oppToDel = insertSellerOpportunity(vhToDel.Id);
			oppsToDel.add(oppToDel);
		}
		Test.stopTest();
		delete oppsToDel;
		// (regression) check that batch inserts do not encounter errors
		List<Vehicle__c> vehiclesToIns = new List<Vehicle__c>();
		for (Integer i = 0; i < 2; i++) {
			vehiclesToIns.add(createTestVehicle());
		}
		insert vehiclesToIns;
		List<Opportunity> oppsToIns = new List<Opportunity>();
		for (Vehicle__c vh : vehiclesToIns) {
			oppsToIns.add(createSellerOpportunity(vh.Id));
		}
		insert oppsToIns;
	}
}