objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Shift Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Days_Guaranteed__c</fullName>
        <label>Days Guaranteed</label>
        <picklist>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entered_Stage_Prepare_Car_For_Sale__c</fullName>
        <label>Entered Stage Prepare Car For Sale</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Flat_Fee_Percent__c</fullName>
        <label>Flat Fee - Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Flat_Fee__c</fullName>
        <label>Flat Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <formula>Vehicle_ID__r.List_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>TEXT(Vehicle_ID__r.Make__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <formula>Vehicle_ID__r.Mileage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricing_Strategy__c</fullName>
        <label>Pricing Strategy</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Fee - Dollar Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Fee - Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Price - 0% Upside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specific Car Search</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The region in which the seller&apos;s vehicle was acquired</description>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Contract_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Contract</label>
        <referenceTo>Shift_Contract__c</referenceTo>
        <relationshipLabel>Opportunities (Seller Contract)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Upside_Percentage__c</fullName>
        <label>Seller Upside Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Specific_Car_Search_Fee__c</fullName>
        <label>Specific Car Search Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Specific_Car_Search__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Specific Car Search</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Vehicle_ID__r.Display_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Buyer</fullName>
        <active>true</active>
        <businessProcess>Buyer</businessProcess>
        <label>Buyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Parking_Lot__c.object
<CustomObject>
    <description>Represents a parking lot location</description>
    <fields>
        <fullName>Region_ID__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Parking Lots</relationshipLabel>
        <relationshipName>Parking_Lots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Parking Lot</label>
    <nameField>
        <label>Parking Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parking Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Represents a region for vehicle activity (acquire, sell, etc).</description>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shift_Contract__c.object
<CustomObject>
    <description>Represents a specific version of a contract, related to some contract execution.</description>
    <fields>
        <fullName>Expires_On__c</fullName>
        <label>Expires On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Shift Contracts</relationshipLabel>
        <relationshipName>Shift_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shift Contract</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Shift Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shift Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>San Francisco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sacramento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Diego</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Body_Style__c</fullName>
        <label>Body Style</label>
        <picklist>
            <picklistValues>
                <fullName>Convertible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sedan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Van</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wagon</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exterior_Color__c</fullName>
        <label>Exterior Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Listing_Region_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Listing Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <picklist>
            <picklistValues>
                <fullName>Acura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alfa Romeo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aston Martin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bentley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bugatti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadillac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chevrolet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chrysler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daewoo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dodge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferrari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fisker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hummer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyundai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infiniti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Isuzu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaguar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jeep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lamborghini</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parking_Lot_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parking Lot</label>
        <referenceTo>Parking_Lot__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle_Order__c.object
<CustomObject>
    <description>Orders represent the process of a Buyer purchasing a Vehicle. Note that we don&apos;t name this object simple &quot;Order&quot; so as to avoid confusion with the standard salesforce Order object. We may one day decide to use that object instead, but not until we understand more about whether it fits with our model.</description>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShiftOpportunityTriggersTest.cls
@IsTest
private class ShiftOpportunityTriggersTest {

	@TestSetup private static void setup() { ShiftTesting.setup(); }

	static void insertOpportunity(boolean seller) {
		Region__c region = new Region__c(
			Name = 'Test Region',
			Shift_Key__c = 'us/sfo',
			Timezone__c = ShiftTesting.REGION_TIMEZONE_TESTING
		);
		insert region;
		insert ShiftTesting.createRandomParkingLot(region.Id, true);

		Account acct = new Account(Name = 'John Doe');
		insert acct;

		RecordType recordTypeSeller = [SELECT Id FROM RecordType WHERE DeveloperName = 'Seller' AND SObjectType = 'Opportunity'];
		RecordType recordTypeBuyer = [SELECT Id FROM RecordType WHERE DeveloperName = 'Buyer' AND SObjectType = 'Opportunity'];

		Opportunity opp = new Opportunity(
			CloseDate = Date.parse('01/02/3000'),
			StageName = seller ? ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE : ShiftConstants.BUYER_OPPORTUNITY_STAGE_QUALIFIED,
			RecordTypeId = seller ? recordTypeSeller.Id : recordTypeBuyer.Id,
			AccountId = acct.Id,
			Region_ID__r = new Region__c(Shift_Key__c = ShiftTesting.REGION_SHIFT_KEY_TESTING)
		);

		if (seller) {
			Vehicle__c bmw = new Vehicle__c(
				Year__c = 2010,
				Make__c = 'BMW',
				Model__c = '328i',
				Body_Style__c = 'Sedan',
				Exterior_Color__c = 'white',
				Mileage__c = 52000,
				List_Price__c = 20,
				Listing_Region_ID__c = region.ID
			);
			insert bmw;
			opp.Vehicle_ID__c = bmw.Id;
		}
		insert opp;
	}

	@IsTest
	static void testSeller() {
		insertOpportunity(true);
		System.assertEquals('2010 BMW 328i - John Doe - white', [SELECT Name FROM Opportunity LIMIT 1].Name);
	}

	@IsTest
	static void testSellerColorChange() {
		insertOpportunity(true);
		System.assertEquals('2010 BMW 328i - John Doe - white', [SELECT Name FROM Opportunity LIMIT 1].Name);
		Vehicle__c vehicle = [SELECT Id FROM Vehicle__c];
		vehicle.Exterior_Color__c = 'black';
		update vehicle;
		System.assertEquals('2010 BMW 328i - John Doe - black', [SELECT Name FROM Opportunity LIMIT 1].Name);
	}

	@IsTest
	static void testOpportunityInsertWithStagePrepare() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Shift_Contract__c sellerContract = ShiftTesting.createAndInsertShiftContract(ctx.opportunity.Id);
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		ctx.opportunity.Days_Guaranteed__c = '75';
		ctx.opportunity.Seller_Contract_ID__c = sellerContract.Id;
		ctx.insertOpportunity();

		System.assertEquals(Date.today().addDays(75), [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
		System.assertEquals(ShiftTesting.PARKING_LOT_NAME_TESTING, [SELECT Parking_Lot_ID__r.Name FROM Vehicle__c WHERE Id = :ctx.vehicle.Id].Parking_Lot_ID__r.Name);
	}

	@IsTest
	static void testSellerContractOnOpportunityInsertWithStageSell() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Shift_Contract__c sellerContract = ShiftTesting.createAndInsertShiftContract(ctx.opportunity.Id);
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL;
		ctx.opportunity.Days_Guaranteed__c = '75';
		ctx.opportunity.Seller_Contract_ID__c = sellerContract.Id;
		ctx.insertOpportunity();

		System.assertEquals(null, [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
	}

	@IsTest
	static void testSellerContractOnOpportunityWithNoSellerContract() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		ctx.opportunity.Days_Guaranteed__c = '75';
		ctx.insertOpportunity();

		// Ensure that the contract still doesn't exist and a task was created.
		System.assertEquals(null, [SELECT Seller_Contract_ID__c FROM Opportunity WHERE Id = :ctx.opportunity.Id].Seller_Contract_ID__c);
		System.assertEquals(0, [SELECT COUNT() FROM Shift_Contract__c WHERE Opportunity_ID__c = :ctx.opportunity.Id]);
		System.assertEquals(1, [SELECT COUNT() FROM Task WHERE Subject = :ShiftConstants.TASK_SUBJECT_INPUT_CONTRACT_EXPIRATION_DATE]);

		// Update the opportunity.
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL;
		ctx.opportunity.Entered_Stage_Prepare_Car_For_Sale__c = DateTime.now().addDays(-10);
		update ctx.opportunity;

		// Ensure that the contract still doesn't exist and a task was created.
		System.assertEquals(null, [SELECT Seller_Contract_ID__c FROM Opportunity WHERE Id = :ctx.opportunity.Id].Seller_Contract_ID__c);
		System.assertEquals(0, [SELECT COUNT() FROM Shift_Contract__c WHERE Opportunity_ID__c = :ctx.opportunity.Id]);
		System.assertEquals(1, [SELECT COUNT() FROM Task WHERE Subject = :ShiftConstants.TASK_SUBJECT_REVIEW_CONTRACT_EXPIRATION_DATE]);
	}

	@IsTest
	static void testSellerContractOnOpportunityWithNoDaysGuaranteed() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Shift_Contract__c sellerContract = ShiftTesting.createAndInsertShiftContract(ctx.opportunity.Id);
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		ctx.opportunity.Seller_Contract_ID__c = sellerContract.Id;
		ctx.insertOpportunity();

		// Ensure that the contract's expiration date isn't set and a task is created.
		System.assertEquals(null, [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
		System.assertEquals(1, [SELECT COUNT() FROM Task WHERE Subject = :ShiftConstants.TASK_SUBJECT_INPUT_CONTRACT_EXPIRATION_DATE]);

		// Update the opportunity.
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL;
		ctx.opportunity.Entered_Stage_Prepare_Car_For_Sale__c = DateTime.now().addDays(-10);
		update ctx.opportunity;

		// Ensure that the contract's expiration date still isn't set and a task is created.
		System.assertEquals(null, [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
		System.assertEquals(1, [SELECT COUNT() FROM Task WHERE Subject = :ShiftConstants.TASK_SUBJECT_REVIEW_CONTRACT_EXPIRATION_DATE]);
	}

	@IsTest
	static void testOpportunityUpdateToStagePrepare() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Shift_Contract__c sellerContract = ctx.signSellerContract();
		ctx.opportunity.Days_Guaranteed__c = '75';
		ctx.insertOpportunity();

		Test.startTest();
		System.assertEquals(null, [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
		System.assertEquals(null, [SELECT Parking_Lot_ID__c FROM Vehicle__c WHERE Id = :ctx.vehicle.Id].Parking_Lot_ID__c);

		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_EVALUATE;
		update ctx.opportunity;
		System.assertEquals(null, [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
		System.assertEquals(null, [SELECT Parking_Lot_ID__c FROM Vehicle__c WHERE Id = :ctx.vehicle.Id].Parking_Lot_ID__c);

		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		update ctx.opportunity;
		System.assertEquals(Date.today().addDays(75), [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
		System.assertEquals(ShiftTesting.PARKING_LOT_NAME_TESTING, [SELECT Parking_Lot_ID__r.Name FROM Vehicle__c WHERE Id = :ctx.vehicle.Id].Parking_Lot_ID__r.Name);
		Test.stopTest();
	}

	@IsTest
	static void testOpportunityUpdateToStagePrepareWithNoContract() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		insert ctx.opportunity;

		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_EVALUATE;
		update ctx.opportunity;

		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		ShiftTesting.expectUpdateExceptionContains(ctx.opportunity, 'Cannot change to stage ' + ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE + ': Seller Contract Signed On cannot be empty');
	}

	@IsTest
	static void testSellerContractOnOpportunityUpdateToStageSellAfterSevenDays() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Shift_Contract__c sellerContract = ShiftTesting.createAndInsertShiftContract(ctx.opportunity.Id);
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		ctx.opportunity.Days_Guaranteed__c = '75';
		ctx.opportunity.Seller_Contract_ID__c = sellerContract.Id;
		ctx.insertOpportunity();

		// Update the opportunity.
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL;
		ctx.opportunity.Entered_Stage_Prepare_Car_For_Sale__c = DateTime.now().addDays(-10);
		ctx.opportunity.Days_Guaranteed__c = '50';
		update ctx.opportunity;

		// Ensure that the expiration date is updated.
		System.assertEquals(Date.today().addDays(50), [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
	}

	@IsTest
	static void testSellerContractOnOpportunityUpdateToStageSellBeforeSevenDays() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Shift_Contract__c sellerContract = ShiftTesting.createAndInsertShiftContract(ctx.opportunity.Id);
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		ctx.opportunity.Days_Guaranteed__c = '75';
		ctx.opportunity.Seller_Contract_ID__c = sellerContract.Id;
		ctx.insertOpportunity();

		// Store the contract expiration date so we can ensure it doesn't change.
		DateTime originalContractExpiration = [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c;

		// Update the opportunity.
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL;
		ctx.opportunity.Days_Guaranteed__c = '50';
		ctx.opportunity.Entered_Stage_Prepare_Car_For_Sale__c = DateTime.now().addDays(-4);
		update ctx.opportunity;

		// Ensure that the expiration date is not updated (because it hasn't been seven days since PREPARE).
		System.assertEquals(originalContractExpiration, [SELECT Expires_On__c FROM Shift_Contract__c WHERE Id = :sellerContract.Id].Expires_On__c);
	}

	@IsTest
	static void testValidSellerUpsidePercentage() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_SINGLE_PRICE_0_UPSIDE;
		ctx.opportunity.Seller_Upside_Percentage__c = 0;
		insert ctx.opportunity;

		Test.startTest();
		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_SPECIFIC_CAR_SEARCH;
		update ctx.opportunity;

		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT;
		ctx.opportunity.Flat_Fee__c = 100;
		ctx.opportunity.Seller_Upside_Percentage__c = 100;
		update ctx.opportunity;

		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT;
		ctx.opportunity.Flat_Fee__c = null;
		ctx.opportunity.Flat_Fee_Percent__c = 100;
		update ctx.opportunity;
		Test.stopTest();
	}

	@IsTest
	static void testFailureOnInvalidSellerUpsidePercentage() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_SINGLE_PRICE_0_UPSIDE;
		ctx.opportunity.Seller_Upside_Percentage__c = 50;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Seller upside percentage must be 0 for pricing strategy: ' + ShiftConstants.PRICING_STRATEGY_SINGLE_PRICE_0_UPSIDE);

		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_SPECIFIC_CAR_SEARCH;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Seller upside percentage must be 0 for pricing strategy: ' + ShiftConstants.PRICING_STRATEGY_SPECIFIC_CAR_SEARCH);

		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Seller upside percentage must be 100 for pricing strategy: ' + ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT);

		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Seller upside percentage must be 100 for pricing strategy: ' + ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT);
	}

	@IsTest
	static void testFlatFeeDollarAmountValidation() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT;
		ctx.opportunity.Seller_Upside_Percentage__c = 100;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Flat Fee field must be populated for pricing strategy: ' + ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT);

		ctx.opportunity.Flat_Fee__c = 100;
		ctx.opportunity.Flat_Fee_Percent__c = 100;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Flat Fee - Percent field must not be populated for pricing strategy: ' + ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT);

		ctx.opportunity.Flat_Fee_Percent__c = null;
		insert ctx.opportunity;
	}

	@IsTest
	static void testFlatFeePercentValidation() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		ctx.opportunity.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT;
		ctx.opportunity.Seller_Upside_Percentage__c = 100;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Flat Fee - Percent field must be populated for pricing strategy: ' + ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT);

		ctx.opportunity.Flat_Fee__c = 100;
		ctx.opportunity.Flat_Fee_Percent__c = 100;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Flat Fee field must not be populated for pricing strategy: ' + ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT);

		ctx.opportunity.Flat_Fee__c = null;
		insert ctx.opportunity;
	}

	@IsTest
	static void testSpecificCarSearchWithFee() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.prepareSellerTestContext();
		sctx.opportunity.Specific_Car_Search__c = true;
		insert sctx.opportunity;

		ShiftTesting.BuyerTestContext bctx = ShiftTesting.prepareBuyerTestContext();
		bctx.opportunity.Specific_Car_Search_Fee__c = 100;
		insert bctx.opportunity;

		Test.startTest();
		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
		bctx.setAndUpdateOpenPurchase(vo);

		sctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_HANDOVER;
		update sctx.opportunity;
		Test.stopTest();
	}

	@IsTest
	static void testErrorSpecificCarSearchWithNoFee() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.prepareSellerTestContext();
		sctx.opportunity.Specific_Car_Search__c = true;
		insert sctx.opportunity;

		ShiftTesting.BuyerTestContext bctx = ShiftTesting.prepareBuyerTestContext();
		insert bctx.opportunity;

		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
		bctx.setOpenPurchase(vo);
		ShiftTesting.expectUpdateExceptionContains(vo, 'Specific Car Search is true but the buyer opportunity does not have a Specific Car Search Fee');
	}

	@IsTest
	static void testErrorNoSpecificCarSearchButFeePresent() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.prepareSellerTestContext();
		insert sctx.opportunity;

		ShiftTesting.BuyerTestContext bctx = ShiftTesting.prepareBuyerTestContext();
		bctx.opportunity.Specific_Car_Search_Fee__c = 100;
		insert bctx.opportunity;

		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
		bctx.setOpenPurchase(vo);
		ShiftTesting.expectUpdateExceptionContains(vo, 'Specific Car Search is false but the buyer opportunity has a Specific Car Search Fee');
	}

	@IsTest
	static void testStageChangeToHandover() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_HANDOVER;
		ShiftTesting.expectInsertExceptionContains(ctx.opportunity, 'Cannot change to stage ' + ShiftConstants.SELLER_OPPORTUNITY_STAGE_HANDOVER + ': vehicle does not have a completed sale');

		ShiftTesting.prepareVehicleForHandover(ctx.vehicle);
		insert ctx.opportunity;
	}

	@IsTest
	static void testValidationOnStageChangeFromHandoverToSellCar() {
		Test.startTest();
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();
		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
		bctx.setAndUpdateOpenPurchase(vo);
		Test.stopTest();

		ShiftTesting.expectOpportunityStage(sctx.opportunity.Id, ShiftConstants.SELLER_OPPORTUNITY_STAGE_HANDOVER);
		sctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL;
		ShiftTesting.expectUpdateExceptionContains(sctx.opportunity, 'Cannot change from stage ' + ShiftConstants.SELLER_OPPORTUNITY_STAGE_HANDOVER + ' to stage ' + ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL + ': vehicle has not been returned');

		bctx.setReturnedPurchase(vo);
		update vo;
		update sctx.opportunity;
	}

	@IsTest
	static void testValidationOnStageChangeFromSoldToSellCar() {
		Test.startTest();
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();
		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
		bctx.setAndUpdateOpenPurchase(vo);
		Test.stopTest();

		sctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SOLD;
		update sctx.opportunity;

		sctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL;
		ShiftTesting.expectUpdateExceptionContains(sctx.opportunity, 'Cannot change from stage ' + ShiftConstants.SELLER_OPPORTUNITY_STAGE_SOLD + ' to stage ' + ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL + ': vehicle has not been returned');

		bctx.setReturnedPurchase(vo);
		update vo;
		update sctx.opportunity;
	}

	@IsTest
	static void testStandardStageChangeToSellCar() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();
		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		Test.startTest();
		insert vo;
		bctx.setAndUpdateOpenPurchase(vo);
		sctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		sctx.signSellerContract();
		update sctx.opportunity;

		sctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL;
		update sctx.opportunity;
		Test.stopTest();
	}

	@IsTest
	static void testExistingVehicleParkingLot() {
		Test.startTest();
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();
		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
		bctx.setAndUpdateOpenPurchase(vo);

		Parking_Lot__c parkingLot = ShiftTesting.createRandomParkingLot(ShiftTesting.getTestRegionId(), false);
		insert parkingLot;
		sctx.vehicle.Parking_Lot_ID__c = parkingLot.Id;
		update sctx.vehicle;
		Test.stopTest();

		sctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE;
		sctx.signSellerContract();
		update sctx.opportunity;
		System.assertEquals(ShiftTesting.PARKING_LOT_NAME_TESTING, [SELECT Parking_Lot_ID__r.Name FROM Vehicle__c WHERE Id = :sctx.vehicle.Id].Parking_Lot_ID__r.Name);
	}

	@IsTest
	static void testUpdateISRInboundAfterInsertAndUpdate() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Opportunity opportunity = ctx.opportunity;
		User user = ShiftTesting.createISRInboundUser();
		User userNew = ShiftTesting.createISRInboundUser();

		insert new List<User> {user, userNew};

		opportunity.OwnerId = user.Id;

		Test.startTest();
		insert opportunity;

		opportunity = [SELECT Id, Inside_Sales_Representative__c FROM Opportunity WHERE Id = :opportunity.Id];

		System.assertEquals(opportunity.Inside_Sales_Representative__c, user.Id);
		Test.stopTest();

		opportunity.OwnerId = userNew.Id;

		update opportunity;

		opportunity = [SELECT Id, Inside_Sales_Representative__c FROM Opportunity WHERE Id = :opportunity.Id];

		System.assertEquals(opportunity.Inside_Sales_Representative__c, userNew.Id);
	}

	@IsTest
	static void testUpdateISROutboundAfterInsertAndUpdate() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Opportunity opportunity = ctx.opportunity;
		User user = ShiftTesting.createISROutboundUser();
		User userNew = ShiftTesting.createISROutboundUser();

		insert new List<User> {user, userNew};

		opportunity.OwnerId = user.Id;

		Test.startTest();
		insert opportunity;

		opportunity = [SELECT Id, Inside_Sales_Representative__c FROM Opportunity WHERE Id = :opportunity.Id];

		System.assertEquals(opportunity.Inside_Sales_Representative__c, user.Id);
		Test.stopTest();

		opportunity.OwnerId = userNew.Id;

		update opportunity;

		opportunity = [SELECT Id, Inside_Sales_Representative__c FROM Opportunity WHERE Id = :opportunity.Id];

		System.assertEquals(opportunity.Inside_Sales_Representative__c, userNew.Id);
	}

	@IsTest
	static void testBuyer() {
		insertOpportunity(false);
		System.assertEquals('John Doe', [SELECT Name FROM Opportunity LIMIT 1].Name);
	}

	@IsTest
	static void testAutoAdvanceStageWithSourceDriveshift() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.prepareBuyerTestContext();
		ctx.opportunity.LeadSource = ShiftConstants.LEAD_SOURCE_DRIVESHIFT;
		ctx.opportunity.StageName = ShiftConstants.BUYER_OPPORTUNITY_STAGE_LEADS;
		ctx.insertOpportunity();

		ShiftTesting.expectOpportunityStage(ctx.opportunity.Id, ShiftConstants.BUYER_OPPORTUNITY_STAGE_QUALIFIED);
	}

	@IsTest
	static void testNoAutoAdvanceStageWithSourceNonDriveshift() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.prepareBuyerTestContext();
		ctx.opportunity.LeadSource = ShiftConstants.LEAD_SOURCE_WORD_OF_MOUTH;
		ctx.opportunity.StageName = ShiftConstants.BUYER_OPPORTUNITY_STAGE_LEADS;
		ctx.insertOpportunity();

		ShiftTesting.expectOpportunityStage(ctx.opportunity.Id, ShiftConstants.BUYER_OPPORTUNITY_STAGE_LEADS);
	}

	@IsTest
	static void testNoAutoAdvanceStageWithStageNonLeads() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.prepareBuyerTestContext();
		ctx.opportunity.LeadSource = ShiftConstants.LEAD_SOURCE_DRIVESHIFT;
		ctx.opportunity.StageName = ShiftConstants.BUYER_OPPORTUNITY_STAGE_SOLD;
		ctx.insertOpportunity();

		ShiftTesting.expectOpportunityStage(ctx.opportunity.Id, ShiftConstants.BUYER_OPPORTUNITY_STAGE_SOLD);
	}
}