objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Shift Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>List_Price__c</fullName>
        <formula>Vehicle_ID__r.List_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>TEXT(Vehicle_ID__r.Make__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <formula>Vehicle_ID__r.Mileage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The region in which the seller&apos;s vehicle was acquired</description>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Vehicle_ID__r.Display_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Parking_Lot__c.object
<CustomObject>
    <description>Represents a parking lot location</description>
    <fields>
        <fullName>Region_ID__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Parking Lots</relationshipLabel>
        <relationshipName>Parking_Lots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Parking Lot</label>
    <nameField>
        <label>Parking Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parking Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Represents a region for vehicle activity (acquire, sell, etc).</description>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Body_Style__c</fullName>
        <label>Body Style</label>
        <picklist>
            <picklistValues>
                <fullName>Convertible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sedan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Van</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wagon</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Listing_Region_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Listing Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing_Region_Name__c</fullName>
        <formula>Listing_Region_ID__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Listing Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <picklist>
            <picklistValues>
                <fullName>Acura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alfa Romeo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aston Martin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bentley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bugatti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadillac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chevrolet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chrysler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daewoo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dodge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferrari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fisker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hummer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyundai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infiniti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Isuzu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaguar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jeep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lamborghini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyota</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShiftCxCarSearchControllerTest.cls
@IsTest
class ShiftCxCarSearchControllerTest {
	@TestSetup static void setup() { ShiftTesting.setup(); }

	static List<Id> insertTestVehicles() {
		Region__c region1 = new Region__c(
			Name = 'Testing Region One',
			Shift_Key__c = 'testing/ShiftCxCarSearchControllerTest/region1',
			Timezone__c = 'America/Los_Angeles'
		);
		Region__c region2 = new Region__c(
			Name = 'Testing Region Two',
			Shift_Key__c = 'testing/ShiftCxCarSearchControllerTest/region2',
			Timezone__c = 'America/Toronto'
		);
		insert new List<Region__c>{region1, region2};
		insert new List<Parking_Lot__c>{
			ShiftTesting.createRandomParkingLot(region1.Id, true),
			ShiftTesting.createRandomParkingLot(region2.Id, true)
		};
		List<Id> out = new List<Id>();

		Account acct = new Account(Name = 'account name');
		insert acct;

		Vehicle__c bmw = new Vehicle__c(
			Year__c = 2010,
			Make__c = 'BMW',
			Model__c = '328i',
			Body_Style__c = 'Sedan',
			Mileage__c = 52000,
			List_Price__c = 20,
			Listing_Region_ID__c = region1.ID
		);
		insert bmw;
		out.add(bmw.Id);

		Vehicle__c toyota = new Vehicle__c(
			Year__c = 2012,
			Make__c = 'Toyota',
			Model__c = '4Runner',
			Body_Style__c = 'SUV',
			Mileage__c = 50000,
			List_Price__c = 30,
			Listing_Region_ID__c = region2.ID
		);
		insert toyota;
		out.add(toyota.Id);

		RecordType recordTypeSeller = [SELECT Id FROM RecordType WHERE DeveloperName = 'Seller' AND SObjectType = 'Opportunity'];
		insert new Opportunity(
			CloseDate = Date.parse('01/02/3000'),
			StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE,
			RecordTypeId = recordTypeSeller.Id,
			AccountId = acct.Id,
			Region_ID__r = new Region__c(Shift_Key__c = ShiftTesting.REGION_SHIFT_KEY_TESTING),
			Vehicle_ID__c = bmw.Id
		);
		insert new Opportunity(
			CloseDate = Date.parse('01/02/3000'),
			StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE,
			RecordTypeId = recordTypeSeller.Id,
			AccountId = acct.Id,
			Region_ID__r = new Region__c(Shift_Key__c = ShiftTesting.REGION_SHIFT_KEY_TESTING),
			Vehicle_ID__c = toyota.Id
		);

		return out;
	}

	static List<Vehicle__c> searchCarsInPrepare(String query, Integer limt) {
		Set<String> selectedStages = new Set<String>();
		selectedStages.add(ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE);
		return ShiftCxCarSearchController.doSearch(selectedStages, query, limt).carsInStage.get(ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE);
	}

	@IsTest
	static void testSearch() {
		List<Id> vehicleIds = insertTestVehicles();

		System.debug('opportunities: ' + [SELECT Id, Name, StageName, RecordType.Id, RecordType.DeveloperName, Vehicle_ID__r.Name FROM Opportunity]);
		System.debug('opportunity 0 record type developer name: ' + [SELECT Id, Name, RecordType.Id, RecordType.DeveloperName FROM Opportunity][0].RecordType.DeveloperName);
		System.debug('record types: ' + [SELECT Id, DeveloperName FROM RecordType]);

		// some sanity checks -- these test our test fixture, not the class under test
		System.assertEquals(2, vehicleIds.size());
		System.assertEquals(2, [SELECT Id FROM Opportunity].size());
		System.assertEquals(2, [SELECT Id FROM Opportunity WHERE RecordType.DeveloperName = 'Seller'].size());
		System.assertEquals(2, [SELECT Id FROM Opportunity WHERE StageName = :ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE].size());

		System.assertEquals(2, searchCarsInPrepare('', 100).size());

		System.assertEquals(2, searchCarsInPrepare('201', 100).size());

		// Test limit
		System.assertEquals(1, searchCarsInPrepare('201', 1).size());
		System.assertEquals(0, searchCarsInPrepare('201', 0).size());

		{
			List<Vehicle__c> results = searchCarsInPrepare('2012 To', 100);
			System.assertEquals(1, results.size());
			System.assertEquals('2012 Toyota 4Runner', results[0].Name);
			System.assertEquals('SUV', results[0].Body_Style__c);
			System.assertEquals(50000, results[0].Mileage__c);
			System.assertEquals(30, results[0].List_Price__c);
			System.assertEquals('Testing Region Two', results[0].Listing_Region_Name__c);
		}

		{
			List<Vehicle__c> results = searchCarsInPrepare(vehicleIds[1], 100);
			System.assertEquals(1, results.size());
			System.assertEquals('2012 Toyota 4Runner', results[0].Name);
		}

		{
			List<Vehicle__c> results = searchCarsInPrepare('BMW Sedan', 100);
			System.assertEquals(1, results.size());
			System.assertEquals('2010 BMW 328i', results[0].Name);
		}

		{
			List<Vehicle__c> results = searchCarsInPrepare('BMW Convertible', 100);
			System.assertEquals(0, results.size());
		}

		{
			List<Vehicle__c> results = searchCarsInPrepare('region2', 100);
			System.assertEquals(1, results.size());
			System.assertEquals('2012 Toyota 4Runner', results[0].Name);
		}

		{
			List<Vehicle__c> results = searchCarsInPrepare('Region One', 100);
			System.assertEquals(1, results.size());
			System.assertEquals('2010 BMW 328i', results[0].Name);
		}
	}

}