objects/Applied_Incentive__c.object
<CustomObject>
    <description>A junction object connecting Incentives with Opportunities.</description>
    <fields>
        <fullName>Incentive_ID__c</fullName>
        <label>Incentive</label>
        <referenceTo>Incentive__c</referenceTo>
        <relationshipLabel>Applied Incentives</relationshipLabel>
        <relationshipName>Applied_Incentives</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Applied Incentive</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Applied Incentive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applied Incentives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Incentive_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This contact&apos;s incentive. Contacts with the same e-mail address will share incentives.</description>
        <label>Incentive</label>
        <referenceTo>Incentive__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incentive_Token__c</fullName>
        <formula>Incentive_ID__r.Token__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Incentive Token</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Incentive__c.object
<CustomObject>
    <description>Represents a code that forms a bridge between customers or business partners and Incentive Programs.</description>
    <fields>
        <fullName>Incentive_Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The incentive program that this token is tied to.</description>
        <label>Incentive Program</label>
        <referenceTo>Incentive_Program__c</referenceTo>
        <relationshipLabel>Incentives</relationshipLabel>
        <relationshipName>Incentive_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>The string representation of this token.</description>
        <externalId>true</externalId>
        <label>Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Visits__c</fullName>
        <description>How many times someone has visited this Incentive&apos;s unique link.</description>
        <label>Visits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Incentive_Program__c.object
<CustomObject>
    <fields>
        <fullName>Payout_Method__c</fullName>
        <label>Payout Method</label>
        <picklist>
            <picklistValues>
                <fullName>Amazon Gift Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instant Rebate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payout__c</fullName>
        <label>Payout</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Referrer_Payout_Method__c</fullName>
        <label>Referrer Payout Method</label>
        <picklist>
            <picklistValues>
                <fullName>Amazon Gift Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instant Rebate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referrer_Payout__c</fullName>
        <label>Referrer Payout</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Incentive Program</label>
    <nameField>
        <label>Incentive Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Incentive_Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Incentive Program</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 3) OR (2 AND 4)</booleanFilter>
            <errorMessage>Incentive program can&apos;t be used with this type of Opportunity.</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <filterItems>
                <field>Incentive_Program__c.Is_Seller_Promotion__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Incentive_Program__c.Is_Buyer_Promotion__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Incentive_Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Cost__c</fullName>
        <label>Marketing Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Buyer</fullName>
        <active>true</active>
        <businessProcess>Buyer</businessProcess>
        <label>Buyer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vehicle_Order__c.object
<CustomObject>
    <description>Orders represent the process of a Buyer purchasing a Vehicle. Note that we don&apos;t name this object simple &quot;Order&quot; so as to avoid confusion with the standard salesforce Order object. We may one day decide to use that object instead, but not until we understand more about whether it fits with our model.</description>
    <fields>
        <fullName>Buyer_Opportunity_ID__c</fullName>
        <label>Buyer Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShiftIncentivesTest.cls
@IsTest
public class ShiftIncentivesTest {
  @IsTest static void testValidateIncentives() {
    Incentive_Program__c program1 = ShiftTesting.createIncentiveProgram();
    Incentive_Program__c program2 = ShiftTesting.createIncentiveProgram();
    insert new List<Incentive_Program__c>{program1, program2};

    Incentive__c incentive = ShiftTesting.createIncentive('token', program1.Id);
    insert incentive;

    incentive.Token__c = 'newToken';
    ShiftTesting.expectUpdateExceptionContains(incentive, String.escapeSingleQuotes('Attempt to change Token__c from token to newToken'));
    incentive.Token__c = 'token';

    incentive.Incentive_Program_ID__c = program2.Id;
    ShiftTesting.expectUpdateExceptionContains(incentive, 'Attempt to change Incentive_Program_ID__c from ' + program1.Id + ' to ' + program2.Id);
    incentive.Incentive_Program_ID__c = program1.Id;

    // Test succcessful visits increment.
    incentive.Visits__c = 1;
    update incentive;
    incentive.Visits__c = 2;
    update incentive;

    incentive.Visits__c = 1;
    ShiftTesting.expectUpdateExceptionContains(incentive, 'Attempt to decrement number of incentive visits from 2 to 1');
  }

  static Task getTaskOnContact(Id id) {
    return [SELECT Id, Subject, Description, Team__c FROM Task WHERE WhoId = :id LIMIT 1];
  }

  static Contact getContactForOpportunity(Id opportunityId) {
    return [SELECT Id, Email, FirstName, Incentive_Token__c FROM Contact WHERE AccountId IN (SELECT AccountId FROM Opportunity WHERE Id = :opportunityId) LIMIT 1];
  }

  static Contact getContactById(Id contactId) {
    return [SELECT Id, Email, FirstName, Incentive_Token__c FROM Contact WHERE Id = :contactId];
  }

  @IsTest static void testProcessIncentives() {
    ShiftTesting.setup();
    ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
    ctx.opportunity.Marketing_Cost__c = 100;
    ctx.insertOpportunity();
    Test.startTest();
    Incentive_Program__c program = ShiftTesting.createIncentiveProgram();
    insert program;
    Contact referrer1 = ShiftTesting.createContactWithRandomEmail();
    Contact referrer2 = ShiftTesting.createContactWithRandomEmail();
    insert new List<Contact>{referrer1, referrer2};
    
    Incentive__c sellerIncentive = ShiftTesting.createIncentive('sellerToken', program.Id, referrer1.Email);
    Incentive__c buyerIncentive = ShiftTesting.createIncentive('buyerToken', program.Id, referrer2.Email);
    insert new List<Incentive__c>{sellerIncentive, buyerIncentive};

    referrer1.Incentive_ID__c = sellerIncentive.Id;
    referrer2.Incentive_ID__c = buyerIncentive.Id;
    update new List<Contact>{referrer1, referrer2};

    ShiftTesting.prepareVehicleForHandover(ctx.vehicle);
    Vehicle_Order__c vo = [SELECT Id, Buyer_Opportunity_ID__c FROM Vehicle_Order__c WHERE Vehicle_ID__c = :ctx.vehicle.Id];
    Applied_Incentive__c appliedIncentive1 = ShiftTesting.createAppliedIncentive(ctx.opportunity.Id, sellerIncentive.Id);
    Applied_Incentive__c appliedIncentive2 = ShiftTesting.createAppliedIncentive(vo.Buyer_Opportunity_ID__c, buyerIncentive.Id);
    insert new List<Applied_Incentive__c>{appliedIncentive1, appliedIncentive2};

    ctx.opportunity.StageName = ShiftConstants.SELLER_OPPORTUNITY_STAGE_SOLD;
    update ctx.opportunity;
    Test.stopTest();

    Contact seller = getContactForOpportunity(ctx.opportunity.Id);
    Contact buyer = getContactForOpportunity(vo.Buyer_Opportunity_ID__c);
    referrer1 = getContactById(referrer1.Id);
    referrer2 = getContactById(referrer2.Id);
    ShiftTesting.TaskExpector sellerReferrerTask = new ShiftTesting.TaskExpector(getTaskOnContact(referrer1.Id));
    ShiftTesting.TaskExpector sellerRefereeTask = new ShiftTesting.TaskExpector(getTaskOnContact(seller.Id));
    ShiftTesting.TaskExpector buyerReferrerTask = new ShiftTesting.TaskExpector(getTaskOnContact(referrer2.Id));
    ShiftTesting.TaskExpector buyerRefereeTask = new ShiftTesting.TaskExpector(getTaskOnContact(buyer.Id));

    List<ShiftTesting.TaskExpector> expectors = new List<ShiftTesting.TaskExpector>{sellerReferrerTask, sellerRefereeTask, buyerReferrerTask, buyerRefereeTask};

    for (ShiftTesting.TaskExpector e : expectors) {
        e.expectTeam(ShiftConstants.TASK_TEAM_USER_HAPPINESS);
    }

    sellerReferrerTask.expectSubject('Pay referrer bonus');
    sellerRefereeTask.expectSubject('Pay referee bonus');
    buyerReferrerTask.expectSubject('Pay referrer bonus');
    buyerRefereeTask.expectSubject('Pay referee bonus');

    String sellerReferrerDescription = 'Pay $' + program.Referrer_Payout__c + ' to ' + referrer1.Email +
        '\n\nPayout Method: ' + program.Referrer_Payout_Method__c +
        '\nE-mail type: Referrer' +
        '\nReferee name: ' + seller.FirstName +
        '\nSale type: seller' +
        '\nIncentive token: ' + referrer1.Incentive_Token__c;
    String buyerReferrerDescription = 'Pay $' + program.Referrer_Payout__c + ' to ' + referrer2.Email +
        '\n\nPayout Method: ' + program.Referrer_Payout_Method__c +
        '\nE-mail type: Referrer' +
        '\nReferee name: ' + buyer.FirstName +
        '\nSale type: buyer' +
        '\nIncentive token: ' + referrer2.Incentive_Token__c;
    String sellerRefereeDescription = 'Pay $' + program.Payout__c + ' to ' + seller.Email +
        '\n\nPayout Method: ' + program.Payout_Method__c +
        '\nE-mail type: Was referred' +
        '\nReferrer name: ' + referrer1.FirstName +
        '\nSale type: seller' +
        '\nIncentive token: ' + seller.Incentive_Token__c;
    String buyerRefereeDescription = 'Pay $' + program.Payout__c + ' to ' + buyer.Email +
        '\n\nPayout Method: ' + program.Payout_Method__c +
        '\nE-mail type: Was referred' +
        '\nReferrer name: ' + referrer2.FirstName +
        '\nSale type: buyer' +
        '\nIncentive token: ' + buyer.Incentive_Token__c;

    sellerReferrerTask.expectDescription(sellerReferrerDescription);
    sellerRefereeTask.expectDescription(sellerRefereeDescription);
    buyerReferrerTask.expectDescription(buyerReferrerDescription);
    buyerRefereeTask.expectDescription(buyerRefereeDescription);

    Opportunity buyerOpportunity = [SELECT Marketing_Cost__c FROM Opportunity WHERE Id = :vo.Buyer_Opportunity_ID__c];
    Opportunity sellerOpportunity = [SELECT Marketing_Cost__c FROM Opportunity WHERE Id = :ctx.opportunity.Id];
    System.assertEquals(200.00, buyerOpportunity.Marketing_Cost__c);
    System.assertEquals(300.00, sellerOpportunity.Marketing_Cost__c);
  }
}