objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle Order</label>
        <referenceTo>Vehicle_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Buyer</fullName>
        <active>true</active>
        <businessProcess>Buyer</businessProcess>
        <label>Buyer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Represents a region for vehicle activity (acquire, sell, etc).</description>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Listing_Region_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Listing Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle_Order__c.object
<CustomObject>
    <description>Orders represent the process of a Buyer purchasing a Vehicle. Note that we don&apos;t name this object simple &quot;Order&quot; so as to avoid confusion with the standard salesforce Order object. We may one day decide to use that object instead, but not until we understand more about whether it fits with our model.</description>
    <fields>
        <fullName>Buyer_Opportunity_ID__c</fullName>
        <label>Buyer Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Returned_Notes__c</fullName>
        <label>Returned Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BluewolfRequestContExtTest.cls
@isTest
private class BluewolfRequestContExtTest {
    
    private static Id buyerOppId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Buyer' AND SobjectType = 'Opportunity' LIMIT 1].Id;
    
    static Vehicle_Order__c setupVehicleOrder(String notes){
        BluewolfVehicleTriggerHandler.bypassTrigger = true;
        Region__c region = (Region__c) new BluewolfSObjectBuilder(Region__c.SobjectType).put(Region__c.Timezone__c, 'GMT 8').create().getRecord();
        Vehicle__c vehicle = (Vehicle__c) new BluewolfSObjectBuilder(Vehicle__c.SobjectType).put(Vehicle__c.Listing_Region_ID__c, region.Id).create().getRecord();
        Account acc = (Account) new BluewolfSObjectBuilder(Account.SobjectType).create().getRecord();
        Contact con = (Contact) new BluewolfSObjectBuilder(Contact.SobjectType).put(Contact.AccountId, acc.Id)
                                                                       .put(Contact.LastName, 'Test Name')
                                                                       .create().getRecord();
        Opportunity opp = (Opportunity) new BluewolfSObjectBuilder(Opportunity.SobjectType).put(Opportunity.AccountId, acc.Id).put(Opportunity.RecordTypeId, buyerOppId).create().getRecord(); 
        return (Vehicle_Order__c) new BluewolfSObjectBuilder(Vehicle_Order__c.SobjectType).put(Vehicle_Order__c.Buyer_Opportunity_ID__c, opp.Id)
                                                                                  .put(Vehicle_Order__c.Returned_Notes__c, notes)
                                                                                  .create().getRecord();                                                                         
    }
    
    static testMethod void testConstructor(){
        final String TEST_NOTES = 'some notes';
        BluewolfVehicleOrderTriggerHandler.bypassTrigger = true;
        Vehicle_Order__c vehicleOrder = setupVehicleOrder(TEST_NOTES);
         BluewolfVehicleOrderTriggerHandler.bypassTrigger = false;
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(vehicleOrder);
        
        Test.startTest();
            BluewolfRequestContExt ext = new BluewolfRequestContExt(stdCtrl);
        Test.stopTest();
        
        system.assertNotEquals(ext.vehicleOrder, null, 'the vehicle order should not be null');
        system.assertEquals(ext.vehicleOrder.Returned_Notes__c, TEST_NOTES, 'the notes should be equal');
    }
    
    static testMethod void testCreateNewCase(){
        final String TEST_NOTES = 'a note';
        final String TEST_TYPES = 'some type';
        BluewolfVehicleOrderTriggerHandler.bypassTrigger = true;
        Vehicle_Order__c vehicleOrder = setupVehicleOrder(TEST_NOTES);
        BluewolfVehicleOrderTriggerHandler.bypassTrigger = false;
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(vehicleOrder);
        BluewolfRequestContExt ext = new BluewolfRequestContExt(stdCtrl);
        
        Test.startTest();
            PageReference ref = ext.createNewCase(TEST_TYPES);
        Test.stopTest();
        
        system.assertNotEquals(ref, null, 'the page reference should not be null');
        system.assert(!ApexPages.hasMessages(),'the page should not show any errors');
        
        Case actual = [SELECT Vehicle_Order__c, Case_Type__c, OwnerId FROM Case LIMIT 1];
        
        system.assertNotEquals(actual, null, 'the case should not be null');
        system.assertEquals(actual.Case_Type__c, TEST_TYPES, 'the type should be set correctly');
        system.assertEquals(actual.OwnerId, BluewolfRequestContExt.ASSIGNED_USER.Id, 'the owner should be set correctly');
    }
    
    static testMethod void testCreatePickupRequest(){
        final String TEST_NOTES = 'a note';
         BluewolfVehicleOrderTriggerHandler.bypassTrigger = true;
        Vehicle_Order__c vehicleOrder = setupVehicleOrder(TEST_NOTES);
         BluewolfVehicleOrderTriggerHandler.bypassTrigger = false;
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(vehicleOrder);
        BluewolfRequestContExt ext = new BluewolfRequestContExt(stdCtrl);
        
        Test.startTest();
            PageReference ref = ext.createPickupRequest();
        Test.stopTest();
        
        system.assertNotEquals(ref, null, 'the page reference should not be null');
        system.assert(!ApexPages.hasMessages(),'the page should not show any errors');
        
        Case actual = [SELECT Vehicle_Order__c, Case_Type__c, OwnerId FROM Case LIMIT 1];
        
        system.assertNotEquals(actual, null, 'the case should not be null');
        system.assertEquals(actual.Case_Type__c, BluewolfRequestContExt.PICKUP_REQUEST_TYPE, 'the type should be set correctly');
        system.assertEquals(actual.OwnerId, BluewolfRequestContExt.ASSIGNED_USER.Id, 'the owner should be set correctly');
    }
    
    static testMethod void testCreateReturnRequest(){
        final String TEST_NOTES = 'a note';
        Vehicle_Order__c vehicleOrder = setupVehicleOrder(TEST_NOTES);
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(vehicleOrder);
        BluewolfRequestContExt ext = new BluewolfRequestContExt(stdCtrl);
        
        Test.startTest();
            PageReference ref = ext.createReturnRequest();
        Test.stopTest();
        
        system.assertNotEquals(ref, null, 'the page reference should not be null');
        system.assert(!ApexPages.hasMessages(),'the page should not show any errors');
        
        Case actual = [SELECT Vehicle_Order__c, Case_Type__c, OwnerId FROM Case LIMIT 1];
        
        system.assertNotEquals(actual, null, 'the case should not be null');
        system.assertEquals(actual.Case_Type__c, BluewolfRequestContExt.RETURN_REQUEST_TYPE, 'the type should be set correctly');
        system.assertEquals(actual.OwnerId, BluewolfRequestContExt.ASSIGNED_USER.Id, 'the owner should be set correctly');
    }
}