objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Delivery_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Notes__c</fullName>
        <label>Delivery Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Delivery_Scheduled_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Scheduled By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Scheduled_For__c</fullName>
        <label>Delivery Scheduled For</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delivery__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery</label>
        <referenceTo>Delivery__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Delivery Location</description>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle Interest</label>
        <referenceTo>Vehicle_Interest__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Delivery__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Deliveries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Is there anything else that the DOS needs to do? (i.e. Does anyone need to sign the 262 besides the buyer?)</inlineHelpText>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Original_Time_Requested__c</fullName>
        <label>Original Time Requested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scheduled By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_For__c</fullName>
        <label>Scheduled For</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vehicle_Interest__c</fullName>
        <label>Vehicle Interest</label>
        <referenceTo>Vehicle_Interest__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Buyer_Opportunity_ID__c</fullName>
        <label>Buyer Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a Buyer Opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicle Interests</relationshipLabel>
        <relationshipName>Vehicle_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Interests</relationshipLabel>
        <relationshipName>Vehicle_Interests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Interest</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShiftDeliveryTest.cls
@IsTest
class ShiftDeliveryTest {
	@TestSetup
	static void setup() { ShiftTesting.setup(); }

	static final String TEST_LOCATION = 'TestLocation';
	static final String TEST_NOTES = 'TestNotes';

	//Class to store Delivery and related Objects so that we can refer to
	//fields in related Objects without any additional query.
	//We need to verify fields on the related Opportunity.
	class TestDeliveryContext {
		Delivery__c delivery;
		Vehicle_Interest__c vehicleInterest;
		Opportunity buyerOpportunity;
		Vehicle__c vehicle;

		public TestDeliveryContext(Delivery__c d, Vehicle_Interest__c vi, Opportunity bo, Vehicle__c veh) {
			delivery = d;
			vehicleInterest = vi;
			buyerOpportunity = bo;
			vehicle = veh;
		}
	}

	static TestDeliveryContext createTestDelivery() {
		Account account = ShiftTesting.createAccount();
		insert account;
		Opportunity buyerOpportunity = ShiftTesting.createBuyerOpportunity();
		buyerOpportunity.AccountId = account.Id;
		insert buyerOpportunity;
		Vehicle__c vehicle = ShiftTesting.createVehicle();
		insert vehicle;
		Vehicle_Interest__c vehicleInterest = new Vehicle_Interest__c(
				Buyer_Opportunity_ID__c = buyerOpportunity.Id,
				Vehicle_ID__c = vehicle.Id
		);
		insert vehicleInterest;
		User testUser1 = ShiftTesting.insertTestUser();
		User testUser2 = ShiftTesting.insertTestUser();
		Delivery__c delivery = new Delivery__c(
			Delivery_By__c = testUser1.Id,
			Vehicle_Interest__c = vehicleInterest.id,
			Notes__c = TEST_NOTES,
			Scheduled_By__c = testUser2.Id,
			Scheduled_For__c = DateTime.now().addDays(2)
		);

		return new TestDeliveryContext(delivery, vehicleInterest, buyerOpportunity, vehicle);
	}

	static void assertCaseValues(TestDeliveryContext testDeliveryCtx) {
		Delivery__c delivery = testDeliveryCtx.delivery;
		Case newCase = [
				SELECT Case_Type__c, Delivery_By__c, Delivery_Notes__c, Delivery_Scheduled_By__c,
						Delivery_Scheduled_For__c, Location__c, Opportunity_ID__c, OwnerId,
						Status, Vehicle_Interest__c
				FROM Case
				WHERE Delivery__c =:delivery.Id
		];

		System.assertEquals(ShiftConstants.CASE_TYPE_DELIVERY_REQUEST, newCase.Case_Type__c);
		System.assertEquals(delivery.Delivery_By__c, newCase.Delivery_By__c);
		System.assertEquals(delivery.Notes__c, newCase.Delivery_Notes__c);
		System.assertEquals(delivery.Scheduled_For__c, newCase.Delivery_Scheduled_For__c);
		System.assertEquals(delivery.Location__c, newCase.Location__c);
		System.assertEquals(ShiftUsers.unownedUserId(), newCase.OwnerId);
		System.assertEquals(ShiftConstants.CASE_STATUS_NEW, newCase.Status);
		System.assertEquals(delivery.Vehicle_Interest__c, newCase.Vehicle_Interest__c);
		System.assertEquals(testDeliveryCtx.buyerOpportunity.Id, newCase.Opportunity_ID__c);
	}

	@IsTest
	static void testAutoConversionWithAllFields() {
		TestDeliveryContext testDeliveryCtx = createTestDelivery();
		Delivery__c delivery = testDeliveryCtx.delivery;
		delivery.Location__c = TEST_LOCATION;
		delivery.Original_Time_Requested__c = DateTime.now();

		Test.startTest();
		insert delivery;
		assertCaseValues(testDeliveryCtx);
		Test.stopTest();
	}

	@IsTest
	static void testAutoConversionMissingLocation() {
		TestDeliveryContext testDeliveryCtx = createTestDelivery();
		Delivery__c delivery = testDeliveryCtx.delivery;
		delivery.Original_Time_Requested__c = DateTime.now();

		Test.startTest();
		insert delivery;
		assertCaseValues(testDeliveryCtx);
		Test.stopTest();
	}

	@IsTest
	static void testAutoConversionMissingRequestTime() {
		TestDeliveryContext testDeliveryCtx = createTestDelivery();
		Delivery__c delivery = testDeliveryCtx.delivery;
		delivery.Location__c = TEST_LOCATION;

		Test.startTest();
		insert delivery;
		assertCaseValues(testDeliveryCtx);
		Test.stopTest();
	}

}