objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Experience_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Experience Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ShiftCases.cls
public class ShiftCases {
	static final Set<String> CASE_TYPES_TO_SET_CUSTOMER_SERVICE_REP_FOR = new Set<String>{
		ShiftConstants.CASE_TYPE_SHIFT_TEST_DRIVE_REQUEST,
		ShiftConstants.CASE_TYPE_SHIFT_TEST_DRIVE_REQUEST_REJECTED,
		ShiftConstants.CASE_TYPE_SHIFT_VEHICLE_QUESTION,
		ShiftConstants.CASE_TYPE_THIRD_PARTY_LISTING_SITE_VEHICLE_QUESTION
	};

	static void handleOwnerChanges(Map<Id, Case> oldMap, List<Case> newList) {
		Set<Id> opportunityIds = new Set<Id>();
		Map<Id, Case> filteredCases = new Map<Id, Case>();
		Id unownedUserId = ShiftUsers.unownedUserId();

		for (Case c : newList) {
			if (c.Opportunity_ID__c != null && CASE_TYPES_TO_SET_CUSTOMER_SERVICE_REP_FOR.contains(c.Case_Type__c) && c.OwnerId != unownedUserId) {
				opportunityIds.add(c.Opportunity_ID__c);
				filteredCases.put(c.Id, c);
			}
		}
		List<Id> ids = new List<Id>(opportunityIds);
		Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>([
			SELECT Id 
			FROM Opportunity
			WHERE Customer_Experience_Representative__c = null 
			AND RecordTypeId = :ShiftOpportunities.getBuyerRecordTypeId()
			AND Id in :ids
		]);

		List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();	
		for (Id caseId : filteredCases.keySet()) {
			Case c = filteredCases.get(caseId);
			Opportunity o = opportunityMap.get(c.Opportunity_ID__c);
			Case oldCase = oldMap.get(caseId);

			if (o != null && (oldCase == null || oldCase.OwnerId == unownedUserId)) {
				opportunitiesToUpdate.add(new Opportunity(
					Id = o.Id,
					Customer_Experience_Representative__c = c.OwnerId
				));			
			}
		}
		update opportunitiesToUpdate;
	}

	public static void afterInsert(List<Case> newList) {
		handleOwnerChanges(new Map<Id, Case>(), newList);
	}

	public static void afterUpdate(Map<Id, Case> oldMap, List<Case> newList) {
		handleOwnerChanges(oldMap, newList);
	}
}