objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/CaseTypePriority__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>CaseType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>CaseTypePriority</label>
</CustomObject>

objects/Evaluation__c.object
<CustomObject>
    <description>Represents an evaluation of a seller vehicle.</description>
    <fields>
        <fullName>Canceled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Canceled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluated_At__c</fullName>
        <label>Evaluated At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <label>Seller Opportunity ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a Seller Opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BluewolfEvaluationService.cls
public with sharing class BluewolfEvaluationService {
    @TestVisible
    private static List<CaseTypePriority__c> priorityMap {
        get{
            if(priorityMap == null){
                priorityMap = CaseTypePriority__c.getAll().values();
            }
            return priorityMap;
        }
        private set;
    } 
    
    @TestVisible
    private final static String CASE_TYPE = 'Open Evaluation';
    private static Select.Filter notCanceled(){
        return Select.Field.isEqual(Evaluation__c.Canceled__c, false);
    }
    
    private static Select.Filter availableTime(){
        return Select.Field.greaterThan(Evaluation__c.Evaluated_At__c, Datetime.now());
    }
    
    
    private static Select.Filter canceledChanged(){
        return Select.Field.hasChanged(Evaluation__c.Canceled__c);
    }
    
    private static Select.Filter timeChanged(){
        return Select.Field.hasChanged(Evaluation__c.Evaluated_At__c);
    }
    
    public static void afterInsert(List<Evaluation__c> records){
        
        List<Evaluation__c> filteredRecords = notCanceled().andx(availableTime()).filter(records);
        
        Map<Id, List<Case>> oppIdToCaseMap = getOppToCaseMap(filteredRecords);
        
        upsertCases(oppIdToCaseMap, filteredRecords);
    } 
    
    public static void afterUpdate(List<Evaluation__c> records, Map<Id, Evaluation__c> oldMap){
        List<Evaluation__c> filteredRecords = canceledChanged().orx(timeChanged()).andx(notCanceled().andx(availableTime())).filter(records, oldMap);
        
        Map<Id, List<Case>> oppIdToCaseMap = getOppToCaseMap(filteredRecords);
        
        upsertCases(oppIdToCaseMap, filteredRecords);
    }
    private static void upsertCases(Map<Id, List<Case>> oppIdToCaseMap, List<Evaluation__c> filteredRecords){
        BluewolfDMLBox insertDMLBox = new BluewolfDMLBox();
        BluewolfDMLBox updateDMLBox = new BluewolfDMLBox();
        
        List<Case> updateCases = new List<Case>();
        List<Case> insertCases = new List<Case>();
        for(Id oppId : oppIdToCaseMap.keySet()){
            List<Case> cases = oppIdToCaseMap.get(oppId);
            if(cases != null && !cases.isEmpty()){
               for(Case aCase: cases){
                   aCase.Case_Type__c = CASE_TYPE;
               }
               updateCases.addAll(cases);
            }
            else{
                insertCases.add(new Case(Opportunity_ID__c = oppId, Case_Type__c = CASE_TYPE));
            }
        }
        
        insertDMLBox.add(insertCases, filteredRecords);
        updateDMLBox.add(updateCases, filteredRecords);
        
        insertDMLBox.safeInsert();
        updateDMLBox.safeUpdate();
    }
    
    private static Set<String> getAvailableStatus(String objectName){
        Set<String> results = new Set<String>();
        
        Decimal minPriority = 1000000;
        Decimal maxPriority = 0;
        
        for(CaseTypePriority__c value: priorityMap){
            if(value.ObjectName__c == objectName){
                if(value.Priority__c > maxPriority) maxPriority = value.Priority__c;
                if(value.Priority__c < minPriority) minPriority = value.Priority__c;
            }
        }
        
        if(maxPriority >= minPriority){
            for(CaseTypePriority__c value: priorityMap){
                if(value.Priority__c <= minPriority){
                    results.add(value.CaseType__c);
                }
            }
        }
        return results;
    }
    
    private static Map<Id, List<Case>> getOppToCaseMap(List<Evaluation__c> evaluations){
        Map<Id, List<Case>> resultMap = new  Map<Id, List<Case>>();
        
        Set<Id> oppIds = Pluck.ids('Seller_Opportunity_ID__c', evaluations);
        
        resultMap = GroupBy.ids('Opportunity_ID__c', [SELECT Opportunity_ID__c, Case_Type__c FROM Case WHERE Opportunity_ID__c =:oppIds AND Opportunity_Id__r.RecordType.DeveloperName = 'Seller' AND Case_Type__c != :getAvailableStatus('Evaluation')]);
        
        for(Id oppId : oppIds){
            if(!resultMap.containsKey(oppId)) resultMap.put(oppId, new List<Case>());
        }
        
        return resultMap;
    }
    
}