objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>In_Transit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Transit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Repairs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs Repairs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paperwork_Missing__c</fullName>
        <label>Paperwork Missing</label>
        <picklist>
            <picklistValues>
                <fullName>Yes - More Than 7 Days Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes - Less Than 7 Days Unavailable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes - Available Without Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Photos_Ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Photos Ready</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BluewolfOpportunityServiceTest.cls
@isTest
private class BluewolfOpportunityServiceTest {
    static final Integer TEST_NUM = /*Limits.getLimitQueries() + */1;
    
    static testMethod void testBeforeUpdate(){
        BluewolfOpportunityTriggerHandler.bypassTrigger = true;
        BluewolfVehicleTriggerHandler.bypassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, false)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(TEST_NUM).create().getRecords();

        List<Opportunity> testOpportunities = new BluewolfSObjectBuilder(Opportunity.sObjectType)
            .put(Opportunity.RecordTypeId, BluewolfOpportunityService.SELLER_OPP_ID)
            .put(Opportunity.Vehicle_Id__c, BluewolfFieldProviderFactory.provideList(Pluck.ids(testVehicles)))
            .put(Opportunity.StageName, 'Leads')
            .count(TEST_NUM).create().getRecords();
       
        Map<Id, Opportunity> oldOpp = new Map<Id, Opportunity>(testOpportunities.deepClone(true/*preserve Ids*/));

        for (Opportunity opp : testOpportunities) {
            opp.StageName = BluewolfOpportunityService.AVAILABLE_STAGE;
        }
        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfOpportunityService.caseOwnerId = testUser.Id;
        BluewolfVehicleTriggerHandler.bypassTrigger = false;
         BluewolfOpportunityTriggerHandler.bypassTrigger = false;
        Test.startTest();
            BluewolfOpportunityService.beforeUpdate(testOpportunities, oldOpp);
        Test.stopTest();
    }
    
        static testMethod void testCreateCases(){
        
        BluewolfOpportunityTriggerHandler.bypassTrigger = true;
        
        List<Opportunity> opps = new SObjectBuilder(Opportunity.SObjectType)
                                        .count(TEST_NUM).build().getRecords();
                                        
        BluewolfOpportunityTriggerHandler.bypassTrigger = false;
        
        Test.startTest();
            BluewolfOpportunityService.createCases(opps);
        Test.stopTest();
        
        List<Case> actual = [SELECT Case_Type__c, AccountId, OwnerId FROM Case];
        system.assertEquals(actual.size(), TEST_NUM, 'the size should be equal');
        
        for(Case aCase: actual){
            system.assertEquals(aCase.Case_Type__c, BluewolfOpportunityService.CASE_TYPE, 'the case type should be equal');
        }
    }
    
    static testMethod void testAfterInsert(){
        
        BluewolfOpportunityTriggerHandler.bypassTrigger = true;
        
        
        List<Opportunity> opps = new SObjectBuilder(Opportunity.SObjectType)
                                        .put(Opportunity.RecordTypeId, BluewolfOpportunityService.SELLER_OPP_ID)
                                        .put(Opportunity.StageName, 'Leads')
                                        .count(TEST_NUM).build().getRecords();
                                        
        BluewolfOpportunityTriggerHandler.bypassTrigger = false;
        
        Test.startTest();
            BluewolfOpportunityService.afterInsert(opps);
        Test.stopTest();
        
        List<Case> actual = [SELECT Case_Type__c, AccountId, OwnerId FROM Case];
        system.assertEquals(actual.size(), TEST_NUM, 'the size should be equal');
        
        for(Case aCase: actual){
            system.assertEquals(aCase.Case_Type__c, BluewolfOpportunityService.CASE_TYPE, 'the case type should be equal');
        }
    }
}