objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Drive_Notes__c</fullName>
        <label>Test Drive Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Test_Drive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Drive</label>
        <referenceTo>Test_Drive__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle Interest</label>
        <referenceTo>Vehicle_Interest__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Test_Drive__c.object
<CustomObject>
    <description>Test Drive related to a Buyer Opportunity</description>
    <fields>
        <fullName>Canceled_Reason__c</fullName>
        <label>Canceled Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Below $250 Shift Margin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car already sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car in shop/not working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car on deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer bought another car (not with Shift)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer bought another car (with Shift)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer no longer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shift Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Switched interest to another Shift car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timing issue on customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timing issue on Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Canceled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Canceled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Steps__c</fullName>
        <label>Next Steps</label>
        <picklist>
            <picklistValues>
                <fullName>CE - Apply For Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Email Requested Information To Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Schedule Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX - Schedule Another Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Recommend Another Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In Two Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In One Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In Two Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In Four Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In Three Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up When Vehicle Repaired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>- How did the test drive go?
- Did they commit to buying? If not, what were their objections?
- What is the action plan to get them into a car they want</inlineHelpText>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vehicle_Interest_ID__c</fullName>
        <label>Vehicle Interest</label>
        <referenceTo>Vehicle_Interest__c</referenceTo>
        <relationshipLabel>Test Drives</relationshipLabel>
        <relationshipName>Test_Drives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Test Drive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Coming_Soon__c</fullName>
        <formula>OR(
Needs_Repairs__c = True,
In_Transit__c = True,
(ISPICKVAL(Paperwork_Missing__c, &apos;Yes - Less Than 7 Days Unavailable&apos;)),
(ISPICKVAL(Paperwork_Missing__c, &apos;Yes - More Than 7 Days Unavailable&apos;)),
(Seller_Stage__c =&apos;Prepare Car for Sale&apos;),
(Photos_Ready__c = False)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Coming Soon</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Going_To_Auction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Going To Auction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hold_For_Financing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hold For Financing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hold_For_Trade_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hold For Trade-In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_Transit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Transit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Repairs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs Repairs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_Deposit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Deposit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paperwork_Missing__c</fullName>
        <label>Paperwork Missing</label>
        <picklist>
            <picklistValues>
                <fullName>Yes - More Than 7 Days Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes - Less Than 7 Days Unavailable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes - Available Without Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Photos_Ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Photos Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sale_Pending__c</fullName>
        <formula>OR( 
On_Deposit__c = True, 
Going_To_Auction__c = True,
Hold_For_Financing__c = True,
Hold_For_Trade_In__c = True 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sale Pending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a seller opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Buyer_Opportunity_ID__c</fullName>
        <label>Buyer Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a Buyer Opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicle Interests</relationshipLabel>
        <relationshipName>Vehicle_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Drive__c</fullName>
        <formula>Test_Drive_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test Drive</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle Interest</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vehicle_Order__c.object
<CustomObject>
    <description>Orders represent the process of a Buyer purchasing a Vehicle. Note that we don&apos;t name this object simple &quot;Order&quot; so as to avoid confusion with the standard salesforce Order object. We may one day decide to use that object instead, but not until we understand more about whether it fits with our model.</description>
    <fields>
        <fullName>Buyer_Opportunity_ID__c</fullName>
        <label>Buyer Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BluewolfTestDriveRequestServices.cls
public with sharing class BluewolfTestDriveRequestServices {
    public static Boolean byPassTrigger = false;

    @testVisible private static String RESCHEDULE_NEXT_STEP = 'CX - Schedule Another Test Drive';
    @testVisible private static String PAID_IN_FULL = 'Purchased Car - Paid In Full';

    @testVisible private static String CASE_OWNER_NAME = 'unowned';

    @testVisible private static String DRIVE_REQUEST_TYPE = 'Car Enthusiast Test Drive Request';
    @testVisible private static String FOLLOWUP_TYPE = 'Cancellation Follow Up';
    @testVisible private static String AVAILABLE_TYPE = 'Vehicle Available - Schedule Test Drives';
    @testVisible private static String UNAVAILABLE_TYPE = 'Vehicle Unavailable - Cancel Test Drives';

    @testVisible private static List<String> NO_RESCHEDULE_REASONS = new List<String> {
        'Customer bought another car (with Shift)',
        'Customer bought another car (not with Shift)',
        'Switched interest to another Shift car'
    };

    @testVisible
    private static Id caseOwnerId {
        get {
            if (caseOwnerId == null) {
                caseOwnerId = [SELECT Id FROM User WHERE Shift_Key__c = :CASE_OWNER_NAME].Id;
            }
            return caseOwnerId;
        }
        private set;
    }

    private static Select.Filter getRescheduledFilter() {
        return Select.Field.hasChanged(Test_Drive__c.Next_Steps__c).andx(
               Select.Field.isEqual(Test_Drive__c.Next_Steps__c, RESCHEDULE_NEXT_STEP)
        );
    }

    private static Select.Filter getCanceledFilter() {
        return Select.Field.hasChanged(Test_Drive__c.Canceled__c).andx(
            Select.Field.isEqual(Test_Drive__c.Canceled__c, true)
        ).andx(
            Select.Field.notIn(Test_Drive__c.Canceled_Reason__c, NO_RESCHEDULE_REASONS)
        );
    }
    private static List<Vehicle__c> newVehicles;
    private static Map<Id, Boolean> depositeReturnReasonMap;
    public static void requestDriveIfCanceled(List<Test_Drive__c> drives, Map<Id, Test_Drive__c> oldDrives) {
        if(byPassTrigger) return;
        
        List<Test_Drive__c> drivesRescheduled = getRescheduledFilter().filter(drives, oldDrives);
        List<Test_Drive__c> drivesCanceled = getCanceledFilter().filter(drives, oldDrives);

        List<Test_Drive__c> drivesToRequest = new List<Test_Drive__c>();
        drivesToRequest.addAll(drivesCanceled);
        drivesToRequest.addAll(drivesRescheduled);

        if (drivesToRequest.isEmpty()) {
            return;
        }

        Map<Id, Vehicle_Interest__c> vehicleInterestMap = new Map<Id, Vehicle_Interest__c>([
            SELECT Buyer_Opportunity_ID__c
            FROM   Vehicle_Interest__c
            WHERE  Id IN :BluewolfPluck.Ids(Test_Drive__c.Vehicle_Interest_ID__c, drivesToRequest)
        ]);

        List<Case> casesToCreate = new List<Case>();

        for (Test_Drive__c drive : drivesRescheduled) {
            casesToCreate.add(new Case(
                OwnerId = caseOwnerId,
                Case_Type__c = DRIVE_REQUEST_TYPE,
                Test_Drive_Notes__c = drive.Notes__c,
                Opportunity_ID__c = vehicleInterestMap.get(drive.Vehicle_Interest_ID__c).Buyer_Opportunity_ID__c,
                Test_Drive__c = drive.Id
            ));
        }
        for (Test_Drive__c drive : drivesCanceled) {
            casesToCreate.add(new Case(
                OwnerId = caseOwnerId,
                Case_Type__c = FOLLOWUP_TYPE,
                Test_Drive_Notes__c = drive.Notes__c,
                Opportunity_ID__c = vehicleInterestMap.get(drive.Vehicle_Interest_ID__c).Buyer_Opportunity_ID__c,
                Test_Drive__c = drive.Id
            ));
        }

        try {
            insert casesToCreate;
        } catch (DmlException ex) {
            for (Test_Drive__c drive : drives) {
                drive.addError(ex);
            }
        }
    }

    /* Update */
    public static void requestDriveIfAvailabilityChanges(List<Vehicle__c> vehicles, Map<Id, Vehicle__c> oldVehicles) {
        if(byPassTrigger) return;

        if(newVehicles == null) newVehicles = [SELECT Id, Sale_Pending__c, Going_To_Auction__c, Hold_For_Financing__c, Hold_For_Trade_In__c, On_Deposit__c, Needs_Repairs__c, In_Transit__c, Paperwork_Missing__c, Photos_Ready__c, Seller_Opportunity_Id__r.StageName FROM Vehicle__c WHERE Id =: vehicles];
        vehicles = (newVehicles == null || newVehicles.isEmpty()) ? vehicles: newVehicles;
        List<Case> casesToCreate = new List<Case>();
        Set<Id> vehiclesUnavailable = new Set<Id>();
        if(depositeReturnReasonMap == null) depositeReturnReasonMap = getDepositReturnReasonMap(vehicles);
        for (Vehicle__c vehicle : vehicles) {
            Vehicle__c oldVehicle = oldVehicles.get(vehicle.Id);
            Boolean currentComingSoon = getComingSoon(vehicle);
            Boolean currentSalePending = getSalePending(vehicle);
            Boolean currentReason = depositeReturnReasonMap.get(vehicle.Id);
            currentReason = currentReason == null? false: currentReason;
            if(oldVehicle != null){
                if (currentComingSoon != oldVehicle.Coming_Soon__c || currentSalePending != oldVehicle.Sale_Pending__c) {
                    Case createdCase = new Case(
                        OwnerId = caseOwnerId,
                        Vehicle_ID__c = vehicle.Id
                    );
    
                    Boolean currentSwitch = currentComingSoon != oldVehicle.Coming_Soon__c ? currentComingSoon : currentSalePending;
                    if (currentSwitch) {
                        createdCase.Case_Type__c = UNAVAILABLE_TYPE;
                        vehiclesUnavailable.add(vehicle.Id);
                    } else {
                        createdCase.Case_Type__c = AVAILABLE_TYPE;
                    }
                    system.debug(currentSalePending + '-' + oldVehicle.Sale_Pending__c + '-' + currentReason + '-' + createdCase);
                    if(currentSalePending == oldVehicle.Sale_Pending__c || (currentSalePending || !currentReason))
                        casesToCreate.add(createdCase);
                }
            }
        }

        //if (!vehiclesUnavailable.isEmpty()) {
        //    casesToCreate.addAll(createTestDriveCases(vehiclesUnavailable));
        //}

        if (casesToCreate.isEmpty()) {
            return;
        }

        try {
            insert casesToCreate;
        } catch (DMLException ex) {
            for (Vehicle__c vehicle : vehicles) {
                vehicle.addError(ex);
            }
        }
    }

    /* Update */
    public static void requestDriveIfSoldOrReturned(List<Vehicle_Order__c> orders, Map<Id, Vehicle_Order__c> oldOrders) {
        if(byPassTrigger) return;
    
        Map<Id, Case> casesByVehicle = new Map<Id, Case>();
        Set<Id> vehiclesUnavailable = new Set<Id>();

        for (Vehicle_Order__c order : orders) {
            Vehicle_Order__c oldOrder = oldOrders.get(order.Id);

            if (nowUnavailable(order, oldOrder)) {
                casesByVehicle.put(order.Vehicle_ID__c, new Case(
                    OwnerId = caseOwnerId,
                    Case_Type__c = UNAVAILABLE_TYPE,
                    Vehicle_ID__c = order.Vehicle_ID__c
                ));
                vehiclesUnavailable.add(order.Vehicle_ID__c);
            } else if (nowAvailable(order, oldOrder)) {
                casesByVehicle.put(order.Vehicle_ID__c, new Case(
                    OwnerId = caseOwnerId,
                    Case_Type__c = AVAILABLE_TYPE,
                    Vehicle_ID__c = order.Vehicle_ID__c
                ));
            }
        }

        List<Case> casesToCreate = new List<Case>(casesByVehicle.values());

        //if (!vehiclesUnavailable.isEmpty()) {
        //    casesToCreate.addAll(createTestDriveCases(vehiclesUnavailable));
        //}

        if (casesByVehicle.isEmpty()) {
            return;
        }

        try {
            insert casesByVehicle.values();
        } catch (DMLException ex) {
            for (Vehicle_Order__c order : orders) {
                order.addError(ex);
            }
        }
    }
    
    private static List<Case> createTestDriveCases(Set<Id> vehicleIds) {
        List<Case> casesToCreate = new List<Case>();

        List<Test_Drive__c> drivesToReschedule = [
            SELECT Id
            FROM   Test_Drive__c
            WHERE  Vehicle_Interest_ID__r.Vehicle_ID__c IN :vehicleIds
               AND Scheduled_For__c >= :DateTime.now()
        ];

        for (Test_Drive__c drive : drivesToReschedule) {
            casesToCreate.add(new Case(
                OwnerId = caseOwnerId,
                Case_Type__c = UNAVAILABLE_TYPE,
                Test_Drive__c = drive.Id
            ));
        }
        return casesToCreate;
    }

    private static Boolean getComingSoon(Vehicle__c vehicle) {
        
        Boolean result = vehicle.Needs_Repairs__c || vehicle.In_Transit__c || vehicle.Paperwork_Missing__c ==  'Yes - Less Than 7 Days Unavailable' || vehicle.Paperwork_Missing__c == 'Yes - More Than 7 Days Unavailable' || !vehicle.Photos_Ready__c;
        if(vehicle.Seller_Opportunity_Id__r.StageName == null || vehicle.Seller_Opportunity_Id__r.StageName != 'Prepare Car for Sale'){
            return result;
        }
        else{
            return true;
        }
        
    }

     private static Boolean nowAvailable(Vehicle_Order__c order, Vehicle_Order__c oldOrder) {
        if (order.Returned_On__c != null && oldOrder.Returned_On__c == null)
            return true;

        return false;
    }

    private static Boolean nowUnavailable(Vehicle_Order__c order, Vehicle_Order__c oldOrder) {
        Vehicle_Order__c calculatedOrder = new Vehicle_Order__c(
            Final_Sale_Price__c = order.Final_Sale_Price__c,
            Taxes_And_Registration__c = order.Taxes_And_Registration__c,
            Payment_Method__c = order.Payment_Method__c,
            Vehicle_Sale_Complete__c = order.Vehicle_Sale_Complete__c
        );
        calculatedOrder.recalculateFormulas();

        if (calculatedOrder.Vehicle_Purchased__c && !oldOrder.Vehicle_Purchased__c)
            return true;
        return false;
    }
    
    private static Boolean getSalePending(Vehicle__c vehicle) {
        // recalculateFormulas() is very broken, and doesn't work well
        // if more fields than whats needed are selected (such as a lookup or created date).
        Vehicle__c temp = new Vehicle__c(
            On_Deposit__c = vehicle.On_Deposit__c,
            Going_To_Auction__c = vehicle.Going_To_Auction__c,
            Hold_For_Financing__c = vehicle.Hold_For_Financing__c ,
            Hold_For_Trade_In__c = vehicle.Hold_For_Trade_In__c
        );
        temp.recalculateFormulas();
        return temp.Sale_Pending__c;
    }
    
    private static Map<Id, Boolean> getDepositReturnReasonMap(List<Vehicle__c> vehicles){
        Map<Id, Boolean> resultMap = new Map<Id, Boolean> ();
        
        Map<Id, List<Vehicle_Order__c>> vehicleInterestMap = BluewolfGroupBy.ids('Vehicle_Id__c', [SELECT Vehicle_Id__c, Deposit_Returned_Reason__c FROM Vehicle_Order__c WHERE Vehicle_ID__c = :vehicles ORDER BY LastModifiedDate]);
        for(Id vehicleId : vehicleInterestMap.keySet()){
            
            List<Vehicle_Order__c> orders = vehicleInterestMap.get(vehicleId);
            if(orders != null && !orders.isEmpty()){
                if(orders[0].Deposit_Returned_Reason__c == PAID_IN_FULL){
                    resultMap.put(vehicleId, true);
                }
                else{
                    resultMap.put(vehicleId, false);
                }
            }
            else{
                resultMap.put(vehicleId, false);
            }
        }
        
        return resultMap;
    }
    
     /* Insert */
    public static void requestDriveIfSoldOrReturned(List<Vehicle_Order__c> orders) {
        if(byPassTrigger) return;

        List<Case> casesToCreate = new List<Case>();

        for (Vehicle_Order__c order : orders) {
            if (nowUnavailable(order)) {
                casesToCreate.add(new Case(
                    OwnerId = caseOwnerId,
                    Case_Type__c = UNAVAILABLE_TYPE,
                    Vehicle_ID__c = order.Vehicle_ID__c
                ));
            }
        }

        if (casesToCreate.isEmpty()) {
            return;
        }

        try {
            insert casesToCreate;
        } catch (DMLException ex) {
            for (Vehicle_Order__c order : orders) {
                order.addError(ex);
            }
        }
    }
    
    private static Boolean nowUnavailable(Vehicle_Order__c order) {
        Vehicle_Order__c calculatedOrder = new Vehicle_Order__c(
            Final_Sale_Price__c = order.Final_Sale_Price__c,
            Taxes_And_Registration__c = order.Taxes_And_Registration__c,
            Payment_Method__c = order.Payment_Method__c,
            Vehicle_Sale_Complete__c = order.Vehicle_Sale_Complete__c
        );
        calculatedOrder.recalculateFormulas();

        return calculatedOrder.Vehicle_Purchased__c || order.Deposit_Accepted_On__c != null;
    }    
}