objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/CaseTypePriority__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>CaseType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromAddress__c</fullName>
        <label>FromAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>CaseTypePriority</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BluewolfEmailMessageService.cls
public with sharing class BluewolfEmailMessageService {
    
    @testVisible private static String CASE_OWNER_NAME = 'unowned';
    @TestVisible
    private final static Id SELLER_OPP_ID = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Seller'].Id;
    @TestVisible
    private static Boolean bypassTrigger = false;
    @TestVisible
    private final static String INCOMING_STATUS = 'Needs Action';
    @TestVisible
    private final static String OUTGOING_STATUS = 'Awaiting Response';
    @TestVisible
    private static List<CaseTypePriority__c> priorityMap {
        get{
            if(priorityMap == null){
                priorityMap = CaseTypePriority__c.getAll().values();
            }
            return priorityMap;
        }
        private set;
    } 
    @testVisible
    private static Id caseOwnerId {
        get {
            if (caseOwnerId == null) {
                caseOwnerId = [SELECT Id FROM User WHERE Shift_Key__c = :CASE_OWNER_NAME].Id;
            }
            return caseOwnerId;
        }
        private set;
    }
    private static Map<String, Decimal> caseTypeToPriorityMap {
        get{
            if(caseTypeToPriorityMap == null){
                caseTypeToPriorityMap = new Map<String, Decimal>();
                for(CaseTypePriority__c value: priorityMap){
                    caseTypeToPriorityMap.put(value.CaseType__c, value.Priority__c);
                }
            }
            return caseTypeToPriorityMap;
        }
        private set;
    }
    
    private static Set<Case> emailPriorityCases = new Set<Case>();
    private static Map<Id, String> caseIdToFromAddressMap = new Map<Id, String>();
    private static Map<Id, String> caseIdToAddressMap = new Map<Id, String>();
    
    public static void afterInsert(List<EmailMessage> records){
        
        if(bypassTrigger) return;
        
        Map<Id, Case> emailToCaseMap = getEmailToCaseMap(records);
        
        List<Case> outgoingCases = getRelatedCases(emailToCaseMap, outgoingEmail().filter(records));
        List<Case> incomingCases = getRelatedCases(emailToCaseMap, incomingEmail().filter(records));
        
        List<Case> filteredIncomingCases = Select.Field.notIn(Case.Case_Type__c, getAvailableStatus('EmailMessage')).andx(Select.Field.notEqual('Opportunity_Id__r.RecordTypeId', SELLER_OPP_ID)).filter(incomingCases);
        setCaseToFromAddressMap(records, emailToCaseMap, filteredIncomingCases);
        setCaseToAddressMap(records, emailToCaseMap, filteredIncomingCases);
        changeCaseType(filteredIncomingCases);
        
        changeCaseStatus(outgoingCases, OUTGOING_STATUS);
        changeCaseStatus(incomingCases, INCOMING_STATUS);
        
        List<Case> cases = new List<Case>();
        cases.addAll(outgoingCases);
        cases.addAll(incomingCases);
        updateCases(cases, records);
    }
    
    private static Set<String> getAvailableStatus(String objectName){
        Set<String> results = new Set<String>();
        
        Decimal minPriority = 1000000;
        Decimal maxPriority = 0;
        
        for(CaseTypePriority__c value: priorityMap){
            if(value.ObjectName__c == objectName){
                if(value.Priority__c > maxPriority) maxPriority = value.Priority__c;
                if(value.Priority__c < minPriority) minPriority = value.Priority__c;
            }
        }
        
        if(maxPriority >= minPriority){
            for(CaseTypePriority__c value: priorityMap){
                if(value.Priority__c <= minPriority){
                    results.add(value.CaseType__c);
                }
            }
        }
        
        return results;
    }
    
    private static void setCaseToFromAddressMap(List<EmailMessage> records, Map<Id, Case> emailToCaseMap, List<Case> cases){
        for(Case aCase: cases){
            for(EmailMessage record: records){
                if(emailToCaseMap.get(record.Id) == aCase){
                    caseIdToFromAddressMap.put(aCase.Id, record.FromAddress);
                    break;
                }
            }
        }
    }
    
    private static void setCaseToAddressMap(List<EmailMessage> records, Map<Id, Case> emailToCaseMap, List<Case> cases){
        for(Case aCase: cases){
            for(EmailMessage record: records){
                if(emailToCaseMap.get(record.Id) == aCase){
                    caseIdToAddressMap.put(aCase.Id, record.ToAddress);
                    break;
                }
            }
        }
    }
    
    private static void changeCaseType(List<Case> cases){
        for(Case aCase: cases){
            Decimal currentPriority = caseTypeToPriorityMap.get(aCase.Case_Type__c);
            if(currentPriority != null){
                String newCaseType = getNewCaseType(aCase, currentPriority, 'EmailMessage');
                if(newCaseType != null){
                    aCase.Case_Type__c = newCaseType;
                    aCase.Status = 'New';
                    aCase.OwnerId = caseOwnerId;
                    emailPriorityCases.add(aCase);
                }
            }
        }
    }
    
    private static String getNewCaseType(Case aCase, Decimal currentPriority, String objectName){
        String result;
        String fromAddress = caseIdToFromAddressMap.get(aCase.Id);
        String toAddress = caseIdToAddressMap.get(aCase.Id);
        if(fromAddress != null && toAddress != null && toAddress.contains('sell')){
            for(CaseTypePriority__c value: priorityMap){
                if(value.ObjectName__c == objectName && value.Priority__c < currentPriority){
                    if(value.FromAddress__c == null){
                        currentPriority = value.Priority__c;
                        result = value.CaseType__c;
                    }
                    else{
                        for(String emailAddress: value.FromAddress__c.split(',')){
                            if(fromAddress.containsIgnoreCase(emailAddress.trim())){
                                currentPriority = value.Priority__c;
                                result = value.CaseType__c;
                                break;
                            }
                        }
                    }
                }
            }
        }
        return result;
    }
    
    private static void updateCases(List<Case> cases, List<EmailMessage> records){
        BluewolfDMLBox BluewolfDMLBox = new BluewolfDMLBox();
        BluewolfDMLBox.add(cases, records);
        BluewolfDMLBox.safeUpdate();
    }
    
    @TestVisible
    private static Map<Id, Case> getEmailToCaseMap(List<EmailMessage> records){
        Map<Id, Case> emailToCaseMap = new Map<Id, Case>();
        
        List<Case> relatedCases = [SELECT Status, Opportunity_Id__r.RecordTypeId, Case_Type__c FROM Case WHERE Id = :BluewolfPluck.ids('ParentId', records)];
        for(EmailMessage email: records){
            for(Case aCase: relatedCases){
                if(aCase.Id == email.ParentId){
                    emailToCaseMap.put(email.Id, aCase);
                    break;
                }
            }
        }
        return emailToCaseMap;
    }
 
    @TestVisible
    private static List<Case> getRelatedCases(Map<Id, Case> emailToCaseMap, List<EmailMessage> records){
        List<Case> cases = new List<Case>();
        
        Set<Id> filterIds = BluewolfPluck.ids('Id', records);
        for(Id emailId: emailToCaseMap.keySet()){
            if(filterIds.contains(emailId)){
                cases.add(emailToCaseMap.get(emailId));
            }
        }
        return cases;
    }
    
    @TestVisible
    private static void changeCaseStatus(List<Case> cases, String caseStatus){
        for(Case aCase: cases){
            if(!emailPriorityCases.contains(aCase)){
                aCase.status = caseStatus;
            }
        }
    }
    
    @TestVisible
    private static Select.Filter incomingEmail(){
        return Select.Field.isEqual(EmailMessage.Incoming, true);
    }
    
    @TestVisible
    private static Select.Filter outgoingEmail(){
        return Select.Field.isEqual(EmailMessage.Incoming, false);
    }
}