objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Drive_Notes__c</fullName>
        <label>Test Drive Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Test_Drive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Drive</label>
        <referenceTo>Test_Drive__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle Interest</label>
        <referenceTo>Vehicle_Interest__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle Order</label>
        <referenceTo>Vehicle_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Test_Drive__c.object
<CustomObject>
    <description>Test Drive related to a Buyer Opportunity</description>
    <fields>
        <fullName>Canceled_Reason__c</fullName>
        <label>Canceled Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Below $250 Shift Margin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car already sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car in shop/not working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car on deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer bought another car (not with Shift)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer bought another car (with Shift)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer no longer interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shift Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Switched interest to another Shift car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timing issue on customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timing issue on Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Canceled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Canceled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Steps__c</fullName>
        <label>Next Steps</label>
        <picklist>
            <picklistValues>
                <fullName>CE - Apply For Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Email Requested Information To Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Schedule Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX - Schedule Another Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Recommend Another Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In Two Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In One Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In Two Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In Four Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up In Three Weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE - Follow Up When Vehicle Repaired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>- How did the test drive go?
- Did they commit to buying? If not, what were their objections?
- What is the action plan to get them into a car they want</inlineHelpText>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scheduled_For__c</fullName>
        <label>Scheduled For</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vehicle_Interest_ID__c</fullName>
        <label>Vehicle Interest</label>
        <referenceTo>Vehicle_Interest__c</referenceTo>
        <relationshipLabel>Test Drives</relationshipLabel>
        <relationshipName>Test_Drives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Test Drive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>In_Transit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Transit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Repairs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs Repairs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paperwork_Missing__c</fullName>
        <label>Paperwork Missing</label>
        <picklist>
            <picklistValues>
                <fullName>Yes - More Than 7 Days Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes - Less Than 7 Days Unavailable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes - Available Without Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Photos_Ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Photos Ready</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Buyer_Opportunity_ID__c</fullName>
        <label>Buyer Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a Buyer Opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicle Interests</relationshipLabel>
        <relationshipName>Vehicle_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Drive__c</fullName>
        <formula>Test_Drive_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test Drive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Interests</relationshipLabel>
        <relationshipName>Vehicle_Interests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Interest</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vehicle_Order__c.object
<CustomObject>
    <description>Orders represent the process of a Buyer purchasing a Vehicle. Note that we don&apos;t name this object simple &quot;Order&quot; so as to avoid confusion with the standard salesforce Order object. We may one day decide to use that object instead, but not until we understand more about whether it fits with our model.</description>
    <fields>
        <fullName>Buyer_Opportunity_ID__c</fullName>
        <label>Buyer Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Returned_On__c</fullName>
        <label>Returned On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BluewolfTestDriveRequestServicesTest.cls
@isTest
private class BluewolfTestDriveRequestServicesTest {
    static final Integer BULK_COUNT = /*Limits.getLimitQueries() + */1;

    static Id sellerRecordTypeId {
        get {
            if (sellerRecordTypeId == null) {
                sellerRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Seller'].Id;
            }
            return sellerRecordTypeId;
        }
        private set;
    }

    static testmethod void requestDriveIfCanceled() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;    
        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        List<Vehicle_Interest__c> testInterests = new BluewolfSObjectBuilder(Vehicle_Interest__c.sObjectType)
            .put(Vehicle_Interest__c.Buyer_Opportunity_ID__c, BluewolfSObjectFactory.provideParents(testOpportunities))
            .count(BULK_COUNT).create().getRecords();

        List<Test_Drive__c> testDrives = new BluewolfSObjectBuilder(Test_Drive__c.sObjectType)
            .put(Test_Drive__c.Vehicle_Interest_ID__c, BluewolfSObjectFactory.provideParents(testInterests))
            .put(Test_Drive__c.Canceled__c, false)
            .put(Test_Drive__c.Notes__c, BluewolfSObjectFactory.provideUniqueString())
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Test_Drive__c> oldMap = new Map<Id, Test_Drive__c>(testDrives.deepClone(true /*Preserve Ids*/));
        for (Test_Drive__c testDrive : testDrives) {
            testDrive.Canceled__c = true;
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfCanceled(testDrives, oldMap);
        Test.stopTest();

        Map<Id, Vehicle_Interest__c> interestMap = new Map<Id, Vehicle_Interest__c>(testInterests);
        Map<Id, Test_Drive__c> testDriveMap = new Map<Id, Test_Drive__c>(testDrives);

        List<Case> actualCases = [
            SELECT Opportunity_ID__c, Case_Type__c, Test_Drive_Notes__c,
                   Test_Drive__c, OwnerId
            FROM   Case
        ];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each test drive should get a case');

        for (Case actualCase : actualcases) {
            System.assertEquals(true, testDriveMap.containsKey(actualCase.Test_Drive__c), 'the case should be related to a test drive');
            Test_Drive__c drive = testDriveMap.get(actualCase.Test_Drive__c);

            Id opportunityId = interestMap.get(drive.Vehicle_Interest_ID__c).Buyer_Opportunity_ID__c;
            System.assertEquals(opportunityId, actualCase.Opportunity_ID__c, 'the opportunity id should be set correctly');

            System.assertEquals(drive.Notes__c, actualCase.Test_Drive_Notes__c, 'the notes should be copied over correctly');
            System.assertEquals(BluewolfTestDriveRequestServices.FOLLOWUP_TYPE, actualCase.Case_Type__c, 'the case type should be set correctly');
            System.assertEquals(testUser.Id, actualCase.OwnerId, 'the owner id should be set correctly');
        }
    }

    static testmethod void requestDriveIfCanceled_AlreadyCanceled() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        List<Vehicle_Interest__c> testInterests = new BluewolfSObjectBuilder(Vehicle_Interest__c.sObjectType)
            .put(Vehicle_Interest__c.Buyer_Opportunity_ID__c, BluewolfSObjectFactory.provideParents(testOpportunities))
            .count(BULK_COUNT).create().getRecords();

        List<Test_Drive__c> testDrives = new BluewolfSObjectBuilder(Test_Drive__c.sObjectType)
            .put(Test_Drive__c.Vehicle_Interest_ID__c, BluewolfSObjectFactory.provideParents(testInterests))
            .put(Test_Drive__c.Canceled__c, true)
            .put(Test_Drive__c.Notes__c, BluewolfSObjectFactory.provideUniqueString())
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Test_Drive__c> oldMap = new Map<Id, Test_Drive__c>(testDrives.deepClone(true /*Preserve Ids*/));

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfCanceled(testDrives, oldMap);
        Test.stopTest();

        List<Case> actualCases = [SELECT Opportunity_ID__c, Case_Type__c, Test_Drive_Notes__c, Test_Drive__c, OwnerId FROM Case];
        System.assertEquals(new List<Case>(), actualCases, 'there should be no cases');
    }

    static testmethod void requestDriveIfCanceled_RescheduleNextStep() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        List<Vehicle_Interest__c> testInterests = new BluewolfSObjectBuilder(Vehicle_Interest__c.sObjectType)
            .put(Vehicle_Interest__c.Buyer_Opportunity_ID__c, BluewolfSObjectFactory.provideParents(testOpportunities))
            .count(BULK_COUNT).create().getRecords();

        List<Test_Drive__c> testDrives = new BluewolfSObjectBuilder(Test_Drive__c.sObjectType)
            .put(Test_Drive__c.Vehicle_Interest_ID__c, BluewolfSObjectFactory.provideParents(testInterests))
            .put(Test_Drive__c.Canceled__c, true)
            .put(Test_Drive__c.Notes__c, BluewolfSObjectFactory.provideUniqueString())
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Test_Drive__c> oldMap = new Map<Id, Test_Drive__c>(testDrives.deepClone(true /*Preserve Ids*/));

        for (Test_Drive__c testDrive : testDrives) {
            testDrive.Next_Steps__c = BluewolfTestDriveRequestServices.RESCHEDULE_NEXT_STEP;
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfCanceled(testDrives, oldMap);
        Test.stopTest();

        Map<Id, Vehicle_Interest__c> interestMap = new Map<Id, Vehicle_Interest__c>(testInterests);
        Map<Id, Test_Drive__c> testDriveMap = new Map<Id, Test_Drive__c>(testDrives);

        List<Case> actualCases = [
            SELECT Opportunity_ID__c, Case_Type__c, Test_Drive_Notes__c,
                   Test_Drive__c, OwnerId
            FROM   Case
        ];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each test drive should get a case');

        for (Case actualCase : actualcases) {
            System.assertEquals(true, testDriveMap.containsKey(actualCase.Test_Drive__c), 'the case should be related to a test drive');
            Test_Drive__c drive = testDriveMap.get(actualCase.Test_Drive__c);

            Id opportunityId = interestMap.get(drive.Vehicle_Interest_ID__c).Buyer_Opportunity_ID__c;
            System.assertEquals(opportunityId, actualCase.Opportunity_ID__c, 'the opportunity id should be set correctly');

            System.assertEquals(drive.Notes__c, actualCase.Test_Drive_Notes__c, 'the notes should be copied over correctly');
            System.assertEquals(BluewolfTestDriveRequestServices.DRIVE_REQUEST_TYPE, actualCase.Case_Type__c, 'the case type should be set correctly');
            System.assertEquals(testUser.Id, actualCase.OwnerId, 'the owner id should be set correctly');
        }
    }

    static testmethod void requestDriveIfCanceled_InvalidReason() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        final String CANCEL_REASON_INVALID = new List<String>(BluewolfTestDriveRequestServices.NO_RESCHEDULE_REASONS)[0];

        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        List<Vehicle_Interest__c> testInterests = new BluewolfSObjectBuilder(Vehicle_Interest__c.sObjectType)
            .put(Vehicle_Interest__c.Buyer_Opportunity_ID__c, BluewolfSObjectFactory.provideParents(testOpportunities))
            .count(BULK_COUNT).create().getRecords();

        List<Test_Drive__c> testDrives = new BluewolfSObjectBuilder(Test_Drive__c.sObjectType)
            .put(Test_Drive__c.Vehicle_Interest_ID__c, BluewolfSObjectFactory.provideParents(testInterests))
            .put(Test_Drive__c.Canceled__c, false)
            .put(Test_Drive__c.Notes__c, BluewolfSObjectFactory.provideUniqueString())
            .put(Test_Drive__c.Canceled_Reason__c, CANCEL_REASON_INVALID)
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Test_Drive__c> oldMap = new Map<Id, Test_Drive__c>(testDrives.deepClone(true /*Preserve Ids*/));

        for (Test_Drive__c testDrive : testDrives) {
            testDrive.Canceled__c = true;
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfCanceled(testDrives, oldMap);
        Test.stopTest();

        List<Case> actualCases = [SELECT Opportunity_ID__c, Case_Type__c, Test_Drive_Notes__c, Test_Drive__c, OwnerId FROM Case];
        System.assertEquals(new List<Case>(), actualCases, 'there should be no cases');
    }

    static testmethod void requestDriveIfCanceled_Trigger() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        List<Vehicle_Interest__c> testInterests = new BluewolfSObjectBuilder(Vehicle_Interest__c.sObjectType)
            .put(Vehicle_Interest__c.Buyer_Opportunity_ID__c, BluewolfSObjectFactory.provideParents(testOpportunities))
            .count(BULK_COUNT).create().getRecords();

        List<Test_Drive__c> testDrives = new BluewolfSObjectBuilder(Test_Drive__c.sObjectType)
            .put(Test_Drive__c.Vehicle_Interest_ID__c, BluewolfSObjectFactory.provideParents(testInterests))
            .put(Test_Drive__c.Canceled__c, false)
            .put(Test_Drive__c.Notes__c, BluewolfSObjectFactory.provideUniqueString())
            .count(BULK_COUNT).create().getRecords();

        for (Test_Drive__c testDrive : testDrives) {
            testDrive.Canceled__c = true;
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            update testDrives;
        Test.stopTest();

        Map<Id, Vehicle_Interest__c> interestMap = new Map<Id, Vehicle_Interest__c>(testInterests);
        Map<Id, Test_Drive__c> testDriveMap = new Map<Id, Test_Drive__c>(testDrives);

        List<Case> actualCases = [
            SELECT Opportunity_ID__c, Case_Type__c, Test_Drive_Notes__c,
                   Test_Drive__c, OwnerId
            FROM   Case
        ];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each test drive should get a case');

        for (Case actualCase : actualcases) {
            System.assertEquals(true, testDriveMap.containsKey(actualCase.Test_Drive__c), 'the case should be related to a test drive');
            Test_Drive__c drive = testDriveMap.get(actualCase.Test_Drive__c);

            Id opportunityId = interestMap.get(drive.Vehicle_Interest_ID__c).Buyer_Opportunity_ID__c;
            System.assertEquals(opportunityId, actualCase.Opportunity_ID__c, 'the opportunity id should be set correctly');

            System.assertEquals(drive.Notes__c, actualCase.Test_Drive_Notes__c, 'the notes should be copied over correctly');
            System.assertEquals(BluewolfTestDriveRequestServices.FOLLOWUP_TYPE, actualCase.Case_Type__c, 'the case type should be set correctly');
            System.assertEquals(testUser.Id, actualCase.OwnerId, 'the owner id should be set correctly');
        }
    }

    static testmethod void requestDriveIfCanceled_Trigger_AlreadyCanceled() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        List<Vehicle_Interest__c> testInterests = new BluewolfSObjectBuilder(Vehicle_Interest__c.sObjectType)
            .put(Vehicle_Interest__c.Buyer_Opportunity_ID__c, BluewolfSObjectFactory.provideParents(testOpportunities))
            .count(BULK_COUNT).create().getRecords();

        List<Test_Drive__c> testDrives = new BluewolfSObjectBuilder(Test_Drive__c.sObjectType)
            .put(Test_Drive__c.Vehicle_Interest_ID__c, BluewolfSObjectFactory.provideParents(testInterests))
            .put(Test_Drive__c.Canceled__c, true)
            .put(Test_Drive__c.Notes__c, BluewolfSObjectFactory.provideUniqueString())
            .count(BULK_COUNT).create().getRecords();

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            update testDrives;
        Test.stopTest();

        List<Case> actualCases = [SELECT Opportunity_ID__c, Case_Type__c, Test_Drive_Notes__c, Test_Drive__c, OwnerId FROM Case];
        System.assertEquals(new List<Case>(), actualCases, 'there should be no cases');
    }

    static testmethod void requestDriveIfAvailabilityChanges_ComingSoon() {
        BluewolfVehicleTriggerHandler.bypassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, false)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(BULK_COUNT).create().getRecords();

        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        List<Vehicle_Interest__c> testInterests = new BluewolfSObjectBuilder(Vehicle_Interest__c.sObjectType)
            .put(Vehicle_Interest__c.Vehicle_ID__c, BluewolfSObjectFactory.provideParents(testVehicles))
            .put(Vehicle_Interest__c.Buyer_Opportunity_ID__c, BluewolfSObjectFactory.provideParents(testOpportunities))
            .count(BULK_COUNT).create().getRecords();

        List<Test_Drive__c> testDrives = new BluewolfSObjectBuilder(Test_Drive__c.sObjectType)
            .put(Test_Drive__c.Vehicle_Interest_ID__c, BluewolfSObjectFactory.provideParents(testInterests))
            .put(Test_Drive__c.Scheduled_For__c, DateTime.now().addDays(1))
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Vehicle__c> oldVehicles = new Map<Id, Vehicle__c>(testVehicles.deepClone(true/*preserve Ids*/));
        for (Vehicle__c vehicle : oldVehicles.values()) {
            vehicle.recalculateFormulas();
        }

        for (Vehicle__c vehicle : testVehicles) {
            vehicle.In_Transit__c = true;
        }

        update testVehicles;
        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;
        
        BluewolfVehicleTriggerHandler.bypassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfAvailabilityChanges(testVehicles, oldVehicles);
        Test.stopTest();

        List<Case> allCases = [SELECT Vehicle_ID__c, Case_Type__c, Test_Drive__c, OwnerId FROM Case];
        List<Case> vehicleCases = Select.Field.notNull(Case.Vehicle_ID__c).filter(allCases);

        System.assertEquals(BULK_COUNT, vehicleCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, vehicleCases), 'each vehicle should get a case');

        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.UNAVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, allCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, allCases), 'each case should have the correct owner');
    }
    static testmethod void requestDriveIfAvailabilityChanges_ComingSoon_PreviousDrives() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        BluewolfVehicleTriggerHandler.bypassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, false)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(BULK_COUNT).create().getRecords();

        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        List<Vehicle_Interest__c> testInterests = new BluewolfSObjectBuilder(Vehicle_Interest__c.sObjectType)
            .put(Vehicle_Interest__c.Vehicle_ID__c, BluewolfSObjectFactory.provideParents(testVehicles))
            .put(Vehicle_Interest__c.Buyer_Opportunity_ID__c, BluewolfSObjectFactory.provideParents(testOpportunities))
            .count(BULK_COUNT).create().getRecords();

        List<Test_Drive__c> testDrives = new BluewolfSObjectBuilder(Test_Drive__c.sObjectType)
            .put(Test_Drive__c.Vehicle_Interest_ID__c, BluewolfSObjectFactory.provideParents(testInterests))
            .put(Test_Drive__c.Scheduled_For__c, DateTime.now().addDays(-1))
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Vehicle__c> oldVehicles = new Map<Id, Vehicle__c>(testVehicles.deepClone(true/*preserve Ids*/));
        for (Vehicle__c vehicle : oldVehicles.values()) {
            vehicle.recalculateFormulas();
        }

        for (Vehicle__c vehicle : testVehicles) {
            vehicle.In_Transit__c = true;
        }
        update testVehicles;
        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;
        BluewolfVehicleTriggerHandler.bypassTrigger = false;
        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfAvailabilityChanges(testVehicles, oldVehicles);
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, actualCases), 'each vehicle should get a case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.UNAVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }

    static testmethod void requestDriveIfAvailabilityChanges_NoChange() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, false)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Vehicle__c> oldVehicles = new Map<Id, Vehicle__c>(testVehicles.deepClone(true /*preserve Ids*/));
        for (Vehicle__c vehicle : oldVehicles.values()) {
            vehicle.recalculateFormulas();
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfAvailabilityChanges(testVehicles, oldVehicles);
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(new List<Case>(), actualCases, 'no cases should be created');
    }

    static testmethod void requestDriveIfAvailabilityChanges_ComingSoon_Trigger_Update() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, false)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(BULK_COUNT).create().getRecords();

        for (Vehicle__c vehicle : testVehicles) {
            vehicle.In_Transit__c = true;
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            update testVehicles;
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, actualCases), 'each vehicle should get a case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.UNAVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }
      
    static testmethod void requestDriveIfAvailabilityChanges_NotComingSoon_Trigger() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, true)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(BULK_COUNT).create().getRecords();

        for (Vehicle__c vehicle : testVehicles) {
            vehicle.In_Transit__c = false;
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            update testVehicles;
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, actualCases), 'each vehicle should get a case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.AVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }

    static testmethod void requestDriveIfAvailabilityChanges_NoChange_Trigger() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, false)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(BULK_COUNT).create().getRecords();

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            update testVehicles;
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(new List<Case>(), actualCases, 'no cases should be created');
    }

    static testmethod void requestDriveIfSoldOrReturned_Available() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .count(BULK_COUNT).create().getRecords();

        List<Vehicle_Order__c> testOrders = new BluewolfSObjectBuilder(Vehicle_Order__c.sObjectType)
            .put(Vehicle_Order__c.Vehicle_ID__c, BluewolfSObjectFactory.provideParents(testVehicles))
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Vehicle_Order__c> oldOrders = new Map<Id, Vehicle_Order__c>(testOrders.deepClone(true/*preserve Ids*/));

        for (Vehicle_Order__c order : testOrders) {
            order.Returned_On__c = Date.today();
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfSoldOrReturned(testOrders, oldOrders);
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, actualCases), 'each vehicle should get a case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.AVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }

    static testmethod void requestDriveIfSoldOrReturned_PaidInFull() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .count(BULK_COUNT).create().getRecords();

        List<Vehicle_Order__c> testOrders = new BluewolfSObjectBuilder(Vehicle_Order__c.sObjectType)
            .put(Vehicle_Order__c.Vehicle_ID__c, BluewolfSObjectFactory.provideParents(testVehicles))
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Vehicle_Order__c> oldOrders = new Map<Id, Vehicle_Order__c>(testOrders.deepClone(true/*preserve Ids*/));

        for (Vehicle_Order__c order : testOrders) {
            order.Deposit_Returned_Reason__c = BluewolfTestDriveRequestServices.PAID_IN_FULL;
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfSoldOrReturned(testOrders, oldOrders);
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(0, actualCases.size(), 'no cases should be created');
    }

    static testmethod void requestDriveIfSoldOrReturned_SameVehicle() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle_Order__c> testOrders = new BluewolfSObjectBuilder(Vehicle_Order__c.sObjectType)
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Vehicle_Order__c> oldOrders = new Map<Id, Vehicle_Order__c>(testOrders.deepClone(true/*preserve Ids*/));

        for (Vehicle_Order__c order : testOrders) {
            order.Returned_On__c = Date.today();
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfSoldOrReturned(testOrders, oldOrders);
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(1, actualCases.size(), 'there should only be one case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.AVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }

    static testmethod void requestDriveIfSoldOrReturned_NoChange() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle_Order__c> testOrders = new BluewolfSObjectBuilder(Vehicle_Order__c.sObjectType)
            .count(BULK_COUNT).create().getRecords();

        Map<Id, Vehicle_Order__c> oldOrders = new Map<Id, Vehicle_Order__c>(testOrders.deepClone(true/*preserve Ids*/));

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfSoldOrReturned(testOrders, oldOrders);
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(new List<Case>(), actualCases, 'no cases should be created');
    }

    static /*testmethod*/ void requestDriveIfSoldOrReturned_Available_Trigger() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        // We're having trouble getting the data to set up correctly.
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .count(BULK_COUNT).create().getRecords();

        List<Opportunity> sellerOpportunities = new BluewolfSObjectBuilder(Opportunity.sObjectType)
            .put(Opportunity.RecordTypeId, sellerRecordTypeId)
            .put(Opportunity.Vehicle_ID__c, BluewolfSObjectFactory.provideParents(testVehicles))
            .count(BULK_COUNT).create().getRecords();

        for (Integer n = 0; n < BULK_COUNT; n++) {
            testVehicles[n].Seller_Opportunity_ID__c = sellerOpportunities[n].Id;
        }
        update testVehicles;

        List<Vehicle_Order__c> testOrders = new BluewolfSObjectBuilder(Vehicle_Order__c.sObjectType)
            .put(Vehicle_Order__c.Final_Sale_Price__c, 3.50)
            .put(Vehicle_Order__c.Taxes_And_Registration__c, 3.50)
            .put(Vehicle_Order__c.Payment_Method__c, 'Poultry')
            .put(Vehicle_Order__c.Vehicle_Sale_Complete__c, true)
            .put(Vehicle_Order__c.Vehicle_ID__c, BluewolfSObjectFactory.provideParents(testVehicles))
            .put(Vehicle_Order__c.Deposit_Accepted_On__c, Date.today())
            .count(BULK_COUNT).create().getRecords();

        for (Vehicle_Order__c order : testOrders) {
            order.Returned_On__c = Date.today();
            order.Returned_Reason__c = 'yes';
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            update testOrders;
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, actualCases), 'each vehicle should get a case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.AVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }

    static testmethod void requestDriveIfSoldOrReturned_Unavailable_Trigger_Update() {
        BluewolfTestDriveRequestServices.byPassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .count(BULK_COUNT).create().getRecords();

        List<Vehicle_Order__c> testOrders = new BluewolfSObjectBuilder(Vehicle_Order__c.sObjectType)
            .put(Vehicle_Order__c.Vehicle_ID__c, BluewolfSObjectFactory.provideParents(testVehicles))
            .count(BULK_COUNT).create().getRecords();

        for (Vehicle_Order__c order : testOrders) {
            order.Deposit_Accepted_On__c = Date.today();
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfTestDriveRequestServices.byPassTrigger = false;
        Test.startTest();
            update testOrders;
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, actualCases), 'each vehicle should get a case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.UNAVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }
    
    static testmethod void requestDriveIfAvailabilityChanges_SalePending() {
        
        BluewolfVehicleTriggerHandler.bypassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.On_Deposit__c, false)
            .put(Vehicle__c.Going_To_Auction__c, false)
            .put(Vehicle__c.Hold_For_Financing__c, false)
            .put(Vehicle__c.Hold_For_Trade_In__c, false)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, false)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(BULK_COUNT).create().getRecords();

        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);


        Map<Id, Vehicle__c> oldVehicles = new Map<Id, Vehicle__c>(testVehicles.deepClone(true/*preserve Ids*/));
        for (Vehicle__c vehicle : oldVehicles.values()) {
            vehicle.recalculateFormulas();
        }

        for (Vehicle__c vehicle : testVehicles) {
            vehicle.Hold_For_Financing__c = true;
        }
        update testVehicles;
        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;
        BluewolfVehicleTriggerHandler.bypassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfAvailabilityChanges(testVehicles, oldVehicles);
        Test.stopTest();

        List<Case> allCases = [SELECT Vehicle_ID__c, Case_Type__c, Test_Drive__c, OwnerId FROM Case];
        List<Case> vehicleCases = Select.Field.notNull(Case.Vehicle_ID__c).filter(allCases);

        System.assertEquals(BULK_COUNT, vehicleCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, vehicleCases), 'each vehicle should get a case');

        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.UNAVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, allCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, allCases), 'each case should have the correct owner');
    }
    
    static testmethod void requestDriveIfAvailabilityChanges_NotSalePending() {
        
        BluewolfVehicleTriggerHandler.bypassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .put(Vehicle__c.On_Deposit__c, false)
            .put(Vehicle__c.Going_To_Auction__c, false)
            .put(Vehicle__c.Hold_For_Financing__c, true)
            .put(Vehicle__c.Hold_For_Trade_In__c, false)
            .put(Vehicle__c.Needs_Repairs__c, false)
            .put(Vehicle__c.In_Transit__c, false)
            .put(Vehicle__c.Paperwork_Missing__c, 'Yes - Vehicle Available')
            .put(Vehicle__c.Photos_Ready__c, true)
            .count(BULK_COUNT).create().getRecords();

        List<Opportunity> testOpportunities = BluewolfSObjectFactory.create(BULK_COUNT, Opportunity.sObjectType);

        Map<Id, Vehicle__c> oldVehicles = new Map<Id, Vehicle__c>(testVehicles.deepClone(true/*preserve Ids*/));
        for (Vehicle__c vehicle : oldVehicles.values()) {
            vehicle.recalculateFormulas();
        }

        for (Vehicle__c vehicle : testVehicles) {
            vehicle.Hold_For_Financing__c = false;
        }

        update testVehicles;
        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;
        BluewolfVehicleTriggerHandler.bypassTrigger = false;
        Test.startTest();
            BluewolfTestDriveRequestServices.requestDriveIfAvailabilityChanges(testVehicles, oldVehicles);
        Test.stopTest();

        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, actualCases), 'each vehicle should get a case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.AVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }
    
    static testmethod void requestDriveIfSoldOrReturned_Unavailable_Trigger_Insert() {
        BluewolfVehicleTriggerHandler.bypassTrigger = true;
        BluewolfVehicleOrderTriggerHandler.bypassTrigger = true;
        List<Vehicle__c> testVehicles = new BluewolfSObjectBuilder(Vehicle__c.sObjectType)
            .count(BULK_COUNT).create().getRecords();

        List<Vehicle_Order__c> testOrders = new BluewolfSObjectBuilder(Vehicle_Order__c.sObjectType)
            .put(Vehicle_Order__c.Vehicle_ID__c, BluewolfSObjectFactory.provideParents(testVehicles))
            .count(BULK_COUNT).build().getRecords();

        for (Vehicle_Order__c order : testOrders) {
            order.Deposit_Accepted_On__c = Date.today();
        }

        User testUser = (User)BluewolfSObjectFactory.create(User.sObjectType);
        BluewolfTestDriveRequestServices.caseOwnerId = testUser.Id;

        BluewolfVehicleOrderTriggerHandler.bypassTrigger = false;
        Test.startTest();
            insert testOrders;
        Test.stopTest();
        BluewolfVehicleTriggerHandler.bypassTrigger = false;
        List<Case> actualCases = [SELECT Vehicle_ID__c, Case_Type__c, OwnerId FROM Case];
        System.assertEquals(BULK_COUNT, actualCases.size(), 'each vehicle should get a case');
        System.assertEquals(BluewolfPluck.Ids(testVehicles), BluewolfPluck.Ids(Case.Vehicle_ID__c, actualCases), 'each vehicle should get a case');
        System.assertEquals(new Set<String> { BluewolfTestDriveRequestServices.UNAVAILABLE_TYPE }, BluewolfPluck.Strings(Case.Case_Type__c, actualCases), 'the cases should be the correct type');
        System.assertEquals(new Set<Id> { testUser.Id }, BluewolfPluck.Ids(Case.OwnerId, actualCases), 'each case should have the correct owner');
    }    
   
}