objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BluewolfDefaultEmailActionTest.cls
@isTest
private class BluewolfDefaultEmailActionTest {
    static testMethod void onInitDefaults_noSellerOpportunity() {
        Case aCase = (Case) new BluewolfSObjectBuilder(Case.SobjectType).create().getRecord();
        String defaultsAsJSON = '[{"targetSObject":{"attributes":{"type":"EmailMessage"},"TextBody":"",'
        + '"FromName":"Test","FromAddress":"test@example.com","HtmlBody":"<html><body></body></html>","BccAddress":"test@example.com",'
        + '"CcAddress":"","ToAddress":"test@example.com","Subject":"Testing"},"contextId": "' + String.valueOf(aCase.Id) + '","actionType":"Email",'
        + '"actionName":"Case.Email","fromAddressList":["salesforce@test.com"]}]';
        List<QuickAction.SendEmailQuickActionDefaults> defaultsSettings =
            (List<QuickAction.SendEmailQuickActionDefaults>)JSON.deserialize(defaultsAsJSON, List<QuickAction.SendEmailQuickActionDefaults>.class);

        Test.startTest();
            new BluewolfDefaultEmailAction().onInitDefaults(defaultsSettings);
        Test.stopTest();

        EmailMessage actualEmail = (EmailMessage)defaultsSettings[0].getTargetSObject();
        system.assertEquals(Label.Case_From_Email, actualEmail.FromAddress, 'the from address should be set');
    }
    
    static testMethod void onInitDefaults_sellerOpportunity(){
        Id recordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Seller'].Id;
        Vehicle__c veh = (Vehicle__c) new BluewolfSObjectBuilder(Vehicle__c.SobjectType).create().getRecord();
        Opportunity opp = (Opportunity) new BluewolfSObjectBuilder(Opportunity.SobjectType)
                                                    .put(Opportunity.RecordTypeId, recordTypeId)
                                                    .put(Opportunity.Vehicle_Id__c, veh.Id)
                                                    .create().getRecord();
        
        Case aCase = (Case) new BluewolfSObjectBuilder(Case.SobjectType)
                                .put(Case.Opportunity_Id__c, opp.Id).create().getRecord();
                                
        String defaultsAsJSON = '[{"targetSObject":{"attributes":{"type":"EmailMessage"},"TextBody":"",'
        + '"FromName":"Test","FromAddress":"test@example.com","HtmlBody":"<html><body></body></html>","BccAddress":"test@example.com",'
        + '"CcAddress":"","ToAddress":"test@example.com","Subject":"Testing"},"contextId": "' + String.valueOf(aCase.Id) + '","actionType":"Email",'
        + '"actionName":"Case.Email","fromAddressList":["salesforce@test.com"]}]';
        List<QuickAction.SendEmailQuickActionDefaults> defaultsSettings =
            (List<QuickAction.SendEmailQuickActionDefaults>)JSON.deserialize(defaultsAsJSON, List<QuickAction.SendEmailQuickActionDefaults>.class);

        Test.startTest();
            new BluewolfDefaultEmailAction().onInitDefaults(defaultsSettings);
        Test.stopTest();

        EmailMessage actualEmail = (EmailMessage)defaultsSettings[0].getTargetSObject();
        system.assertEquals(Label.Seller_Case_Email, actualEmail.FromAddress, 'the from address should be set');                                          
    }
}