objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BluewolfDefaultEmailAction.cls
global class BluewolfDefaultEmailAction implements QuickAction.QuickActionDefaultsHandler {

    @TestVisible
    static final String SELLER_OPP = 'Seller';
    static final Set<String> SELLER_EMAIL_TYPE = new Set<String>{'8x8 Voicemail', 'Tesla Email', 'General Email', 'Automated Pickup Request', 'Pricing Update', 'Response to Drip Campaign'}; 
    
    global void onInitDefaults(List<QuickAction.QuickActionDefaults> defaults) {
        QuickAction.SendEmailQuickActionDefaults sendEmailDefaults = getCaseEmailAction(defaults);

        if(sendEmailDefaults == null) return;
        EmailMessage emailMessage = (EmailMessage)sendEmailDefaults.getTargetSObject();
        
        Id caseId = (Id) sendEmailDefaults.getContextId();
        system.debug(caseId);
        Case aCase;
        if(caseId != null)
            aCase = [SELECT Case_Type__c, Opportunity_ID__c, Opportunity_Id__r.RecordType.DeveloperName FROM Case WHERE Id =:caseId];
        if(aCase != null && aCase.Opportunity_Id__r.RecordType.DeveloperName == SELLER_OPP){
            emailMessage.FromAddress = Label.Seller_Case_Email;
        }
        else if(SELLER_EMAIL_TYPE.contains(aCase.Case_Type__c)){
            emailMessage.FromAddress = Label.Seller_Case_Email;
        }
        else{
            emailMessage.FromAddress = Label.Case_From_Email;
        } 
    }

    QuickAction.SendEmailQuickActionDefaults getCaseEmailAction(List<QuickAction.QuickActionDefaults> defaults) {
        for (QuickAction.QuickActionDefaults d : defaults) {
            if(d instanceof QuickAction.SendEmailQuickActionDefaults
                && d.getTargetSObject().getSObjectType() == EmailMessage.sObjectType
                && d.getActionName().equals('Case.Email')
                && d.getActionType().equals('Email')) {

                return (QuickAction.SendEmailQuickActionDefaults)d;
            }
        }

        return null;
    }
}