objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Evaluation__c.object
<CustomObject>
    <description>Represents an evaluation of a seller vehicle.</description>
    <fields>
        <fullName>Canceled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Canceled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluated_At__c</fullName>
        <label>Evaluated At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <label>Seller Opportunity ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a Seller Opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a seller opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BluewolfEvaluationServiceTest.cls
@isTest
private class BluewolfEvaluationServiceTest {
    
    private final static Id SELLER_OPP_ID = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Seller'].Id;
    
    static testMethod void testAfterInsert(){
        BluewolfOpportunityTriggerHandler.bypassTrigger = true;
        BluewolfEvaluationTriggerHandler.bypassTrigger = true;
        Vehicle__c vehicle = (Vehicle__c) new BluewolfSObjectBuilder(Vehicle__c.SObjectType).create().getRecord();
        Opportunity opp = (Opportunity) new BluewolfSObjectBuilder(Opportunity.SObjectType)
                                            .put(Opportunity.RecordTypeId, SELLER_OPP_ID)
                                            .put(Opportunity.Vehicle_Id__c, vehicle.Id)
                                            .create().getRecord();
        Evaluation__c testEva = (Evaluation__c) new BluewolfSObjectBuilder(Evaluation__c.SObjectType)
                                                .put(Evaluation__c.Seller_Opportunity_ID__c, opp.Id)
                                                .put(Evaluation__c.Evaluated_At__c, Datetime.now().addDays(1))
                                                .put(Evaluation__c.Canceled__c, false)
                                                .create().getRecord();
                                                
        BluewolfOpportunityTriggerHandler.bypassTrigger = false;
        BluewolfEvaluationTriggerHandler.bypassTrigger = false;
        
        Test.startTest();
            BluewolfEvaluationService.afterInsert(new List<Evaluation__c>{testEva});
        Test.stopTest();
        
        List<Case> cases = [SELECT Case_Type__c, Opportunity_ID__c FROM Case];
        
        system.assertEquals(1, cases.size(), 'the case size should be equal');
        system.assertEquals(BluewolfEvaluationService.CASE_TYPE, cases[0].Case_Type__c, 'the case size should be equal');
        system.assertEquals(opp.Id, cases[0].Opportunity_ID__c, 'the case size should be equal');
    }
    
    static testMethod void testAfterInsert_trigger(){
        BluewolfOpportunityTriggerHandler.bypassTrigger = true;
        BluewolfEvaluationTriggerHandler.bypassTrigger = true;
        Vehicle__c vehicle = (Vehicle__c) new BluewolfSObjectBuilder(Vehicle__c.SObjectType).create().getRecord();
        Opportunity opp = (Opportunity) new BluewolfSObjectBuilder(Opportunity.SObjectType)
                                            .put(Opportunity.RecordTypeId, SELLER_OPP_ID)
                                            .put(Opportunity.Vehicle_Id__c, vehicle.Id)
                                            .create().getRecord();
        Evaluation__c testEva = (Evaluation__c) new BluewolfSObjectBuilder(Evaluation__c.SObjectType)
                                                .put(Evaluation__c.Seller_Opportunity_ID__c, opp.Id)
                                                .put(Evaluation__c.Evaluated_At__c, Datetime.now().addDays(1))
                                                .put(Evaluation__c.Canceled__c, false)
                                                .build().getRecord();
                                                
        BluewolfOpportunityTriggerHandler.bypassTrigger = false;
        BluewolfEvaluationTriggerHandler.bypassTrigger = false;
        
        Test.startTest();
            insert testEva;
        Test.stopTest();
        
        List<Case> cases = [SELECT Case_Type__c, Opportunity_ID__c FROM Case];
        
        system.assertEquals(1, cases.size(), 'the case size should be equal');
        system.assertEquals(BluewolfEvaluationService.CASE_TYPE, cases[0].Case_Type__c, 'the case size should be equal');
        system.assertEquals(opp.Id, cases[0].Opportunity_ID__c, 'the case size should be equal');
    }
    
    static testMethod void testAfterUpdate(){
        BluewolfOpportunityTriggerHandler.bypassTrigger = true;
        BluewolfEvaluationTriggerHandler.bypassTrigger = true;
        Vehicle__c vehicle = (Vehicle__c) new BluewolfSObjectBuilder(Vehicle__c.SObjectType).create().getRecord();
        Opportunity opp = (Opportunity) new BluewolfSObjectBuilder(Opportunity.SObjectType)
                                            .put(Opportunity.RecordTypeId, SELLER_OPP_ID)
                                            .put(Opportunity.Vehicle_Id__c, vehicle.Id)
                                            .create().getRecord();
        Case aCase = (Case) new BluewolfSObjectBuilder(Case.SObjectType)
                                .put(Case.Opportunity_Id__c, opp.Id)
                                .create().getRecord();
        Evaluation__c testEva = (Evaluation__c) new BluewolfSObjectBuilder(Evaluation__c.SObjectType)
                                                .put(Evaluation__c.Seller_Opportunity_ID__c, opp.Id)
                                                .put(Evaluation__c.Evaluated_At__c, Datetime.now().addDays(1))
                                                .put(Evaluation__c.Canceled__c, true)
                                                .create().getRecord();
                                                
        Map<Id, Evaluation__c> oldMap = new Map<Id, Evaluation__c>{testEva.Id => testEva};
        
        Evaluation__c newEva = testEva.clone(true, true, true ,true);
        newEva.Canceled__c = false;
        BluewolfOpportunityTriggerHandler.bypassTrigger = false;
        BluewolfEvaluationTriggerHandler.bypassTrigger = false;
        
        Test.startTest();
            BluewolfEvaluationService.afterUpdate(new List<Evaluation__c>{newEva}, oldMap);
        Test.stopTest();
        
        List<Case> cases = [SELECT Case_Type__c, Opportunity_ID__c FROM Case];
        
        system.assertEquals(1, cases.size(), 'the case size should be equal');
        system.assertEquals(BluewolfEvaluationService.CASE_TYPE, cases[0].Case_Type__c, 'the case size should be equal');
        system.assertEquals(opp.Id, cases[0].Opportunity_ID__c, 'the case size should be equal');
    }
    
    static testMethod void testAfterUpdate_trigger(){
        BluewolfOpportunityTriggerHandler.bypassTrigger = true;
        BluewolfEvaluationTriggerHandler.bypassTrigger = true;
        Vehicle__c vehicle = (Vehicle__c) new BluewolfSObjectBuilder(Vehicle__c.SObjectType).create().getRecord();
        Opportunity opp = (Opportunity) new BluewolfSObjectBuilder(Opportunity.SObjectType)
                                            .put(Opportunity.RecordTypeId, SELLER_OPP_ID)
                                            .put(Opportunity.Vehicle_Id__c, vehicle.Id)
                                            .create().getRecord();
        Case aCase = (Case) new BluewolfSObjectBuilder(Case.SObjectType)
                                .put(Case.Opportunity_Id__c, opp.Id)
                                .create().getRecord();
        Evaluation__c testEva = (Evaluation__c) new BluewolfSObjectBuilder(Evaluation__c.SObjectType)
                                                .put(Evaluation__c.Seller_Opportunity_ID__c, opp.Id)
                                                .put(Evaluation__c.Evaluated_At__c, Datetime.now().addDays(1))
                                                .put(Evaluation__c.Canceled__c, true)
                                                .create().getRecord();
                                                
        Evaluation__c newEva = testEva.clone(true, true, true ,true);
        newEva.Canceled__c = false;
        BluewolfOpportunityTriggerHandler.bypassTrigger = false;
        BluewolfEvaluationTriggerHandler.bypassTrigger = false;
        
        Test.startTest();
            update newEva;
        Test.stopTest();
        
        List<Case> cases = [SELECT Case_Type__c, Opportunity_ID__c FROM Case];
        
        system.assertEquals(1, cases.size(), 'the case size should be equal');
        system.assertEquals(BluewolfEvaluationService.CASE_TYPE, cases[0].Case_Type__c, 'the case size should be equal');
        system.assertEquals(opp.Id, cases[0].Opportunity_ID__c, 'the case size should be equal');
    }
}