objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Experience_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Experience Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ShiftCasesTest.cls
@IsTest
class ShiftCasesTest {
	@TestSetup static void setup() { ShiftTesting.setup(); }

	static ShiftTesting.BuyerTestContext setupOpportunity() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.prepareBuyerTestContext();
		ctx.opportunity.StageName = ShiftConstants.BUYER_OPPORTUNITY_STAGE_LEADS;
		insert ctx.opportunity;
		return ctx;
	}

	static ShiftTesting.BuyerTestContext setupOpportunityWithCustomerExperienceRepresentative(User customerExperienceRepresentative) {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.prepareBuyerTestContext();
		ctx.opportunity.StageName = ShiftConstants.BUYER_OPPORTUNITY_STAGE_LEADS;
		ctx.opportunity.Customer_Experience_Representative__c = customerExperienceRepresentative.Id;
		insert ctx.opportunity;
		return ctx;
	}

	static Case setupCase(Id opportunityId, Id caseOwnerId, String caseType) {
		Case c = new Case(
			OwnerId = caseOwnerId,
			Opportunity_ID__c = opportunityId,
			Case_Type__c = caseType
		);
		insert c;
		return c;
	}

	static void expectCustomerExperienceRepresentativeForCaseType (String caseType, User u, Id expectedUserId) {
		ShiftTesting.BuyerTestContext ctx = setupOpportunity();
		Case c = setupCase(ctx.opportunity.Id, ShiftUsers.unownedUserId(), caseType);
		c.OwnerId = u.id;
		update c;

		ShiftTesting.expectOpportunityCustomerExperienceRepresentatitve(ctx.opportunity.Id, expectedUserId);
	}

	static void expectCustomerExperienceRepresentativeForInvalidCaseType (String caseType) {
		User u1 = ShiftTesting.insertTestUser();
		expectCustomerExperienceRepresentativeForCaseType(caseType, u1, null);
	}

	static void expectCustomerExperienceRepresentativeForValidCaseType(String caseType) {
		User u1 = ShiftTesting.insertTestUser();
		expectCustomerExperienceRepresentativeForCaseType(caseType, u1, u1.id);
	}

	static Case setupDefaultCase(Id opportunityId, Id caseOwnerId) {
		return setupCase(opportunityId, caseOwnerId, ShiftConstants.CASE_TYPE_SHIFT_TEST_DRIVE_REQUEST);
	}

	@IsTest
	static void testNewCaseWithUnownedUserAndExisitngRepIsNull() {
		ShiftTesting.BuyerTestContext ctx = setupOpportunity();
		Case c = setupDefaultCase(ctx.opportunity.Id, ShiftUsers.unownedUserId());
		ShiftTesting.expectOpportunityCustomerExperienceRepresentatitve(ctx.opportunity.Id, null);
	}

	@IsTest
	static void testNewCaseWithKnownUserAndExistingRepIsNull() {
		ShiftTesting.BuyerTestContext ctx = setupOpportunity();
		User u = ShiftTesting.insertTestUser();
		Case c = setupDefaultCase(ctx.opportunity.Id, u.Id);
		ShiftTesting.expectOpportunityCustomerExperienceRepresentatitve(ctx.opportunity.Id, u.Id);
	}

	@IsTest
	static void testNewCaseWithKnownUserAndExistingRepIsNotNull() {
		User u1 = ShiftTesting.insertTestUser();
		ShiftTesting.BuyerTestContext ctx = setupOpportunityWithCustomerExperienceRepresentative(u1);
		Case c = setupDefaultCase(ctx.opportunity.Id, ShiftTesting.insertTestUser().Id);
		ShiftTesting.expectOpportunityCustomerExperienceRepresentatitve(ctx.opportunity.Id, u1.Id);
	}

	@IsTest
	static void testUpdateCaseFromUnknownUserToKnownAndExistingRepIsNull() {
		ShiftTesting.BuyerTestContext ctx = setupOpportunity();
		Case c = setupDefaultCase(ctx.opportunity.Id, ShiftUsers.unownedUserId());
		User u = ShiftTesting.insertTestUser();
		c.OwnerId = u.id;
		update c;

		ShiftTesting.expectOpportunityCustomerExperienceRepresentatitve(ctx.opportunity.Id, u.Id);
	}

	@IsTest
	static void testUpdateCaseFromUnknownUserToKnownAndExistingRepIsNotNull() {
		User u1 = ShiftTesting.insertTestUser();
		ShiftTesting.BuyerTestContext ctx = setupOpportunityWithCustomerExperienceRepresentative(u1);
		Case c = setupDefaultCase(ctx.opportunity.Id, ShiftUsers.unownedUserId());
		c.OwnerId = ShiftTesting.insertTestUser().id;
		update c;

		ShiftTesting.expectOpportunityCustomerExperienceRepresentatitve(ctx.opportunity.Id, u1.Id);
	}

	@IsTest
	static void testUpdateCaseFromKnownUserToKnownAndExistingRepIsNotNull() {
		ShiftTesting.BuyerTestContext ctx = setupOpportunity();
		User u1 = ShiftTesting.insertTestUser();
		Case c = setupDefaultCase(ctx.opportunity.Id, u1.Id);
		c.OwnerId = ShiftTesting.insertTestUser().id;
		update c;

		ShiftTesting.expectOpportunityCustomerExperienceRepresentatitve(ctx.opportunity.Id, u1.Id);
	}

	@IsTest
	static void testShiftTestDriveRequestRejectedCaseType() {
		expectCustomerExperienceRepresentativeForValidCaseType(ShiftConstants.CASE_TYPE_SHIFT_TEST_DRIVE_REQUEST_REJECTED);
	}

	@IsTest
	static void testShiftVehicleQuestionCaseType() {
		expectCustomerExperienceRepresentativeForValidCaseType(ShiftConstants.CASE_TYPE_SHIFT_VEHICLE_QUESTION);	
	}

	@IsTest
	static void testThirdPartyListingSiteVehicleQuestionCaseType() {
		expectCustomerExperienceRepresentativeForValidCaseType(ShiftConstants.CASE_TYPE_THIRD_PARTY_LISTING_SITE_VEHICLE_QUESTION);	
	}

	@IsTest
	static void testAutomatedPickupRequestCaseType() {
		expectCustomerExperienceRepresentativeForInvalidCaseType(ShiftConstants.CASE_TYPE_AUTOMATED_PICKUP_REQUEST);
	}

	@IsTest
	static void testCraigslistFollowUpCaseType() {
		expectCustomerExperienceRepresentativeForInvalidCaseType(ShiftConstants.CASE_TYPE_CRAIGSLIST_FOLLOW_UP);
	}
}