objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle Order</label>
        <referenceTo>Vehicle_Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Vehicle_Order__c.object
<CustomObject>
    <description>Orders represent the process of a Buyer purchasing a Vehicle. Note that we don&apos;t name this object simple &quot;Order&quot; so as to avoid confusion with the standard salesforce Order object. We may one day decide to use that object instead, but not until we understand more about whether it fits with our model.</description>
    <fields>
        <fullName>Buyer_Opportunity_ID__c</fullName>
        <label>Buyer Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Buyer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Returned_Notes__c</fullName>
        <label>Returned Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BluewolfRequestContExt.cls
public without sharing class BluewolfRequestContExt{
    @TestVisible
    private static final String PICKUP_REQUEST_TYPE = 'Temporary Return';
    @TestVisible
    private static final String RETURN_REQUEST_TYPE = 'Permanent Return';
    @TestVisible
    private static final User ASSIGNED_USER = [SELECT Id FROM User WHERE Shift_Key__c = 'unowned'];
    
    public Vehicle_Order__c vehicleOrder {get; set;}
    private Contact contact {get; set;}
    
    public BluewolfRequestContExt(ApexPages.StandardController ctrl){
        vehicleOrder = [SELECT Buyer_Opportunity_ID__c, Buyer_Opportunity_ID__r.AccountId, Returned_Notes__c FROM Vehicle_Order__c WHERE Id =: ctrl.getRecord().Id];
        contact = [SELECT Id FROM Contact WHERE AccountId = :vehicleOrder.Buyer_Opportunity_ID__r.AccountId LIMIT 1];
    }
    
    public PageReference createPickupRequest(){
        return createNewCase(PICKUP_REQUEST_TYPE);
    }
    
    public PageReference createReturnRequest(){
        return createNewCase(RETURN_REQUEST_TYPE );
    }
    
    @TestVisible
    private PageReference createNewCase(String type){
        if(ASSIGNED_USER == null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unowned User not existed, please contact System Administrator'));
        }
        Case newCase = new Case(
                                 Opportunity_ID__c = vehicleOrder.Buyer_Opportunity_ID__c,
                                 Case_Type__c = type,
                                 Description = 'Returned Notes: ' + vehicleOrder.Returned_Notes__c,
                                 OwnerId = ASSIGNED_USER.Id,
                                 contactId = contact.Id
                               );
        
        try{
            insert newCase;
        }
        catch(DMLException ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getStackTraceString()));
        }
        
        PageReference oldPage = new ApexPages.StandardController(vehicleOrder).view();
        oldPage.setRedirect(true);
        return oldPage;

    }
}