objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>8x8 Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automated Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Pickup Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Enthusiast Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Inbound Seller Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Drip Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Test Drive Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>shift.com Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tesla Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Listing Site Vehicle Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Available - Schedule Test Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Unavailable - Cancel Test Drives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/CaseTypePriority__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>CaseType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>CaseTypePriority</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>In_Transit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Transit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Repairs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs Repairs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paperwork_Missing__c</fullName>
        <label>Paperwork Missing</label>
        <picklist>
            <picklistValues>
                <fullName>Yes - More Than 7 Days Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes - Less Than 7 Days Unavailable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes - Available Without Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Photos_Ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Photos Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a seller opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BluewolfOpportunityService.cls
public with sharing class BluewolfOpportunityService {

    @testVisible private static String CASE_OWNER_NAME = 'unowned';
    @testVisible private static String AVAILABLE_TYPE = 'Vehicle Available - Schedule Test Drives';
    @testVisible private static String UNAVAILABLE_TYPE = 'Vehicle Unavailable - Cancel Test Drives';
    @testVisible private static String AVAILABLE_STAGE = 'Prepare Car for Sale';
    @testVisible private static Id SELLER_OPP_ID{
        get{
            if(SELLER_OPP_ID == null){
                SELLER_OPP_ID = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Seller'].Id;
            }
            return SELLER_OPP_ID;
        }
        private set;
    }
    @testVisible
    private static Id caseOwnerId {
        get {
            if (caseOwnerId == null) {
                caseOwnerId = [SELECT Id FROM User WHERE Shift_Key__c = :CASE_OWNER_NAME].Id;
            }
            return caseOwnerId;
        }
        private set;
    }
    @TestVisible
    private final static String CRAIGSLIST = 'Craigslist';
    @TestVisible
    private static final User ASSIGNED_USER = [SELECT Id FROM User WHERE Shift_Key__c = 'unowned'];
    @TestVisible
    private static final String CASE_TYPE = 'New Inbound Seller Opportunity';
    private static final Set<String> VALID_STAGES = new Set<String>{'Leads', 'Quote and Schedule'};
    private static Map<Id, List<Vehicle__c>> oppToVehicleMap;
    private static Map<Id, Id> oppToContactMap;
    private static List<CaseTypePriority__c> priorityMap {
        get{
            if(priorityMap == null){
                priorityMap = CaseTypePriority__c.getAll().values();
            }
            return priorityMap;
        }
        private set;
    } 
    private static Select.Filter validStage(){
        return Select.Field.isIn(Opportunity.StageName, VALID_STAGES);
    }
    private static Select.Filter stageChanged(){
        return Select.Field.hasChanged(Opportunity.StageName);
    }
    private static Select.Filter isSellerOpportunity(){
        return Select.Field.isEqual(Opportunity.RecordTypeId, SELLER_OPP_ID);
    }
    
    private static Select.Filter recordTypeChanged(){
        return Select.Field.hasChanged(Opportunity.RecordTypeId);
    }
    
    private static Select.Filter isNotFromCraigsList(){
        return Select.Field.notEqual(Opportunity.LeadSource, CRAIGSLIST);
    }
    
    private static Select.Filter leadSourceChanged(){
        return Select.Field.hasChanged(Opportunity.LeadSource);
    }
    
    public static void afterInsert(List<Opportunity> records){
        List<Opportunity> filteredRecords = validStage().andx(isSellerOpportunity()).andx(isNotFromCraigsList()).filter(records);
        createCases(filteredRecords);
    }
    
    public static void afterUpdate(List<Opportunity> records, Map<Id, Opportunity> oldMap){
        List<Opportunity> filteredRecords = stageChanged().orx(recordTypeChanged()).orx(leadSourceChanged()).andx(validStage()).andx(isSellerOpportunity().andx(isNotFromCraigsList())).filter(records, oldMap);
        Map<Id, List<Case>> resultMap = getOppToCaseMap(filteredRecords);
        upsertCases(resultMap, filteredRecords);
    }
    private static void upsertCases(Map<Id, List<Case>> oppIdToCaseMap, List<Opportunity> filteredRecords){
        BluewolfDMLBox insertDMLBox = new BluewolfDMLBox();
        BluewolfDMLBox updateDMLBox = new BluewolfDMLBox();
        
        List<Case> updateCases = new List<Case>();
        List<Case> insertCases = new List<Case>();
        for(Id oppId : oppIdToCaseMap.keySet()){
            List<Case> cases = oppIdToCaseMap.get(oppId);
            if(cases != null && !cases.isEmpty()){
               for(Case aCase: cases){
                   aCase.Case_Type__c = CASE_TYPE;
               }
               updateCases.addAll(cases);
            }
            else{
                insertCases.add(new Case(Opportunity_ID__c = oppId, Case_Type__c = CASE_TYPE));
            }
        }
        
        insertDMLBox.add(insertCases, filteredRecords);
        updateDMLBox.add(updateCases, filteredRecords);
        
        insertDMLBox.safeInsert();
        updateDMLBox.safeUpdate();
    }
    
    private static Map<Id, List<Case>> getOppToCaseMap(List<Opportunity> opps){
        Map<Id, List<Case>> resultMap = new  Map<Id, List<Case>>();
        
        Set<Id> oppIds = Pluck.ids(opps);
        
        resultMap = GroupBy.ids('Opportunity_ID__c', [SELECT Opportunity_ID__c, Case_Type__c FROM Case WHERE Opportunity_ID__c =:oppIds AND Case_Type__c != :getAvailableStatus('Opportunity')]);
        
        for(Id oppId : oppIds){
            if(!resultMap.containsKey(oppId)) resultMap.put(oppId, new List<Case>());
        }
        
        return resultMap;
    }
    
    private static Set<String> getAvailableStatus(String objectName){
        Set<String> results = new Set<String>();
        
        Decimal minPriority = 1000000;
        Decimal maxPriority = 0;
        
        for(CaseTypePriority__c value: priorityMap){
            if(value.ObjectName__c == objectName){
                if(value.Priority__c > maxPriority) maxPriority = value.Priority__c;
                if(value.Priority__c < minPriority) minPriority = value.Priority__c;
            }
        }
        
        if(maxPriority >= minPriority){
            for(CaseTypePriority__c value: priorityMap){
                if(value.Priority__c <= minPriority){
                    results.add(value.CaseType__c);
                }
            }
        }
        return results;
    }
    
    @TestVisible
    private static void createCases(List<Opportunity> opps){
        BluewolfDMLBox dmlBox = new BluewolfDMLBox();
        List<Case> newCases = new List<Case>();
        if(oppToContactMap == null) oppToContactMap = getOppToContactIdMap(opps);
        for(Opportunity opp: opps){
            Case newCase = new Case(Opportunity_Id__c = opp.Id,
                                    Case_Type__c = CASE_TYPE,
                                    AccountId = opp.AccountId,
                                    ContactId = oppToContactMap.get(opp.Id),
                                    OwnerId = ASSIGNED_USER.Id);
            newCases.add(newCase);
        }
        
        dmlBox.add(newCases, opps);
        dmlBox.safeInsert();
    }
    public static void beforeUpdate(List<Opportunity> opps, Map<Id, Opportunity> oldMap){
        
        BluewolfDMLBox dmlBox = new BluewolfDMLBox();
        List<Opportunity> filteredOpps = stageChanged().filter(opps, oldMap);
        if(oppToVehicleMap == null) oppToVehicleMap = getVehicleMap(filteredOpps);
        List<Case> createdCases = new List<Case>();
        
        for(Opportunity opp: filteredOpps){
            List<Vehicle__c> vehicles = oppToVehicleMap.get(opp.Id);
            if(vehicles == null || vehicles.isEmpty()) continue;
            
            Vehicle__c vehicle = vehicles[0];
            
            if(opp.StageName == AVAILABLE_STAGE && !getComingSoon(vehicle)){
                createdCases.add(new Case(
                    OwnerId = caseOwnerId,
                    Vehicle_ID__c = vehicle.Id,
                    Case_Type__c = UNAVAILABLE_TYPE
                ));
            }
            else if(oldMap.get(opp.Id).stageName == AVAILABLE_STAGE && !getComingSoon(vehicle)){
                createdCases.add(new Case(
                    OwnerId = caseOwnerId,
                    Vehicle_ID__c = vehicle.Id,
                    Case_Type__c = AVAILABLE_TYPE
                ));
            }
        }
        
        dmlBox.add(createdCases, filteredOpps);
        dmlBox.safeInsert();
    }
    
    private static Map<Id, List<Vehicle__c>> getVehicleMap(List<Opportunity> opps){
        
        Map<Id, List<Vehicle__c>> resultMap = new Map<Id, List<Vehicle__c>>();
        
        resultMap = GroupBy.ids('Seller_Opportunity_ID__c', [SELECT Seller_Opportunity_Id__r.StageName, Seller_Opportunity_ID__c, Needs_Repairs__c, In_Transit__c, Paperwork_Missing__c, Photos_Ready__c, Id FROM Vehicle__c WHERE Seller_Opportunity_ID__c =:opps]);
        
        return resultMap;
    }
    
    private static Map<Id, Id> getOppToContactIdMap(List<Opportunity> opps){
        Map<Id, Id> resultMap = new Map<Id, Id>();
        
        List<Contact> contacts = [SELECT Id, AccountId FROM Contact WHERE AccountId = :Pluck.ids('AccountId', opps)];
        for(Opportunity opp: opps){
            for(Contact contact: contacts){
                if(opp.AccountId == contact.AccountId){
                    resultMap.put(opp.Id, contact.Id);
                    break;
                }
            } 
        }
        
        return resultMap;    
    }
    
    private static Boolean getComingSoon(Vehicle__c vehicle){
        Boolean result = vehicle.Needs_Repairs__c || vehicle.In_Transit__c || vehicle.Paperwork_Missing__c ==  'Yes - Less Than 7 Days Unavailable' || vehicle.Paperwork_Missing__c == 'Yes - More Than 7 Days Unavailable' || !vehicle.Photos_Ready__c;
        return result;
    }
}