objects/Delivery__c.object
<CustomObject>
    <fields>
        <fullName>Canceled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Canceled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Is there anything else that the DOS needs to do? (i.e. Does anyone need to sign the 262 besides the buyer?)</inlineHelpText>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Details__c</fullName>
        <inlineHelpText>What should the DOS know about the sale? (i.e. Customer will be paying with First Tech loan and cashier&apos;s check. Customer will have a $5,000 cashier&apos;s check ready. We should be receiving the First Tech check tomorrow.) If redelivery, type &quot;Redelivery&quot;.</inlineHelpText>
        <label>Payment Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <inlineHelpText>Please include final sale price, tax and registration and total cost. Also include how the customer is paying for the vehicle. (i.e. First Tech loan of $8,000 and cashier&apos;s check of $5,000 minus Square deposit of $500.) If redelivery, type &quot;Redelivery&quot;.</inlineHelpText>
        <label>Payment Method</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/skedDeliveryHandler.cls
public class skedDeliveryHandler {

    public static void afterDeliverysInsert(List<Delivery__c> newDeliverys) {
        string recordIds = '';
        
        for (Delivery__c delivery : newDeliverys) {
            recordIds += delivery.Id + ';';
        }
        if (recordIds.length() > 0) {
            recordIds = recordIds.substring(0, recordIds.length() - 1);
            skedLocationService.updateGeoLocation(recordIds, 'delivery');
        }
    }
    
    public static void afterDeliverysUpdate(Map<Id, Delivery__c> oldDeliverys, List<Delivery__c> newDeliverys) {
        string recordIds = '';
        Map<Id, Delivery__c> mapDeliveryToCancelJobs = new Map<Id, Delivery__c>();
        Map<Id, Delivery__c> mapDeliveryToUpdateJobFields = new Map<Id, Delivery__c>();
        
        for (Delivery__c delivery : newDeliverys) {
            Delivery__c oldData = oldDeliverys.get(delivery.Id);
            if (delivery.Location__c != oldData.Location__c 
                && delivery.GeoLocation__Latitude__s == oldData.GeoLocation__Latitude__s 
                && delivery.GeoLocation__Longitude__s == oldData.GeoLocation__Longitude__s) {
                    recordIds += delivery.Id + ';';
                }
            if (delivery.Canceled__c && delivery.Canceled__c != oldData.Canceled__c) {
                mapDeliveryToCancelJobs.put(delivery.Id, delivery);
            }
            if (delivery.Notes__c != oldData.Notes__c || delivery.Payment_Details__c != oldData.Payment_Details__c
                || delivery.Payment_Method__c != oldData.Payment_Method__c) {
                mapDeliveryToUpdateJobFields.put(delivery.Id, delivery);
            }
        }
        if (mapDeliveryToCancelJobs.size() > 0) {
            skedTriggerUtils.CancelRelatedJobs(mapDeliveryToCancelJobs);
        }
        if (mapDeliveryToUpdateJobFields.size() > 0) {
            UpdateJobFields(mapDeliveryToUpdateJobFields);
        }
        if (recordIds.length() > 0) {
            recordIds = recordIds.substring(0, recordIds.length() - 1);
            skedLocationService.updateGeoLocation(recordIds, 'delivery');
        }
    }
    
    
    public static void UpdateJobFields(Map<Id, Delivery__c> mapDeliveries) {
        List<sked__Job__c> relatedJobs = [SELECT Id, Shift_Notes__c, Delivery__c, Payment_Details__c, Payment_Method__c
                                          FROM sked__Job__c
                                          WHERE Delivery__c IN :mapDeliveries.keySet()
                                          AND sked__Job_Status__c != :SkeduloConstants.JOB_STATUS_CANCELLED];
        for (sked__Job__c job : relatedJobs) {
            Delivery__c delivery = mapDeliveries.get(job.Delivery__c);
            job.Shift_Notes__c = delivery.Notes__c;
            job.Payment_Details__c = delivery.Payment_Details__c;
            job.Payment_Method__c = delivery.Payment_Method__c;
        }
        update relatedJobs;
    }
    
}