objects/Evaluation__c.object
<CustomObject>
    <description>Represents an evaluation of a seller vehicle.</description>
    <fields>
        <fullName>Canceled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Canceled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluated_At__c</fullName>
        <label>Evaluated At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Evaluated_By_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Migration_Tree_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Migration Tree ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Next_Steps_After_Evaluation__c</fullName>
        <inlineHelpText>- How did the evaluation go?
- Are there any outstanding questions and issues?
- What are the next steps? By who? When?</inlineHelpText>
        <label>Next Steps After Evaluation</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scheduled_By_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scheduled By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Evaluations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShiftBatchRemoveEmptyEvaluations.cls
// Removes empty evaluations incorrectly created as part of the migration
// (https://shift.phacility.com/T1396).
public class ShiftBatchRemoveEmptyEvaluations implements Database.Batchable<Evaluation__c> {
	
	public Iterable<Evaluation__c> start(Database.BatchableContext bc) {
		return (Iterable<Evaluation__c>) Database.getQueryLocator([
			SELECT Id, Next_Steps_After_Evaluation__c
			FROM Evaluation__c
			WHERE 
				Canceled__c != TRUE AND
				Evaluated_At__c = NULL AND
				Evaluated_By_ID__c = NULL AND 
				Location__c = NULL AND 
				Migration_Tree_ID__c != NULL AND 
				Scheduled_By_ID__c = NULL
		]);
	}

	public void execute(Database.BatchableContext bc, List<Evaluation__c> evals) {
		List<Evaluation__c> toDel = new List<Evaluation__c>();
		for (Evaluation__c eval : evals) {
			if (eval.Next_Steps_After_Evaluation__c == null) {
				toDel.add(eval);
			}
		}
		delete toDel;
		// not checking/failing on errors from emptyRecycleBin() since they'll
		// be removed by salesforce if we can't for some reason. The delete()
		// call above is the critical one for correctness and will fail fast.
		Database.emptyRecycleBin(toDel); 
	}

	public void finish(Database.BatchableContext bc) {}
}