objects/Evaluation__c.object
<CustomObject>
    <description>Represents an evaluation of a seller vehicle.</description>
    <fields>
        <fullName>On_The_Spot_Pickup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox should be checked only if the vehicle was picked up during the eval.  (Waves the Pick-Up Fee.)</description>
        <inlineHelpText>This checkbox should be checked only if the vehicle was picked up during the eval.  (Waves the Pick-Up Fee.)</inlineHelpText>
        <label>On The Spot Pickup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seller_Drop_Off__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox should be checked if the vehicle is dropped off by the customer at the hub.  (Waives the Pick Up Fee.)</description>
        <inlineHelpText>This checkbox should be checked if the vehicle is dropped off by the customer at the hub.  (Waives the Pick Up Fee.)</inlineHelpText>
        <label>Seller Drop-Off</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <label>Seller Opportunity ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a Seller Opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Pickup_Fee__c</fullName>
        <defaultValue>100</defaultValue>
        <description>Pickup Fee defaults to $100 but can be reduced to $0 if &quot;On The Spot Pickup&quot; or &quot;Seller Drop-Off&quot; is checked in the Evaluation. Change this field directly to override. Credit is split with the seller for non-Flat Fee deals.</description>
        <inlineHelpText>Pickup Fee defaults to $100 but can be reduced to $0 if &quot;On The Spot Pickup&quot; or &quot;Seller Drop-Off&quot; is checked in the Evaluation. Change this field directly to override. Credit is split with the seller for non-Flat Fee deals.</inlineHelpText>
        <label>Pickup Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ShiftEvaluations.cls
public class ShiftEvaluations {
	@TestVisible static final String EVALUATION_CHECKBOXES_ERROR = 'Should not have both "On The Spot Pickup" and "Seller Drop Off" selected.';

	private static void validateEvaluation(List<Evaluation__c> evaluations) {
		for (Evaluation__c eval : evaluations) {
			 //Ensure that the evaluation doesn't have both On The Spot Pickup and Seller Drop-Off checked
			if (eval.On_The_Spot_Pickup__c && eval.Seller_Drop_Off__c) {
				eval.On_The_Spot_Pickup__c.addError(EVALUATION_CHECKBOXES_ERROR);
				eval.Seller_Drop_Off__c.addError(EVALUATION_CHECKBOXES_ERROR);
			}
		}
	}

	private static void updateSellerOpportunityPickupFee(List<Evaluation__c> evaluations) {
		Map<Id, Opportunity> opportunitiesToUpdate = new Map<Id, Opportunity>();

		for (Evaluation__c eval : evaluations) {
			Id sellerOpportunityId = eval.Seller_Opportunity_ID__c;
			if (eval.On_The_Spot_Pickup__c) {
				opportunitiesToUpdate.put(sellerOpportunityId, new Opportunity(Id = sellerOpportunityId, Pickup_Fee__c = ShiftConstants.SELLER_PICKUP_DURING_EVAL_FEE));
			} else if (eval.Seller_Drop_Off__c) {
				opportunitiesToUpdate.put(sellerOpportunityId, new Opportunity(Id = sellerOpportunityId, Pickup_Fee__c = ShiftConstants.SELLER_DROPOFF_FEE));
			} else {
				opportunitiesToUpdate.put(sellerOpportunityId, new Opportunity(Id = sellerOpportunityId, Pickup_Fee__c = ShiftConstants.SELLER_PICKUP_FEE));
			}
		}

		update opportunitiesToUpdate.values();
	}

	public static void beforeInsert(List<Evaluation__c> newList) {
		validateEvaluation(newList);
		updateSellerOpportunityPickupFee(newList);
	}

	public static void beforeUpdate(Map<Id, Evaluation__c> oldMap, List<Evaluation__c> newList) {
		validateEvaluation(newList);

		List<Evaluation__c> changed = new List<Evaluation__c>();
		for (Evaluation__c eval : newList) {
			if (eval.On_The_Spot_Pickup__c != oldMap.get(eval.Id).On_The_Spot_Pickup__c || 
					eval.Seller_Drop_Off__c != oldMap.get(eval.Id).Seller_Drop_Off__c) {
				changed.add(eval);
			}
		}
		if (changed.isEmpty()) {
			return;
		}

		updateSellerOpportunityPickupFee(changed);
	}
}