objects/Evaluation__c.object
<CustomObject>
    <description>Represents an evaluation of a seller vehicle.</description>
    <fields>
        <fullName>Canceled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Canceled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluated_At__c</fullName>
        <label>Evaluated At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Migration_Tree_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Migration Tree ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <label>Seller Opportunity ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a Seller Opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Migration_Tree_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Migration Tree ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ShiftBatchRemoveEmptyEvaluationsTest.cls
@isTest private class ShiftBatchRemoveEmptyEvaluationsTest {

	@testSetup private static void setup() { ShiftTesting.setup(); }

	@isTest private static void testExecute() {
		ShiftTesting.SellerTestContext sc = ShiftTesting.createAndInsertSeller();
		Id oppId = sc.opportunity.Id;
		List<Evaluation__c> evals = new List<Evaluation__c>();
		Integer insertSize = 100;
		for (Integer i = 0; i < insertSize; ++i) {
			Evaluation__c eval = new Evaluation__c(
				Seller_Opportunity_ID__c = oppId,
				Migration_Tree_ID__c = 'test-tree-id-' + i
			);
			if (Math.mod(i, 2) == 0) {
				eval.Canceled__c = false; // an empty migrated eval
			} else {
				eval.Evaluated_At__c = DateTime.now(); // a nonempty migrated eval
			}
			evals.add(eval);
		}
		insert evals;
		// also insert something which looks empty but wasn't migrated, ensure
		// we don't touch it
		insert new Evaluation__c( Seller_Opportunity_ID__c = oppId, Canceled__c = false);
		Test.startTest();
		Database.executeBatch(new ShiftBatchRemoveEmptyEvaluations());
		Test.stopTest();
		Integer ctRemain = [SELECT COUNT() FROM Evaluation__c WHERE Seller_Opportunity_ID__c = :oppId];
		System.assertEquals(insertSize / 2 + 1, ctRemain);
	}
}