objects/Incentive__c.object
<CustomObject>
    <description>Represents a code that forms a bridge between customers or business partners and Incentive Programs.</description>
    <fields>
        <fullName>Incentive_Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The incentive program that this token is tied to.</description>
        <label>Incentive Program</label>
        <referenceTo>Incentive_Program__c</referenceTo>
        <relationshipLabel>Incentives</relationshipLabel>
        <relationshipName>Incentive_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>The string representation of this token.</description>
        <externalId>true</externalId>
        <label>Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Visits__c</fullName>
        <description>How many times someone has visited this Incentive&apos;s unique link.</description>
        <label>Visits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShiftIncentives.cls
public class ShiftIncentives {
  static void validateIncentives(Map<Id, Incentive__c> oldMap, List<Incentive__c> newList) {
    for (Incentive__c incentive : newList) {
      Incentive__c oldIncentive = oldMap.get(incentive.Id);
      if (oldIncentive.Token__c != null && incentive.Token__c != oldIncentive.Token__c) {
        incentive.addError('Attempt to change Token__c from ' + oldIncentive.Token__c + ' to ' + incentive.Token__c);
      }
      if (oldIncentive.Incentive_Program_ID__c != null && incentive.Incentive_Program_ID__c != oldIncentive.Incentive_Program_ID__c) {
        incentive.addError('Attempt to change Incentive_Program_ID__c from ' + oldIncentive.Incentive_Program_ID__c + ' to ' + incentive.Incentive_Program_ID__c);
      }
      if (oldIncentive.Visits__c != null && oldIncentive.Visits__c > incentive.Visits__c) {
        incentive.addError('Attempt to decrement number of incentive visits from ' + oldIncentive.Visits__c + ' to ' + incentive.Visits__c);
      }
    }
  }

  public static void beforeUpdate(Map<Id, Incentive__c> oldMap, List<Incentive__c> newList) {
    validateIncentives(oldMap, newList);
  }
}