objects/Inspection__c.object
<CustomObject>
    <fields>
        <fullName>Forcebase_Deal_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Forcebase Deal ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>i3{0000000}</displayFormat>
        <label>Inspection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Base_Deal_ID__c</fullName>
        <formula>Migration_Source_ID__r.Base_Deal_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base Deal ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Note__c.object
<CustomObject>
    <fields>
        <fullName>Call_Outcome__c</fullName>
        <label>Call Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Evaluation Scheduled (move to next stage)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested (follow up)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Answer (follow up)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Currently Interested (follow up)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective Buyer is Dealer (move to lost)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Submitted to Seller (follow up)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seller Sold Car (move to lost)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seller Unqualified (move to lost)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seller Will Not Work With Shift (move to lost)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shift Sold Car (add to ProD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive Cancelled (follow up)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive Scheduled (move to next stage)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unreachable (move to lost)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Notes</relationshipLabel>
        <relationshipName>Opportunity_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Note</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Opportunity Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Base_Deal_ID__c</fullName>
        <formula>Migration_Source_ID__r.Base_Deal_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base Deal ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value is not a seller opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>equals</operation>
                <value>Seller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle_Order__c.object
<CustomObject>
    <description>Orders represent the process of a Buyer purchasing a Vehicle. Note that we don&apos;t name this object simple &quot;Order&quot; so as to avoid confusion with the standard salesforce Order object. We may one day decide to use that object instead, but not until we understand more about whether it fits with our model.</description>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Purchased__c</fullName>
        <formula>NOT(ISBLANK(Final_Sale_Price__c)) &amp;&amp; NOT(ISBLANK(Taxes_And_Registration__c)) &amp;&amp; Vehicle_Sale_Complete__c = True</formula>
        <label>Vehicle Purchased</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Returned__c</fullName>
        <formula>NOT(ISBLANK(Returned_On__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle Returned</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShiftVehicleDetailController.cls
public with sharing class ShiftVehicleDetailController {
	static final Integer TRUNCATE_AFTER_MAX_LINES = 30;
	
	public Vehicle__c vehicle { get; private set; }

	public Opportunity sellerOpportunity { get { return vehicle.Seller_Opportunity_ID__r; } }

	private List<Vehicle_Order__c> vehicleOrders;

	public List<OpportunityNoteDisplay> opportunityNoteDisplays { get; private set; }

	public Boolean hasOpportunityNotes { get { return !opportunityNoteDisplays.isEmpty(); } }

	public List<Attachment> attachments { get; private set; }

	public Boolean hasAttachments { get { return !attachments.isEmpty(); } }

	public Integer vehicleOrdersSize { get { return vehicleOrders.size(); } }

	public Vehicle_Order__c vehicleOrder { 
		get { return vehicleOrders.isEmpty() ? null : vehicleOrders.get(0); } 
	}

	public Contact sellerContact { get; private set; }

	public List<String> inspectionUrls { get; private set; }

	public Boolean hasInspections { get { return !inspectionUrls.isEmpty(); } }

	private void setupVehicleDetails() {
		Id vehicleId = ApexPages.currentPage().getParameters().get('id');
		vehicle = [
			SELECT 
				Id, 
				Seller_Opportunity_ID__c, 
				Seller_Opportunity_ID__r.AccountId,
				Seller_Opportunity_ID__r.Base_Deal_ID__c
			FROM Vehicle__c 
			WHERE Id = :vehicleId
		];
	}

	private void setupSellerDetails() {
		sellerContact = [
			SELECT Id 
			FROM Contact 
			WHERE AccountId = :vehicle.Seller_Opportunity_ID__r.AccountId
		];

		attachments = [
			SELECT Id, Name, ContentType, LastModifiedDate, CreatedById
			FROM Attachment 
			WHERE ParentId = :vehicle.Seller_Opportunity_ID__c
		];
		
		opportunityNoteDisplays = new List<OpportunityNoteDisplay>();
		for (Opportunity_Note__c note : [
				SELECT Id, Content__c, CreatedById, CreatedDate, Call_Outcome__c
				FROM Opportunity_Note__c
				WHERE Opportunity_Id__c = :vehicle.Seller_Opportunity_ID__c
			]) {
			opportunityNoteDisplays.add(new OpportunityNoteDisplay(note));
		}
	}

	private void setupVehicleOrders() {
		// Per the current spec, we only intend to show the full detail of the (at most one)
		// completed order. But our current system doesn't enforce the "at most one" requirement
		// yet, so we entertain the fact that we could have more and handle that on the page
		vehicleOrders = [
			SELECT Id 
			FROM Vehicle_Order__c 
			WHERE 
				Vehicle_ID__c = :vehicle.Id AND 
				Vehicle_Purchased__c = TRUE AND
				Vehicle_Returned__c = FALSE
		];
		if (vehicleOrders.size() <= 1) {
			return;
		}
		ApexPages.addMessage(new ApexPages.Message(
			ApexPages.Severity.WARNING, 
			'Vehicle is associated with ' + vehicleOrders.size() + ' completed orders'
		));
	}

	void setupInspectionUrls() {
		List<Inspection__c> inspections = [
				SELECT Id
				FROM Inspection__c
				WHERE
					Vehicle_ID__C = :vehicle.Id OR
					Forcebase_Deal_ID__c IN (:vehicle.Seller_Opportunity_ID__c, :vehicle.Seller_Opportunity_ID__r.Base_Deal_ID__c)
		];
		inspectionUrls = new List<String>();
		for (Inspection__c inspection : inspections) {
			inspectionUrls.add(ShiftProcessingPipeline.getInspectionUrl(inspection.Id, false));
		}
	}

	public ShiftVehicleDetailController() {
		setupVehicleDetails();
		setupSellerDetails();
		setupVehicleOrders();
		setupInspectionUrls();
	}

	public class OpportunityNoteDisplay {				
		Opportunity_Note__c source;
		String truncated;
		String full;

		public OpportunityNoteDisplay(Opportunity_Note__c note) {
			this.source = note;
			this.truncated = truncateLines(note.Content__c, TRUNCATE_AFTER_MAX_LINES);
			this.full = truncateLines(note.Content__c, -1);
			hasToggle = this.truncated !=null && this.full != null && !this.truncated.equals(this.full);		
		}

		public Opportunity_Note__c note { get { return source; } }

		public String truncatedContent { get { return truncated; } }

		public String fullContent { get { return full; } }

		public Boolean hasToggle { get; private set; }

		//public Boolean getHasToggle() { return false; }

		private String truncateLines(String value, Integer maxLines) {
			if (value == null) {
				return null;
			}
			List<String> lines = new List<String>();
			for (String line : value.split('\\r?\\n')) {
				if (maxLines >= 0 && lines.size() >= maxLines) {
					break;
				}
				lines.add(line.escapeHtml4());
			}
			return String.join(lines, '<br/>');
		}
	}
}