objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Base_Deal_ID__c</fullName>
        <formula>Migration_Source_ID__r.Base_Deal_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base Deal ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <formula>Vehicle_ID__r.List_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <formula>Vehicle_ID__r.Mileage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <formula>Vehicle_ID__r.VIN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Represents a region for vehicle activity (acquire, sell, etc).</description>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Base_Deal_ID__c</fullName>
        <formula>Migration_Source_ID__r.Base_Deal_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base Deal ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Body_Style__c</fullName>
        <label>Body Style</label>
        <picklist>
            <picklistValues>
                <fullName>Convertible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sedan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Van</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wagon</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Coming_Soon__c</fullName>
        <formula>OR(
Needs_Repairs__c = True,
In_Transit__c = True,
(ISPICKVAL(Paperwork_Missing__c, &apos;Yes - Less Than 7 Days Unavailable&apos;)),
(ISPICKVAL(Paperwork_Missing__c, &apos;Yes - More Than 7 Days Unavailable&apos;)),
(Seller_Stage__c =&apos;Prepare Car for Sale&apos;),
(Photos_Ready__c = False)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Coming Soon</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Driveshift_Listing_URL__c</fullName>
        <label>Driveshift Listing URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Exterior_Color__c</fullName>
        <label>Exterior Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interior_Color__c</fullName>
        <label>Interior Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Listing_Region_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Listing Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing_Region_Name__c</fullName>
        <formula>Listing_Region_ID__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Listing Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale_Pending__c</fullName>
        <formula>OR( 
On_Deposit__c = True, 
Going_To_Auction__c = True,
Hold_For_Financing__c = True,
Hold_For_Trade_In__c = True 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sale Pending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShiftCxCarSearchController.cls
public with sharing class ShiftCxCarSearchController {

	public class SearchResult {
		public Map<String, List<Vehicle__c>> carsInStage { get; set; }
		public Map<String, Integer> carCountInStage { get; set; }

		public SearchResult(Map<String, List<Vehicle__c>> carsInStage) {
			this.carsInStage = carsInStage;
			carCountInStage = new Map<String, Integer>();
			for (String stage : carsInStage.keySet()) {
				carCountInStage.put(stage, carsInStage.get(stage).size());
			}
		}
	}

	// View state size limit is 135KB, so this can't be arbitrarily high.
	private static final Integer MAX_RESULTS_PER_STAGE = 99;

	public List<SelectOption> allStages { get; set; }
	public List<String> selectedStages { get; set; }
	public String searchQuery { get; set; }
	public SearchResult searchResult { get; set; }
	public String errorMessage { get; set; }

	private static List<String> stagesInCustomOrder() {
		List<String> out = new List<String>();
		// These stages are most important for CX, so show them first.
		out.add(ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL);
		out.add(ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE);
		for (String stage : ShiftConstants.SELLER_OPPORTUNITY_STAGES) {
			if (!new Set<String>(out).contains(stage)) { // inefficient, but N is small, and this runs infrequently
				out.add(stage);
			}
		}
		return out;
	}

	public ShiftCxCarSearchController() {
		searchQuery = '';
		allStages = new List<SelectOption>();
		for (String stage : stagesInCustomOrder()) {
			allStages.add(new SelectOption(stage, stage));
		}
		selectedStages = new List<String>();
		selectedStages.add(ShiftConstants.SELLER_OPPORTUNITY_STAGE_PREPARE);
		selectedStages.add(ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL);
		// initialize searchResult
		search();
	}

	public void search() {
		searchResult = doSearch(new Set<String>(selectedStages), searchQuery, MAX_RESULTS_PER_STAGE);
	}

	private static List<Vehicle__c> doSearchInStage(String stage, String searchQuery, Integer limt) {
		List<String> queryComponents = new List<String>();
		for (String token : searchQuery.split(' ')) {
			String queryComponent = '';
			if (ShiftUtil.isValidId(token)) {
				String tokenQ = ShiftUtil.soqlQuote(token);
				queryComponent +=
						'(Id = ' + tokenQ + ')'
						+ ' OR (Vehicle_Id__c = ' + tokenQ + ')'
						+ ' OR ';
			}
			String termQ = ShiftUtil.soqlQuote('%' + token + '%');
			queryComponent +=
					'(Name LIKE ' + termQ + ')'
					+ ' OR (Vehicle_Id__r.Body_Style__c LIKE ' + termQ + ')'
					+ ' OR (Vehicle_Id__r.VIN__c LIKE ' + termQ + ')'
					+ ' OR (Vehicle_Id__r.Driveshift_Listing_URL__c LIKE ' + termQ + ')'
					+ ' OR (Vehicle_Id__r.Base_Deal_ID__c LIKE ' + termQ + ')'
					+ ' OR (Vehicle_Id__r.Listing_Region_ID__r.Shift_Key__c LIKE ' + termQ + ')'
					+ ' OR (Vehicle_Id__r.Listing_Region_ID__r.Name LIKE ' + termQ + ')';
			queryComponents.add('(' + queryComponent + ')');
		}

		String dbQuery =
				'SELECT Id, Vehicle_Id__r.Name, Vehicle_Id__r.Exterior_Color__c, Vehicle_Id__r.Interior_Color__c, Vehicle_Id__r.Body_Style__c, Vehicle_Id__r.Mileage__c, Vehicle_Id__r.List_Price__c, Vehicle_Id__r.Coming_Soon__c, Vehicle_Id__r.Sale_Pending__c, Vehicle_Id__r.Listing_Region_Name__c'
				+ ' FROM Opportunity WHERE StageName = ' + ShiftUtil.soqlQuote(stage) + ' AND RecordType.DeveloperName = ' + ShiftUtil.soqlQuote(ShiftConstants.OPPORTUNITY_RECORD_TYPE_SELLER) + ' AND '
				+ '(' + String.join(queryComponents, ' AND ') + ')'
				+ ' ORDER BY Vehicle_Id__r.Coming_Soon__c ASC, Vehicle_Id__r.Listing_Region_Name__c DESC, Id ASC'
				+ ' LIMIT ' + limt;
		System.debug('searchInStage "' + stage + '": dbQuery: ' + dbQuery);
		List<Opportunity> results = Database.Query(dbQuery);
		List<Vehicle__c> out = new List<Vehicle__c>();
		for (Opportunity x : results) {
			out.add(x.Vehicle_Id__r);
		}
		return out;
	}

	public static SearchResult doSearch(Set<String> selectedStages, String searchQuery, Integer limt) {
		Map<String, List<Vehicle__c>> carsInStage = new Map<String, List<Vehicle__c>>();
		for (String stage : selectedStages) {
			carsInStage.put(stage, doSearchInStage(stage, searchQuery, limt));
		}
		return new SearchResult(carsInStage);
	}

}