objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Advance_Funds_Amount__c</fullName>
        <label>Advance Funds Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_Funds_Fee_2__c</fullName>
        <label>Advance Funds Fee 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_Funds_Fee_Override__c</fullName>
        <label>Advance Funds Fee Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_Funds_Net_2__c</fullName>
        <label>Advance Funds Net 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_Funds_Type__c</fullName>
        <label>Advance Funds Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lienholder Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Car_Commission__c</fullName>
        <label>Car Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Covered_Repair_Cost__c</fullName>
        <label>Covered Repair Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Direct_To_Wholesale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Direct To Wholesale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entered_Stage_Sold__c</fullName>
        <label>Entered Stage Sold</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Final_Guaranteed_Price_2__c</fullName>
        <label>Final Guaranteed Price 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Sale_Price__c</fullName>
        <formula>Vehicle_ID__r.Purchased_Vehicle_Order_ID__r.Final_Sale_Price__c</formula>
        <label>Final Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Flat_Fee_Percent__c</fullName>
        <label>Flat Fee - Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Flat_Fee__c</fullName>
        <label>Flat Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Guaranteed_Price__c</fullName>
        <label>Guaranteed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Paperwork_Fee_2__c</fullName>
        <label>Late Paperwork Fee 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Paperwork_Fee_Override__c</fullName>
        <label>Late Paperwork Fee Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <formula>Vehicle_ID__r.List_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payoff_Amount__c</fullName>
        <label>Payoff Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pickup_Fee_Revenue__c</fullName>
        <label>Pickup Fee Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pickup_Fee__c</fullName>
        <defaultValue>100</defaultValue>
        <description>Pickup Fee defaults to $100 but can be reduced to $0 if &quot;On The Spot Pickup&quot; or &quot;Seller Drop-Off&quot; is checked in the Evaluation. Change this field directly to override. Credit is split with the seller for non-Flat Fee deals.</description>
        <inlineHelpText>Pickup Fee defaults to $100 but can be reduced to $0 if &quot;On The Spot Pickup&quot; or &quot;Seller Drop-Off&quot; is checked in the Evaluation. Change this field directly to override. Credit is split with the seller for non-Flat Fee deals.</inlineHelpText>
        <label>Pickup Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_Strategy__c</fullName>
        <label>Pricing Strategy</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Fee - Dollar Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Fee - Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Price - 0% Upside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specific Car Search</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Projected_Car_Commission__c</fullName>
        <label>Projected Car Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Referral_Payout__c</fullName>
        <label>Referral Payout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Referral_Program_Or_Promotion__c</fullName>
        <label>Referral Program Or Promotion</label>
        <picklist>
            <picklistValues>
                <fullName>AnyPerk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At2 Detail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoFresh Mobile Carwash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Pro Detailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California Detail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Challenge 4 Charity (Stanford)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Challenge 4 Charity (UCLA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Relocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrystalCity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCAutoShow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCLaunch250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dent Artist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dent Discount Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dents Doctor PDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DentSquad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DentX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detail Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFJ Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropbox San Francisco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EcoWash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ed&apos;s Mobile Detailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EuroPros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friends and Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoldenBright Detail Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grateful Dent PDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highland Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IndyExpress Mobile Detail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Revenue_Net_2__c</fullName>
        <label>Revenue Net 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Contract_Signed_On__c</fullName>
        <formula>Seller_Contract_ID__r.Signed_On__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Seller Contract Signed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Seller_Costs_DMV__c</fullName>
        <label>Seller Costs DMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Costs_Repairs_Estimate__c</fullName>
        <label>Seller Costs Repairs Estimate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Costs_Repairs__c</fullName>
        <label>Seller Costs Repairs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Payment_Gross_2__c</fullName>
        <label>Seller Payment Gross 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Payment_Net_2__c</fullName>
        <label>Seller Payment Net 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Upside_Percentage__c</fullName>
        <label>Seller Upside Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shift_Costs_Repairs__c</fullName>
        <label>Shift Costs Repairs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Revenue__c</fullName>
        <label>Total Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Shift_Costs__c</fullName>
        <label>Total Shift Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_In_Credit_Amount__c</fullName>
        <label>Trade-In Credit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_In_Status__c</fullName>
        <inlineHelpText>Requested: trade needs pricing
Estimated: est. quote sent
Approved: price finalized; contract signed
Funded: credit applied to purchase (need team ld. approval)
Closed: return period elapsed--final settlement complete
Expired: buyer elects not to buy</inlineHelpText>
        <label>Trade-In Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Was_Paid_On_Contract_Expiration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Was Paid On Contract Expiration</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <businessProcess>Seller</businessProcess>
        <label>Seller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paperwork_Fee_Pending__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Admin field to track the Late Paperwork fee we will charge once the contract is signed for over 30 days and paperwork is missing.  This field should be updated by the updatePaperworkFeePending trigger.</description>
        <inlineHelpText>This field should be updated by the updatePaperworkFeePending trigger.</inlineHelpText>
        <label>Paperwork Fee Pending</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShiftPayments.cls
// The parent class for all Shift exceptions (which all extend ShiftException).
public class ShiftPayments {
	private static Date ADVANCE_FUNDS_FEE_START_DATE = Date.newInstance(2016, 4, 30);

	private static Set<String> CALCULATED_PRICING_STRATEGIES = new Set<String> {
			ShiftConstants.PRICING_STRATEGY_STANDARD,
			ShiftConstants.PRICING_STRATEGY_SINGLE_PRICE_0_UPSIDE,
			ShiftConstants.PRICING_STRATEGY_SPECIFIC_CAR_SEARCH,
			ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT,
			ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT,
			''
	};

	// To get around the issue that some fields can have null values, certain fields are validated and
	// set to 0.0 to support later calculations, clone original object and return new normalized object
	@TestVisible
	static Opportunity normalizeFinancialFields(Opportunity base) {
		Opportunity o = base.clone(false, true);
		o.Covered_Repair_Cost__c = ShiftUtil.nonNullDecimal(o.Covered_Repair_Cost__c);
		o.Flat_Fee__c = ShiftUtil.nonNullDecimal(o.Flat_Fee__c);
		o.Payoff_Amount__c = ShiftUtil.nonNullDecimal(o.Payoff_Amount__c);
		o.Pickup_Fee__c = ShiftUtil.nonNullDecimal(o.Pickup_Fee__c);
		o.Seller_Costs_Repairs__c = ShiftUtil.nonNullDecimal(o.Seller_Costs_Repairs__c);
		o.Seller_Costs_DMV__c = ShiftUtil.nonNullDecimal(o.Seller_Costs_DMV__c);
		o.Shift_Costs_Repairs__c = ShiftUtil.nonNullDecimal(o.Shift_Costs_Repairs__c);
		o.Covered_Repair_Cost__c = ShiftUtil.nonNullDecimal(o.Covered_Repair_Cost__c);
		o.Trade_In_Credit_Amount__c = ShiftUtil.nonNullDecimal(o.Trade_In_Credit_Amount__c);
		o.Seller_Upside_Percentage__c = ShiftUtil.nonNullDecimal(o.Seller_Upside_Percentage__c);
		return o;
	}

	public static void calculateSellerOpportunityFinancials(Opportunity o, Vehicle__c cv) {
		Opportunity co = normalizeFinancialFields(o);

		// Cross object formula fields are passed directly as parameters to faciliate testing
		// After the calculation is done on the cloned object copy the value over to the orignal
		// object
		co.Late_Paperwork_Fee_2__c = calculateLatePaperWorkFee(co, cv, co.Seller_Contract_Signed_On__c);
		o.Late_Paperwork_Fee_2__c = co.Late_Paperwork_Fee_2__c;
		co.Advance_Funds_Fee_2__c = calculateAdvanceFundsFee(co);
		o.Advance_Funds_Fee_2__c = co.Advance_Funds_Fee_2__c;
		co.Advance_Funds_Net_2__c = calculateAdvanceFundsNet(co);
		o.Advance_Funds_Net_2__c = co.Advance_Funds_Net_2__c;
		co.Referral_Payout__c = calculateReferralPayout(co);
		o.Referral_Payout__c = co.Referral_Payout__c;

		if (co.Guaranteed_Price__c != null) {
			co.Final_Guaranteed_Price_2__c = calculateFinalGuaranteedPrice(co);
			o.Final_Guaranteed_Price_2__c = co.Final_Guaranteed_Price_2__c;
		}

		if (co.List_Price__c != null && co.Guaranteed_Price__c != null) {
			co.Projected_Car_Commission__c = calculateCarCommission(co, co.List_Price__c);
			o.Projected_Car_Commission__c = co.Projected_Car_Commission__c;
		}

		if (co.Final_Sale_Price__c != null && co.Guaranteed_Price__c != null) {
			co.Pickup_Fee_Revenue__c = calculatePickupFeeRevenue(co, co.Final_Sale_Price__c);
			o.Pickup_Fee_Revenue__c = co.Pickup_Fee_Revenue__c;
			co.Seller_Payment_Gross_2__c = calculateSellerPaymentGross(co, co.Final_Sale_Price__c);
			o.Seller_Payment_Gross_2__c = co.Seller_Payment_Gross_2__c;
			co.Seller_Payment_Net_2__c = calculateSellerPaymentNet(co);
			o.Seller_Payment_Net_2__c = co.Seller_Payment_Net_2__c;
			co.Car_Commission__c = calculateCarCommission(co, co.Final_Sale_Price__c);
			o.Car_Commission__c = co.Car_Commission__c;
			co.Total_Revenue__c = calculateTotalRevenue(co);
			o.Total_Revenue__c = co.Total_Revenue__c;
			co.Total_Shift_Costs__c = calculateTotalShiftCosts(co);
			o.Total_Shift_Costs__c = co.Total_Shift_Costs__c;
			co.Revenue_Net_2__c = calculateRevenueNet(co);
			o.Revenue_Net_2__c = co.Revenue_Net_2__c;
		}
	}

	//Advance_Funds_Fee_2
	@TestVisible
	static Decimal calculateAdvanceFundsFee(Opportunity o) {
		Decimal finalAmount = 0.0;
		if(o.Advance_Funds_Amount__c != null && o.Advance_Funds_Amount__c != 0.0) {
			if (o.Advance_Funds_Fee_Override__c != null) {
				return o.Advance_Funds_Fee_Override__c;
			}
			if (Date.today() > ADVANCE_FUNDS_FEE_START_DATE && o.LeadSource != ShiftConstants.LEAD_SOURCE_TESLA_REMARKETING) {
				finalAmount = ShiftConstants.ADVANCE_FUNDS_FEE;
			}
		}
		return finalAmount;
	}

	//Late_Paperwork_Fee_2
	@TestVisible
	static Decimal calculateLatePaperWorkFee(Opportunity o, Vehicle__c v, Date dateSigned) {
		Decimal finalAmount = 0.0;
		if (o.Late_Paperwork_Fee_Override__c != null) {
			return o.Late_Paperwork_Fee_Override__c;
		}
		if (v != null) {
			if (o.Entered_Stage_Sold__c != null && dateSigned != null && o.Entered_Stage_Sold__c > dateSigned.addDays(30)) {
				finalAmount = ShiftUtil.nonNullDecimal(v.Paperwork_Fee_Pending__c);
			} else if (dateSigned != null && DateTime.now() > dateSigned.addDays(30)) {
				finalAmount = ShiftUtil.nonNullDecimal(v.Paperwork_Fee_Pending__c);
			}
		}
		return finalAmount;
	}

	//Pickup_Fee_Revenue
	@TestVisible
	static Decimal calculatePickupFeeRevenue(Opportunity o, Decimal finalSalePrice) {
		String pStrategy = o.Pricing_Strategy__c;
		Decimal maxCommission = finalSalePrice - o.Final_Guaranteed_Price_2__c;
		Decimal finalAmount = 0.0;
		if (maxCommission > o.Pickup_Fee__c) {
			if (pStrategy == ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT) {
				finalAmount = o.Pickup_Fee__c;
			} else if (pStrategy == ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT) {
				finalAmount = o.Pickup_Fee__c;
			} else {
				finalAmount = o.Pickup_Fee__c * ((100 - o.Seller_Upside_Percentage__c) / 100);
			}
		}
		return finalAmount;
	}

	//Advance_Funds_Net_2
	@TestVisible
	static Decimal calculateAdvanceFundsNet(Opportunity o) {
		Decimal finalAmount = 0.0;
		if (o.Advance_Funds_Amount__c != null && o.Advance_Funds_Amount__c != 0.0) {
			finalAmount = o.Advance_Funds_Amount__c - o.Seller_Costs_DMV__c - o.Payoff_Amount__c - calculateSellerRepairCosts(o) - o.Advance_Funds_Fee_2__c - o.Late_Paperwork_Fee_2__c;
		}
		return finalAmount;
	}

	//Helper method to calculate seller repair costs
	//TODO Need to change work flow so that we don't have to disambiguate this value
	@TestVisible
	static Decimal calculateSellerRepairCosts(Opportunity o) {
		if (o.Seller_Costs_Repairs__c != null) {
			return o.Seller_Costs_Repairs__c;
		} else {
			return o.Seller_Costs_Repairs_Estimate__c;
		}
	}

	//Referral_Payout
	@TestVisible
	static Decimal calculateReferralPayout(Opportunity o) {
		Decimal finalAmount = 0.0;
		String refProgram = o.Referral_Program_Or_Promotion__c;
		Set<String> tierOnePrograms = new Set<String> {
				ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_PASSPORT_UNLIMITED_HOT_DEAL,
				ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_TESLA,
				ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_ANYPERK
		};
		Set<String> tierTwoPrograms = new Set<String> {
				ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_GOOGLE,
				ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_PASSPORT_UNLIMITED,
				ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_LA_STREET_TEAM,
				ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_QUALCOMM,
				ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_HIGHLAND_PORTOFLIO
		};
		if (tierOnePrograms.contains(refProgram)) {
			finalAmount = 300.0;
		} else if (tierTwoPrograms.contains(refProgram)) {
			finalAmount = 200.0;
		}
		return finalAmount;
	}


	//Final_Guaranteed_Price_2
	@TestVisible
	static Decimal calculateFinalGuaranteedPrice(Opportunity o) {
		return o.Guaranteed_Price__c - o.Pickup_Fee__c;
	}

	//Seller_Payment_Gross_2
	@TestVisible
	static Decimal calculateSellerPaymentGross(Opportunity o, Decimal finalSalePrice) {
		Decimal finalAmount = 0.0;
		if (finalSalePrice > o.Final_Guaranteed_Price_2__c) {
			finalAmount = o.Final_Guaranteed_Price_2__c + ((finalSalePrice - o.Final_Guaranteed_Price_2__c) * (o.Seller_Upside_Percentage__c / 100));
		} else {
			finalAmount = o.Final_Guaranteed_Price_2__c;
		}
		return finalAmount;
	}

	//Seller_Payment_Net_2
	@TestVisible
	static Decimal calculateSellerPaymentNet(Opportunity o) {
		Decimal finalAmount = 0.0;
		Decimal sellerFees = o.Seller_Costs_DMV__c + calculateSellerRepairCosts(o) + o.Late_Paperwork_Fee_2__c;
		if (o.Trade_In_Status__c == ShiftConstants.TRADE_IN_STATUS_FUNDED) {
			finalAmount = o.Seller_Payment_Gross_2__c - o.Trade_In_Credit_Amount__c;
		} else if (o.Advance_Funds_Amount__c > 0) {
			if (o.Advance_Funds_Type__c == ShiftConstants.ADVANCE_FUNDS_TYPE_LIENHOLDER_ONLY) {
				finalAmount = o.Seller_Payment_Gross_2__c - sellerFees - o.Payoff_Amount__c - o.Trade_In_Credit_Amount__c + o.Referral_Payout__c;
			} else {
				finalAmount = o.Seller_Payment_Gross_2__c - o.Advance_Funds_Amount__c;
			}
		} else if (o.Direct_To_Wholesale__c == true) {
			finalAmount = o.Final_Guaranteed_Price_2__c - o.Payoff_Amount__c - o.Late_Paperwork_Fee_2__c + o.Referral_Payout__c;
		} else if (o.Was_Paid_On_Contract_Expiration__c == true) {
			finalAmount = o.Seller_Payment_Gross_2__c - o.Final_Guaranteed_Price_2__c;
		} else if (o.Pricing_Strategy__c == ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT) {
			finalAmount = o.Seller_Payment_Gross_2__c - sellerFees - o.Flat_Fee__c - o.Payoff_Amount__c + o.Referral_Payout__c;
		} else {
			finalAmount = o.Seller_Payment_Gross_2__c - sellerFees - o.Payoff_Amount__c + o.Referral_Payout__c;
		}
		return finalAmount;
	}

	//Car_Commission
	@TestVisible
	static Decimal calculateCarCommission(Opportunity o, Decimal finalSalePrice) {
		String pStrategy = o.Pricing_Strategy__c;
		Decimal maxCommission = Math.max(0.0, finalSalePrice - o.Guaranteed_Price__c);
		Decimal finalAmount = maxCommission;
		if (pStrategy == ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT) {
			if (maxCommission > o.Flat_Fee__c) {
				finalAmount = o.Flat_Fee__c;
			}
		} else if (pStrategy == ShiftConstants.PRICING_STRATEGY_FLAT_FEE_PERCENT) {
			if (maxCommission > (finalSalePrice * o.Flat_Fee_Percent__c)) {
				finalAmount = finalSalePrice * o.Flat_Fee_Percent__c;
			}
		} else if (maxCommission > 0) {
			finalAmount = (finalSalePrice - o.Guaranteed_Price__c) * ((100 - o.Seller_Upside_Percentage__c) / 100);
		}
		return finalAmount;
	}

	//Total_Revenue
	@TestVisible
	static Decimal calculateTotalRevenue(Opportunity o) {
		return o.Car_Commission__c + o.Late_Paperwork_Fee_2__c + o.Advance_Funds_Fee_2__c + o.Pickup_Fee_Revenue__c;
	}

	//Total Shift Costs
	@TestVisible
	static Decimal calculateTotalShiftCosts(Opportunity o) {
		return o.Shift_Costs_Repairs__c + o.Covered_Repair_Cost__c;
	}

	//Revenue_Net_2
	@TestVisible
	static Decimal calculateRevenueNet(Opportunity o) {
		return o.Total_Revenue__c - o.Total_Shift_Costs__c;
	}
}