objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Final_Sale_Price__c</fullName>
        <formula>Vehicle_ID__r.Purchased_Vehicle_Order_ID__r.Final_Sale_Price__c</formula>
        <label>Final Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Handover_Date__c</fullName>
        <formula>Vehicle_ID__r.Purchased_Vehicle_Order_ID__r.Handover_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Handover Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Payment__c.object
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>On_Deposit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Deposit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purchased_Vehicle_Order_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchased Vehicle Order ID</label>
        <referenceTo>Vehicle_Order__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle_Order__c.object
<CustomObject>
    <description>Orders represent the process of a Buyer purchasing a Vehicle. Note that we don&apos;t name this object simple &quot;Order&quot; so as to avoid confusion with the standard salesforce Order object. We may one day decide to use that object instead, but not until we understand more about whether it fits with our model.</description>
    <fields>
        <fullName>Deposit_Accepted_On__c</fullName>
        <label>Deposit Accepted On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit_Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether this deposit has expired, if it has then the car won&apos;t be flagged as On Deposit and will be back on sale</description>
        <inlineHelpText>Determines whether this deposit has expired, if it has then the car won&apos;t be flagged as On Deposit and will be back on sale</inlineHelpText>
        <label>Deposit Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deposit_Returned_On__c</fullName>
        <label>Deposit Returned On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit_Returned_Reason__c</fullName>
        <label>Deposit Returned Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Autopay financing fell through</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earnest financing fell through</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Tech financing fell through</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal financing fell through</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased Car - Paid In Full</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Sale_Price__c</fullName>
        <label>Final Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Handover_Date__c</fullName>
        <description>The date at which a vehicle order moves to the &quot;Handover&quot; stage.</description>
        <inlineHelpText>The date at which a vehicle order moves to the &quot;Handover&quot; stage.</inlineHelpText>
        <label>Handover Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cashier&apos;s Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan - Autopay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan - Earnest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan - First Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan - Non Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan - Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Returned_On__c</fullName>
        <label>Returned On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Returned_Reason__c</fullName>
        <label>Returned Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Buyer Found A Preferable Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer&apos;s Remorse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic Condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Vehicle Listing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mechanical Condition (Not Due To Failed PPI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed PPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspected Return Policy Abuse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Taxes_And_Registration__c</fullName>
        <label>Taxes And Registration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Orders</relationshipLabel>
        <relationshipName>Vehicle_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Sale_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vehicle Sale Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Vehicle Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShiftVehicleOrderTriggersTest.cls
@IsTest
private class ShiftVehicleOrderTriggersTest {
	@TestSetup private static void setup() { ShiftTesting.setup(); }

	@IsTest
	static void testErrorOnDepositReturnedWithoutDeposit() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);
		vo.Deposit_Returned_Reason__c = ShiftConstants.VEHICLE_ORDER_DEPOSIT_RETURNED_REASON_OTHER;
		ShiftTesting.expectInsertExceptionContains(vo, 'Cannot insert vehicle order with deposit returned but no deposit');
	}

	@IsTest
	static void testErrorOnVehicleReturnWithoutPurchase() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);
		vo.Returned_On__c = Date.today();
		ShiftTesting.expectInsertExceptionContains(vo, 'Cannot insert vehicle order with vehicle returned but no vehicle purchased');
	}

	@IsTest
	static void testErrorOnOpenDepositOnVehicleWithExistingOpenDeposit() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		ShiftTesting.setOpenDeposit(vo1);
		insert vo1;

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		ShiftTesting.setOpenDeposit(vo2);
		ShiftTesting.expectInsertExceptionContains(vo2, 'Vehicle already has an open order');
	}

	@IsTest
	static void testErrorOnOpenPurchaseOnVehicleWithExistingOpenDeposit() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		insert vo1;
		ShiftTesting.setOpenDeposit(vo1);
		update vo1;

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		insert vo2;
		ctx.setOpenPurchase(vo2);
		ShiftTesting.expectUpdateExceptionContains(vo2, 'Vehicle already has an open order');
	}

	@IsTest
	static void testReturnedDepositOnVehicleWithExistingOpenDeposit() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		ShiftTesting.setOpenDeposit(vo1);
		insert vo1;

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		ShiftTesting.setReturnedDeposit(vo2);
		insert vo2;
		System.assertEquals(2, [SELECT COUNT() FROM Vehicle_Order__c WHERE Vehicle_ID__c = :v.Id]);
	}

	@IsTest
	static void testErrorOnOpenDepositOnVehicleWithExistingOpenPurchase() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		insert vo1;
		ctx.setAndUpdateOpenPurchase(vo1);

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		ShiftTesting.setOpenDeposit(vo2);
		ShiftTesting.expectInsertExceptionContains(vo2, 'Vehicle already has an open order');
	}

	@IsTest
	static void testErrorOnOpenPurchaseOnVehicleWithExistingOpenPurchase() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		insert vo1;
		ctx.setAndUpdateOpenPurchase(vo1);

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		insert vo2;
		ctx.setOpenPurchase(vo2);
		ShiftTesting.expectUpdateExceptionContains(vo2, 'Vehicle already has an open order');
	}

	@IsTest
	static void testReturnedDepositOnVehicleWithExistingOpenPurchase() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		insert vo1;
		ctx.setAndUpdateOpenPurchase(vo1);

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		insert vo2;
		ShiftTesting.setReturnedDeposit(vo2);
		update vo2;
		System.assertEquals(2, [SELECT COUNT() FROM Vehicle_Order__c WHERE Vehicle_ID__c = :v.Id]);
	}

	@IsTest
	static void testOpenDepositOnVehicleWithExistingOrder() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		insert vo1;

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		ShiftTesting.setOpenDeposit(vo2);
		insert vo2;
		System.assertEquals(2, [SELECT COUNT() FROM Vehicle_Order__c WHERE Vehicle_ID__c = :v.Id]);
	}

	@IsTest
	static void testOpenPurchaseOnVehicleWithExistingOrder() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		insert vo1;

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		insert vo2;
		ctx.setAndUpdateOpenPurchase(vo2);
		System.assertEquals(2, [SELECT COUNT() FROM Vehicle_Order__c WHERE Vehicle_ID__c = :v.Id]);
	}

	@IsTest
	static void testReturnedDepositOnVehicleWithExistingOrder() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo1 = ctx.createVehicleOrder(v);
		insert vo1;

		Vehicle_Order__c vo2 = ctx.createVehicleOrder(v);
		ShiftTesting.setReturnedDeposit(vo2);
		insert vo2;
		System.assertEquals(2, [SELECT COUNT() FROM Vehicle_Order__c WHERE Vehicle_ID__c = :v.Id]);
	}

	@IsTest
	static void testReturnedPurchaseOnVehicleWithExistingOrder() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();
		Vehicle_Order__c vo1 = bctx.createVehicleOrder(sctx.vehicle);
		insert vo1;

		Test.startTest();
		Vehicle_Order__c vo2 = bctx.createVehicleOrder(sctx.vehicle);
		insert vo2;
		bctx.setAndUpdateOpenPurchase(vo2);
		bctx.setReturnedPurchase(vo2);
		update vo2;
		System.assertEquals(2, [SELECT COUNT() FROM Vehicle_Order__c WHERE Vehicle_ID__c = :sctx.vehicle.Id]);
		Test.stopTest();
	}

	static void testErrorOnVehicleWithIncompleteOpenPurchase() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);

		vo.Final_Sale_Price__c = 10000.00;
		ShiftTesting.expectInsertExceptionContains(vo, 'Vehicle order must have all or none');

		vo.Taxes_And_Registration__c = 1000.00;
		ShiftTesting.expectInsertExceptionContains(vo, 'Vehicle order must have all or none');

		vo.Final_Sale_Price__c = null;
		ShiftTesting.expectInsertExceptionContains(vo, 'Vehicle order must have all or none');

		vo.Payment_Method__c = ShiftConstants.VEHICLE_ORDER_PAYMENT_METHOD_CASH;
		ShiftTesting.expectInsertExceptionContains(vo, 'Vehicle order must have all or none');

		vo.Taxes_And_Registration__c = null;
		ShiftTesting.expectInsertExceptionContains(vo, 'Vehicle order must have all or none');

		vo.Final_Sale_Price__c = 10000.00;
		ShiftTesting.expectInsertExceptionContains(vo, 'Vehicle order must have all or none');
	}

	@IsTest
	static void testErrorOnVehicleSaleCompleteWithIncompleteOpenPurchase() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);
		vo.Vehicle_Sale_Complete__c = true;
		ShiftTesting.expectInsertExceptionContains(vo, ShiftVehicleOrders.VEHICLE_SALE_CANNOT_COMPLETE_ERROR);

		vo.Final_Sale_Price__c = 100;
		vo.Taxes_And_Registration__c = 100;
		ShiftTesting.expectInsertExceptionContains(vo, ShiftVehicleOrders.VEHICLE_SALE_CANNOT_COMPLETE_ERROR);

		vo.Taxes_And_Registration__c = null;
		vo.Final_Sale_Price__c = null;
		vo.Vehicle_Sale_Complete__c = false;
		insert vo;
		Payment__c payment = ctx.createPayment(vo);
		insert payment;
		vo.Vehicle_Sale_Complete__c = true;
		ShiftTesting.expectUpdateExceptionContains(vo, ShiftVehicleOrders.VEHICLE_SALE_CANNOT_COMPLETE_ERROR);
	}

	@IsTest
	static void testOpportunityStageOnVehicleOrderInsertUpdate() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();

		Test.startTest();
		Vehicle_Order__c vo1 = bctx.createVehicleOrder(sctx.vehicle);
		insert vo1;
		System.assertEquals(ShiftConstants.SELLER_OPPORTUNITY_STAGE_LEADS, [SELECT StageName FROM Opportunity WHERE Id = :sctx.opportunity.Id].StageName);
		System.assertEquals(null, [SELECT Handover_Date__c FROM Vehicle_Order__c WHERE Id = :vo1.Id].Handover_Date__c);

		Vehicle_Order__c vo2 = bctx.createVehicleOrder(sctx.vehicle);
		insert vo2;
		bctx.setOpenPurchase(vo2);
		update vo2;
		System.assertEquals(ShiftConstants.SELLER_OPPORTUNITY_STAGE_HANDOVER, [SELECT StageName FROM Opportunity WHERE Id = :sctx.opportunity.Id].StageName);
		System.assertEquals(Date.today(), [SELECT Handover_Date__c FROM Vehicle_Order__c WHERE Id = :vo2.Id].Handover_Date__c);

		bctx.setReturnedPurchase(vo2);
		update vo2;
		System.assertEquals(ShiftConstants.SELLER_OPPORTUNITY_STAGE_SELL, [SELECT StageName FROM Opportunity WHERE Id = :sctx.opportunity.Id].StageName);
		System.assertEquals(Date.today(), [SELECT Handover_Date__c FROM Vehicle_Order__c WHERE Id = :vo2.Id].Handover_Date__c);
		Test.stopTest();
	}

	@IsTest
	static void testErrorOnInsertNewlySoldOrderAlreadyReturned() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);
		vo.Final_Sale_Price__c = 10000.00;
		vo.Taxes_And_Registration__c = 1000.00;
		vo.Payment_Method__c = ShiftConstants.VEHICLE_ORDER_PAYMENT_METHOD_CASH;
		vo.Vehicle_Sale_Complete__c = true;
		vo.Returned_On__c = Date.today();
		vo.Returned_Reason__c = ShiftConstants.VEHICLE_ORDER_RETURNED_REASON_BUYERS_REMORSE;
		ShiftTesting.expectInsertExceptionContains(vo, 'A vehicle order cannot be newly sold and also returned');
	}

	@IsTest
	static void testErrorOnUpdateNewlySoldOrderAlreadyReturned() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);
		insert vo;
		ctx.setReturnedPurchase(vo);
		ShiftTesting.expectUpdateExceptionContains(vo, 'A vehicle order cannot be newly sold and also returned');
	}

	@IsTest
	static void testErrorOnInsertNewlySoldOrderWithHandoverDate() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.prepareBuyerTestContext();
		ctx.insertOpportunity();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);
		vo.Handover_Date__c = Date.today();
		vo.Final_Sale_Price__c = 10000.00;
		vo.Taxes_And_Registration__c = 1000.00;
		vo.Vehicle_Sale_Complete__c = true;
		vo.Payment_Method__c = ShiftConstants.VEHICLE_ORDER_PAYMENT_METHOD_CASH;
		ShiftTesting.expectInsertExceptionContains(vo, 'A vehicle order cannot be newly sold with an existing handover date');
	}

	@IsTest
	static void testErrorOnUpdateNewlySoldOrderWithHandoverDate() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.prepareBuyerTestContext();
		ctx.insertOpportunity();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);
		insert vo;
		vo.Handover_Date__c = Date.today();
		ctx.setOpenPurchase(vo);
		ShiftTesting.expectUpdateExceptionContains(vo, 'A vehicle order cannot be newly sold with an existing handover date');
	}

	@IsTest
	static void testDepositReturnOnVehicleReturn() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();
		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
		bctx.setOpenPurchase(vo);
		ShiftTesting.setOpenDeposit(vo);
		Test.startTest();
		update vo;

		bctx.setReturnedPurchase(vo);
		update vo;
		Vehicle_Order__c updatedVehicleOrder = [SELECT Deposit_Returned_On__c, Deposit_Returned_Reason__c FROM Vehicle_Order__c WHERE Id = :vo.Id];
		System.assertEquals(vo.Returned_On__c, updatedVehicleOrder.Deposit_Returned_On__c);
		System.assertEquals(ShiftConstants.VEHICLE_ORDER_DEPOSIT_RETURNED_REASON_CAR_RETURNED, updatedVehicleOrder.Deposit_Returned_Reason__c);
		Test.stopTest();
	}

	@IsTest
	static void testNoDepositReturnOnVehicleReturnWithNoDeposit() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();
		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
    Test.startTest();
		bctx.setOpenPurchase(vo);
		update vo;

		bctx.setReturnedPurchase(vo);
		update vo;
		Vehicle_Order__c updatedVehicleOrder = [SELECT Deposit_Returned_On__c, Deposit_Returned_Reason__c FROM Vehicle_Order__c WHERE Id = :vo.Id];
		System.assertEquals(null, updatedVehicleOrder.Deposit_Returned_On__c);
		System.assertEquals(null, updatedVehicleOrder.Deposit_Returned_Reason__c);
    Test.stopTest();
	}

	@IsTest
	static void testErrorOnVehicleWithIncompleteReturn() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);
		insert vo;
		ctx.setOpenPurchase(vo);
		update vo;

		vo.Returned_On__c = Date.today();
		ShiftTesting.expectUpdateExceptionContains(vo, 'If Returned On is specified, Returned Reason must also be specified');

		vo.Returned_On__c = null;
		vo.Returned_Reason__c = ShiftConstants.VEHICLE_ORDER_RETURNED_REASON_BUYERS_REMORSE;
		ShiftTesting.expectUpdateExceptionContains(vo, 'If Returned Reason is specified, Returned On must also be specified');
	}

	@IsTest
	static void testOnDepositTriggerReturned() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);

		vo.Deposit_Accepted_On__c = Date.today();
		vo.Deposit_Returned_On__c = null;
		vo.Deposit_Expired__c = false;
		insert vo;
		v = [SELECT Id, On_Deposit__c FROM Vehicle__c WHERE Id = :v.Id];
		System.assertEquals(v.On_Deposit__c, true);

		vo.Deposit_Returned_On__c = Date.today();
		vo.Deposit_Returned_Reason__c = ShiftConstants.VEHICLE_ORDER_RETURNED_REASON_BUYERS_REMORSE;
		update vo;
		v = [SELECT Id, On_Deposit__c FROM Vehicle__c WHERE Id = :v.Id];
		System.assertEquals(false, v.On_Deposit__c);
	}


	@IsTest
	static void testOnDepositTriggerExpired() {
		ShiftTesting.BuyerTestContext ctx = ShiftTesting.createAndInsertBuyer();
		Vehicle__c v = ctx.createAndInsertVehicle();
		Vehicle_Order__c vo = ctx.createVehicleOrder(v);

		vo.Deposit_Accepted_On__c = Date.today();
		vo.Deposit_Returned_On__c = null;
		vo.Deposit_Expired__c = false;
		insert vo;

		v = [SELECT Id, On_Deposit__c FROM Vehicle__c WHERE Id = :v.Id];
		System.assertEquals(true, v.On_Deposit__c);

		vo.Deposit_Expired__c = true;
		update vo;
		v = [SELECT Id, On_Deposit__c FROM Vehicle__c WHERE Id = :v.Id];
		System.assertEquals(false, v.On_Deposit__c);
	}

	@IsTest
	static void testAssignPurchasedVehicleOrder() {
		ShiftTesting.SellerTestContext sctx = ShiftTesting.createAndInsertSeller();
		ShiftTesting.BuyerTestContext bctx = ShiftTesting.createAndInsertBuyer();
		Vehicle_Order__c vo = bctx.createVehicleOrder(sctx.vehicle);
		insert vo;
		Test.startTest();
		System.assertEquals(null, [SELECT Purchased_Vehicle_Order_ID__c FROM Vehicle__c WHERE Id = :sctx.vehicle.Id].Purchased_Vehicle_Order_ID__c);

		vo.Final_Sale_Price__c = 10000.00;
		vo.Taxes_And_Registration__c = 1000.00;
		vo.Payment_Method__c = ShiftConstants.VEHICLE_ORDER_PAYMENT_METHOD_CASH;
		update vo;
		System.assertEquals(null, [SELECT Purchased_Vehicle_Order_ID__c FROM Vehicle__c WHERE Id = :sctx.vehicle.Id].Purchased_Vehicle_Order_ID__c);

		bctx.setOpenPurchase(vo);
		update vo;
		System.assertEquals(vo.Id, [SELECT Purchased_Vehicle_Order_ID__c FROM Vehicle__c WHERE Id = :sctx.vehicle.Id].Purchased_Vehicle_Order_ID__c);

		bctx.setReturnedPurchase(vo);
		update vo;
		System.assertEquals(null, [SELECT Purchased_Vehicle_Order_ID__c FROM Vehicle__c WHERE Id = :sctx.vehicle.Id].Purchased_Vehicle_Order_ID__c);
		Test.stopTest();
	}
}