objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Advance_Funds_Amount__c</fullName>
        <label>Advance Funds Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_Funds_Fee_2__c</fullName>
        <label>Advance Funds Fee 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_Funds_Fee_Override__c</fullName>
        <label>Advance Funds Fee Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_Funds_Type__c</fullName>
        <label>Advance Funds Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lienholder Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Car_Commission__c</fullName>
        <label>Car Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Direct_To_Wholesale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Direct To Wholesale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entered_Stage_Sold__c</fullName>
        <label>Entered Stage Sold</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Final_Guaranteed_Price_2__c</fullName>
        <label>Final Guaranteed Price 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Flat_Fee__c</fullName>
        <label>Flat Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Guaranteed_Price__c</fullName>
        <label>Guaranteed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Paperwork_Fee_2__c</fullName>
        <label>Late Paperwork Fee 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payoff_Amount__c</fullName>
        <label>Payoff Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pickup_Fee_Revenue__c</fullName>
        <label>Pickup Fee Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pickup_Fee__c</fullName>
        <defaultValue>100</defaultValue>
        <description>Pickup Fee defaults to $100 but can be reduced to $0 if &quot;On The Spot Pickup&quot; or &quot;Seller Drop-Off&quot; is checked in the Evaluation. Change this field directly to override. Credit is split with the seller for non-Flat Fee deals.</description>
        <inlineHelpText>Pickup Fee defaults to $100 but can be reduced to $0 if &quot;On The Spot Pickup&quot; or &quot;Seller Drop-Off&quot; is checked in the Evaluation. Change this field directly to override. Credit is split with the seller for non-Flat Fee deals.</inlineHelpText>
        <label>Pickup Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_Strategy__c</fullName>
        <label>Pricing Strategy</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Fee - Dollar Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Fee - Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Price - 0% Upside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specific Car Search</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referral_Payout__c</fullName>
        <label>Referral Payout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Referral_Program_Or_Promotion__c</fullName>
        <label>Referral Program Or Promotion</label>
        <picklist>
            <picklistValues>
                <fullName>AnyPerk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At2 Detail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoFresh Mobile Carwash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Pro Detailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California Detail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Challenge 4 Charity (Stanford)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Challenge 4 Charity (UCLA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Relocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrystalCity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCAutoShow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCLaunch250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dent Artist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dent Discount Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dents Doctor PDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DentSquad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DentX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detail Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFJ Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropbox San Francisco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EcoWash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ed&apos;s Mobile Detailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EuroPros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friends and Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoldenBright Detail Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grateful Dent PDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highland Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IndyExpress Mobile Detail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Seller_Costs_DMV__c</fullName>
        <label>Seller Costs DMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Costs_Repairs_Estimate__c</fullName>
        <label>Seller Costs Repairs Estimate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Costs_Repairs__c</fullName>
        <label>Seller Costs Repairs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Payment_Gross_2__c</fullName>
        <label>Seller Payment Gross 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Upside_Percentage__c</fullName>
        <label>Seller Upside Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trade_In_Credit_Amount__c</fullName>
        <label>Trade-In Credit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_In_Status__c</fullName>
        <inlineHelpText>Requested: trade needs pricing
Estimated: est. quote sent
Approved: price finalized; contract signed
Funded: credit applied to purchase (need team ld. approval)
Closed: return period elapsed--final settlement complete
Expired: buyer elects not to buy</inlineHelpText>
        <label>Trade-In Status</label>
        <picklist>
            <picklistValues>
                <fullName>Estimated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Was_Paid_On_Contract_Expiration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Was Paid On Contract Expiration</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <description>Vehicles are acquired from sellers and sold to buyers.</description>
    <fields>
        <fullName>Paperwork_Fee_Pending__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Admin field to track the Late Paperwork fee we will charge once the contract is signed for over 30 days and paperwork is missing.  This field should be updated by the updatePaperworkFeePending trigger.</description>
        <inlineHelpText>This field should be updated by the updatePaperworkFeePending trigger.</inlineHelpText>
        <label>Paperwork Fee Pending</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShiftPaymentsTest.cls
@IsTest
class ShiftPaymentsTest {
	@TestSetup static void setup() { ShiftTesting.setup(); }

	@IsTest
	static void testCalculateAdvanceFundsFee() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		o.Advance_Funds_Amount__c = 1000.0;
		o.LeadSource = ShiftConstants.LEAD_SOURCE_TESLA_REMARKETING;
		System.assertEquals(0.0, ShiftPayments.calculateAdvanceFundsFee(o));

		o.LeadSource = ShiftConstants.LEAD_SOURCE_WORD_OF_MOUTH;
		o.Advance_Funds_Fee_Override__c = null;
		System.assertEquals(ShiftConstants.ADVANCE_FUNDS_FEE, ShiftPayments.calculateAdvanceFundsFee(o));

		o.Advance_Funds_Fee_Override__c = 500.0;
		System.assertEquals(o.Advance_Funds_Fee_Override__c, ShiftPayments.calculateAdvanceFundsFee(o));
	}


	@IsTest
	static void testCalculateLatePaperWorkFee() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		Vehicle__c v = ShiftTesting.createVehicle();
		o.Entered_Stage_Sold__c = null;
		v.Paperwork_Fee_Pending__c = 100.0;
		System.assertEquals(0.0, ShiftPayments.calculateLatePaperWorkFee(o, v, null));

		o.Entered_Stage_Sold__c = null;
		System.assertEquals(0.0, ShiftPayments.calculateLatePaperWorkFee(o, v, Date.today().addDays(-20)));

		o.Entered_Stage_Sold__c = Date.today().addDays(-5);
		System.assertEquals(0.0, ShiftPayments.calculateLatePaperWorkFee(o, v, Date.today().addDays(-20)));

		o.Entered_Stage_Sold__c = Date.today().addDays(-5);
		System.assertEquals(v.Paperwork_Fee_Pending__c, ShiftPayments.calculateLatePaperWorkFee(o, v, Date.today().addDays(-50)));

		o.Entered_Stage_Sold__c = null;
		System.assertEquals(v.Paperwork_Fee_Pending__c, ShiftPayments.calculateLatePaperWorkFee(o, v, Date.today().addDays(-50)));
	}

	@IsTest
	static void testCalculatePickupFeeRevenue() {
		ShiftTesting.SellerTestContext ctx = ShiftTesting.prepareSellerTestContext();
		Opportunity o = ctx.opportunity;
		o.Guaranteed_Price__c = 10000.0;
		o.Pickup_Fee__c = 100.0;
		o.Final_Guaranteed_Price_2__c = ShiftPayments.calculateFinalGuaranteedPrice(o);
		o.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_STANDARD;
		o.Seller_Upside_Percentage__c = 50;

		System.assertEquals(50.0, ShiftPayments.calculatePickupFeeRevenue(o, 12000.0));

		o.Seller_Upside_Percentage__c = 20;
		System.assertEquals(80.0, ShiftPayments.calculatePickupFeeRevenue(o, 12000.0));

		o.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT;
		System.assertEquals(100.0, ShiftPayments.calculatePickupFeeRevenue(o, 12000.0));
	}

	@IsTest
	static void testCalculateAdvanceFundsNet() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		o.Advance_Funds_Amount__c = null;
		o.Seller_Costs_DMV__c = 0.0;
		o.Advance_Funds_Fee_2__c = 0.0;
		o.Late_Paperwork_Fee_2__c = 0.0;
		o.Seller_Costs_Repairs_Estimate__c = 0.0;
		o.Payoff_Amount__c = 0.0;
		System.assertEquals(0.0, ShiftPayments.calculateAdvanceFundsNet(o));

		o.Advance_Funds_Amount__c = 0.0;
		System.assertEquals(0.0, ShiftPayments.calculateAdvanceFundsNet(o));

		o.Advance_Funds_Amount__c = 5000.0;
		o.Seller_Costs_DMV__c = 500.0;
		System.assertEquals(4500.0, ShiftPayments.calculateAdvanceFundsNet(o));

		o.Advance_Funds_Fee_2__c = 500.0;
		System.assertEquals(4000.0, ShiftPayments.calculateAdvanceFundsNet(o));

		o.Late_Paperwork_Fee_2__c = 500.0;
		System.assertEquals(3500.0, ShiftPayments.calculateAdvanceFundsNet(o));

		o.Seller_Costs_Repairs__c = 500.0;
		System.assertEquals(3000.0, ShiftPayments.calculateAdvanceFundsNet(o));

		o.Seller_Costs_Repairs__c = null;
		o.Seller_Costs_Repairs_Estimate__c = 500.0;
		System.assertEquals(3000.0, ShiftPayments.calculateAdvanceFundsNet(o));

		o.Payoff_Amount__c = 1000.0;
		System.assertEquals(2000.0, ShiftPayments.calculateAdvanceFundsNet(o));
	}


	@IsTest
	static void testCalculateSellerRepairCosts() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		o.Seller_Costs_Repairs__c = null;
		o.Seller_Costs_Repairs_Estimate__c = 500.0;
		System.assertEquals(500.0, ShiftPayments.calculateSellerRepairCosts(o));

		o.Seller_Costs_Repairs__c = 1000.0;
		System.assertEquals(1000.0, ShiftPayments.calculateSellerRepairCosts(o));
	}

	@IsTest
	static void testCalculateReferralPayout() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		o.Referral_Program_Or_Promotion__c = ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_ANYPERK;
		System.assertEquals(300.0, ShiftPayments.calculateReferralPayout(o));

		o.Referral_Program_Or_Promotion__c = ShiftConstants.REFERRAL_PROGRAM_OR_PROMOTION_GOOGLE;
		System.assertEquals(200.0, ShiftPayments.calculateReferralPayout(o));
	}

	@IsTest
	static void testCalculateSellerPaymentGross() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		o.Seller_Upside_Percentage__c = 50;
		o.Final_Guaranteed_Price_2__c = 10000.0;

		System.assertEquals(15000.0, ShiftPayments.calculateSellerPaymentGross(o, 20000.0));
		System.assertEquals(10000.0, ShiftPayments.calculateSellerPaymentGross(o, 9000.0));

		o.Seller_Upside_Percentage__c = 60;
		System.assertEquals(16000.0, ShiftPayments.calculateSellerPaymentGross(o, 20000.0));
	}

	@IsTest
	static void testCalculateSellerPaymentNet() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		o.Seller_Payment_Gross_2__c = 16000.0;
		o.Seller_Costs_DMV__c = 0.0;
		o.Seller_Costs_Repairs__c = 0.0;
		o.Late_Paperwork_Fee_2__c = 0.0;
		o.Payoff_Amount__c = 0.0;
		o.Trade_In_Credit_Amount__c = 0.0;
		o.Referral_Payout__c = 0.0;
		o.Advance_Funds_Amount__c = 0.0;
		o.Flat_Fee__c = 0.0;
		o.Direct_To_Wholesale__c = false;
		o.Was_Paid_On_Contract_Expiration__c = false;
		o.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_STANDARD;

		System.assertEquals(16000.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Seller_Costs_DMV__c = 1000.0;
		System.assertEquals(15000.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Seller_Costs_Repairs__c = 500.0;
		System.assertEquals(14500.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Late_Paperwork_Fee_2__c = 500.0;
		System.assertEquals(14000.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Payoff_Amount__c = 5000.0;
		System.assertEquals(9000.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Referral_Payout__c = 500.0;
		System.assertEquals(9500.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Flat_Fee__c = 2000.0;
		o.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT;
		System.assertEquals(7500.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Final_Guaranteed_Price_2__c = 10000.0;
		o.Was_Paid_On_Contract_Expiration__c = true;
		System.assertEquals(6000.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Direct_To_Wholesale__c = true;
		System.assertEquals(5000.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Advance_Funds_Amount__c = 3000.0;
		o.Advance_Funds_Type__c = ShiftConstants.ADVANCE_FUNDS_TYPE_FULL;
		System.assertEquals(13000.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Advance_Funds_Type__c = ShiftConstants.ADVANCE_FUNDS_TYPE_LIENHOLDER_ONLY;
		o.Trade_In_Credit_Amount__c = 2000.0;
		System.assertEquals(7500.0, ShiftPayments.calculateSellerPaymentNet(o));

		o.Trade_In_Status__c = ShiftConstants.TRADE_IN_STATUS_FUNDED;
		o.Trade_In_Credit_Amount__c = 15000.0;
		System.assertEquals(1000.0, ShiftPayments.calculateSellerPaymentNet(o));
	}

	@IsTest
	static void testCalculateCarCommission() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		o.Seller_Upside_Percentage__c = 50;
		o.Guaranteed_Price__c = 10000.0;
		o.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_STANDARD;
		System.assertEquals(5000.0, ShiftPayments.calculateCarCommission(o, 20000.0));

		o.Seller_Upside_Percentage__c = 90;
		System.assertEquals(1000.0, ShiftPayments.calculateCarCommission(o, 20000.0));

		o.Flat_Fee__c = 500.0;
		o.Pricing_Strategy__c = ShiftConstants.PRICING_STRATEGY_FLAT_FEE_DOLLAR_AMOUNT;
		System.assertEquals(500.0, ShiftPayments.calculateCarCommission(o, 20000.0));
	}


	@IsTest
	static void testCalculateTotalRevenue() {
		Opportunity o = ShiftTesting.createSellerOpportunity();
		o.Car_Commission__c = 1000.0;
		o.Late_Paperwork_Fee_2__c = 100.0;
		o.Advance_Funds_Fee_2__c = 100.0;
		o.Pickup_Fee_Revenue__c = 800.0;

		System.assertEquals(2000.0, ShiftPayments.calculateTotalRevenue(o));
	}
}