objects/Parking_Lot__c.object
<CustomObject>
    <description>Represents a parking lot location</description>
    <fields>
        <fullName>Is_Region_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Region Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region_ID__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Parking Lots</relationshipLabel>
        <relationshipName>Parking_Lots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shift_UQ_Name_Region_ID__c</fullName>
        <description>Custom field to hold uniqueness constraint across Name and Region_ID as Name:Region_ID</description>
        <inlineHelpText>Custom field to hold uniqueness constraint across Name and Region_ID as Name:Region_ID</inlineHelpText>
        <label>Shift UQ Name Region ID</label>
        <length>99</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Shift_UQ_Region_Primary__c</fullName>
        <label>Shift UQ Region Primary</label>
        <length>99</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Parking Lot</label>
    <nameField>
        <label>Parking Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parking Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShiftParkingLots.cls
public class ShiftParkingLots {
	public static Map<Id, Id> getRegionIdToPrimaryParkingLotIdMap(Set<Id> regionIds) {
		List<Parking_Lot__c> primaryParkingLots = [
			SELECT Id, Region_ID__c
			FROM Parking_Lot__c
			WHERE
				Region_ID__c IN :regionIds AND
				Is_Region_Primary__c = TRUE
		];
		Map<Id, Id> regionIdToPrimaryParkingLotId = new Map<Id, Id>();
		for (Parking_Lot__c primaryParkingLot : primaryParkingLots) {
			regionIdToPrimaryParkingLotId.put(primaryParkingLot.Region_ID__c, primaryParkingLot.Id);
		}
		return regionIdToPrimaryParkingLotId;
	}

	static void setNameRegionIDUniqueKey(List<Parking_Lot__c> parkingLots) {
		for (Parking_Lot__c p : parkingLots) {
			p.Shift_UQ_Name_Region_ID__c = p.Region_ID__c + ':' + p.Name;
		}
	}

	static void setRegionPrimaryUniqueKey(List<Parking_Lot__c> parkingLots) {
		for (Parking_Lot__c p : parkingLots) {
			if (p.Is_Region_Primary__c) {
				p.Shift_UQ_Region_Primary__c = p.Region_ID__c + ':primary';
			}
		}
	}

	public static void beforeInsert(List<Parking_Lot__c> newParkingLots) {
		setNameRegionIDUniqueKey(newParkingLots);
		setRegionPrimaryUniqueKey(newParkingLots);
	}

	public static void beforeUpdate(Map<Id, Parking_Lot__c> oldParkingLotMap, List<Parking_Lot__c> newParkingLots) {
		setNameRegionIDUniqueKey(newParkingLots);
		setRegionPrimaryUniqueKey(newParkingLots);
	}
}