objects/Region__c.object
<CustomObject>
    <description>Represents a region for vehicle activity (acquire, sell, etc).</description>
    <fields>
        <fullName>Shift_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Shift Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Skedulo_Region_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Skedulo Region</label>
        <referenceTo>sked__Region__c</referenceTo>
        <relationshipLabel>Skedulo Regions</relationshipLabel>
        <relationshipName>Sked_Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ShiftRegionTriggersTest.cls
@IsTest
class ShiftRegionTriggersTest {
	@TestSetup static void setup() { ShiftTesting.setup(); }

	static void expectSkeduloRegionSynced(Id regionId) {
		Region__c region = [
			SELECT
				Name,
				Timezone__c,
				Skedulo_Region_ID__r.Id,
				Skedulo_Region_ID__r.Name,
				Skedulo_Region_ID__r.sked__Timezone__c
			FROM Region__c
			WHERE Id = :regionId
		];
		System.assertEquals(region.Name, region.Skedulo_Region_ID__r.Name);
		System.assertEquals(region.Timezone__c, region.Skedulo_Region_ID__r.sked__Timezone__c);
	}

	@IsTest
	static void testSyncSkeduloRegion() {
		Region__c r = new Region__c(
			Name = ShiftUtil.randomStringLowercaseAlphanum(8),
			Shift_Key__c = ShiftUtil.randomStringLowercaseAlphanum(8),
			Timezone__c = ShiftTesting.REGION_TIMEZONE_TESTING
		);
		insert r;
		expectSkeduloRegionSynced(r.Id);

		r.Timezone__c = ShiftTesting.REGION_TIMEZONE_TESTING + '/2';
		update r;
		expectSkeduloRegionSynced(r.Id);

		delete r;
		System.assertEquals(0, [SELECT COUNT() FROM sked__Region__c WHERE Name = :r.Name]);
	}
}