objects/Skedulo_API_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>API_Token__c</fullName>
        <label>API Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Skedulo API Setting</label>
</CustomObject>

classes/skedLocationService_Test.cls
@isTest
public class skedLocationService_Test {

    static testmethod void testLocationService() {
        Skedulo_API_Setting__c skeduloApiSetting = Skedulo_API_Setting__c.getOrgDefaults();
        skeduloApiSetting.API_Token__c = 'apiToken';
        upsert skeduloApiSetting;
        
        Test.startTest();
        
        skedLocationService_MockTest mockClass = new skedLocationService_MockTest();
        Test.setMock(HttpCalloutMock.class, mockClass);
        
        skedLocationService.getAddressGeoLocation('test address');
        
        Test.stopTest();
    }
    
}