objects/Subregion__c.object
<CustomObject>
    <fields>
        <fullName>Region_ID__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Subregions</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shift_UQ_Name_Region_ID__c</fullName>
        <description>Custom field to hold uniqueness constraint across Name and Region_ID as Name:Region_ID</description>
        <inlineHelpText>Custom field to hold uniqueness constraint across Name and Region_ID as Name:Region_ID</inlineHelpText>
        <label>Shift UQ Name Region ID</label>
        <length>99</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subregion</label>
    <nameField>
        <label>Subregion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subregions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShiftSubregions.cls
public class ShiftSubregions {
	static void setNameRegionIDUniqueKey(List<Subregion__c> subregions) {
		for (Subregion__c r : subregions) {
			r.Shift_UQ_Name_Region_ID__c = r.Region_ID__c + ':' + r.Name;
		}
	}

	public static void beforeInsert(List<Subregion__c> newSubregions) {
		setNameRegionIDUniqueKey(newSubregions);
	}

	public static void beforeUpdate(Map<Id, Subregion__c> oldSubregionMap, List<Subregion__c> newSubregions) {
		setNameRegionIDUniqueKey(newSubregions);
	}
}